#!/bin/sh
# sys module checks. Run by tools/ci.sh inside its private mount namespace (tmpfs on
# /etc/mini-router), with OUT and ROOT set and the home / lab configs rendered to $OUT/home, $OUT/lab.
#  1. /etc/localtime (TZif built from the POSIX TZ string): glibc reading the file must agree with
#     glibc interpreting the POSIX string itself, every 5 days over two years (DST edges included)
#  2. rendered service settings: home unchanged (ntpd, dropbear), lab: NTP server, LAN-only SSH on
#     the LAN-zone addresses only, tailscale port, boot order for nf_conntrack sysctls
#  3. crontab: managed block with fixed commands only; `mr sys run` refuses anything else
#  4. authorized_keys: managed block, and every line this host already had is still there
#  5. every rendered conf.d file parses as sh and sets what the init scripts read
#  6. `mr sys backup`: archive content, secrets only on request and never the web UI password hash
#  7. sysctl, real kernel (network namespace): after the rendered file is loaded no netdev sends ICMP
#     redirects — neither one that existed before nor one created after
set -eu
: "${OUT:?}" "${ROOT:?}"
MR=$OUT/mr-host
H=$OUT/home L=$OUT/lab
fail() { echo "FAIL: $*"; exit 1; }
ok() { echo "ok: $*"; }

# 1. TZif vs glibc's own POSIX TZ parser
check_tz() { # name tzstring
	f=$OUT/$1/etc/localtime
	[ -s "$f" ] || fail "$1: no /etc/localtime"
	head -c 5 "$f" | grep -q '^TZif2' || fail "$1: /etc/localtime is not TZif v2"
	t=1767225600 # 2026-01-01
	n=0
	while [ "$n" -lt 146 ]; do
		a=$(TZ=":$f" date -d "@$t" '+%F %T %Z %z')
		b=$(TZ="$2" date -d "@$t" '+%F %T %Z %z')
		[ "$a" = "$b" ] || fail "$1 at $t: TZif says '$a', POSIX '$2' says '$b'"
		t=$((t + 5 * 86400 + 3600))
		n=$((n + 1))
	done
	ok "$1 /etc/localtime matches '$2' ($n instants)"
}
check_tz home '<+08>-8'
check_tz lab 'CET-1CEST,M3.5.0,M10.5.0/3'
[ "$(TZ=":$L/etc/localtime" date -d @1784116800 +%z)" = "+0200" ] || fail "lab: July is not CEST"
[ "$(TZ=":$L/etc/localtime" date -d @1768478400 +%z)" = "+0100" ] || fail "lab: January is not CET"

# 2. service settings
[ "$(cat "$H/etc/conf.d/ntpd")" = '# generated by mr
NTPD_OPTS="-N -S /usr/libexec/mr/clock-save -p ntp.tencent.com -p ntp1.aliyun.com -p ntp.ntsc.ac.cn -p cn.ntp.org.cn"' ] || fail "home ntpd changed: $(cat "$H/etc/conf.d/ntpd")"
[ "$(sed -n 's/^DROPBEAR_OPTS=//p' "$H/etc/conf.d/dropbear")" = '"-p 22 -K 300 -s -g"' ] || fail "home dropbear changed"
grep -q ' -l"$' "$L/etc/conf.d/ntpd" || fail "lab: ntpd not serving (-l)"
if grep -q ' -l"$' "$H/etc/conf.d/ntpd"; then fail "home: ntpd serves time without ntp_server"; fi
grep -q 'DROPBEAR_OPTS="-p 192.168.1.6:22 -p 192.168.30.1:22 -K 300 -s -g"' "$L/etc/conf.d/dropbear" || fail "lab dropbear: $(cat "$L/etc/conf.d/dropbear")"
if grep -q '192.168.20.1' "$L/etc/conf.d/dropbear"; then fail "lab: SSH listens on the guest network"; fi
grep -qx 'TS_PORT=41642' "$L/etc/conf.d/tailscale" || fail "lab: tailscale port"
grep -q 'udp dport 41642 accept comment "tailscale"' "$OUT/lab-nft.nft" || fail "lab: tailscale port not opened"
if grep -Eq '(dport|,|\{) 123( |,|$)' "$OUT/lab-nft.nft"; then fail "lab: NTP opened in the firewall"; fi
for t in home lab; do
	grep -qx 'nf_conntrack' "$OUT/$t/etc/modules-load.d/mr-sys.conf" || fail "$t: nf_conntrack not in modules-load.d"
	grep -qx 'rc_after="modules"' "$OUT/$t/etc/conf.d/sysctl" || fail "$t: sysctl not ordered after modules"
done
grep -qx 'net.netfilter.nf_conntrack_max=100000' "$H/etc/sysctl.d/90-mini-router.conf" || fail "home conntrack max"
grep -qx 'net.netfilter.nf_conntrack_max=131072' "$L/etc/sysctl.d/90-mini-router.conf" || fail "lab conntrack max override"
ok "service settings"

# 3. crontab
C=$L/etc/crontabs/root
if [ -e "$H/etc/crontabs/root" ]; then fail "home: crontab rendered without schedules"; fi
grep -qx 'crond' "$L/etc/mini-router/gen/services" || fail "lab: crond not enabled"
if grep -qx 'crond' "$H/etc/mini-router/gen/services"; then fail "home: crond enabled without schedules"; fi
grep -qx "export TZ='CET-1CEST,M3.5.0,M10.5.0/3'" "$L/etc/conf.d/crond" || fail "lab: crond zone"
block=$(sed -n '/^# --- begin mini-router schedules/,/^# --- end mini-router schedules/p' "$C" | grep -v '^#')
[ "$(echo "$block" | wc -l)" = 4 ] || fail "lab crontab: want 4 jobs, got: $block"
echo "$block" | while read -r m hr d mo w cmd; do
	echo "$m $hr $d $mo $w" | grep -Eq '^[0-9]+ [0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+$' || fail "bad time spec: $m $hr $d $mo $w"
	echo "$cmd" | grep -Eqx '/usr/sbin/mr sys run (reboot|restart [a-z0-9.-]+|reconnect [a-z0-9_-]+)' || fail "unexpected crontab command: $cmd"
done
grep -qx '15 \*/6 \* \* \* /usr/sbin/mr sys run reconnect iptv' "$C" || fail "lab crontab: reconnect iptv"
CFG="-c $OUT/lab.yaml -s $OUT/lab-secrets.yaml"
for bad in "restart dnsmasq;reboot" "restart mr-network" "reconnect office" "shutdown" "reboot now" "restart sshd"; do
	# shellcheck disable=SC2086
	if "$MR" $CFG sys run $bad >/dev/null 2>&1; then fail "mr sys run $bad accepted"; fi
done
ok "crontab + mr sys run"

# 4. authorized_keys: managed block + everything this host already had
K=$L/root/.ssh/authorized_keys
[ "$(stat -c %a "$K")" = 600 ] || fail "authorized_keys mode"
[ "$(sed -n '/^# --- begin mini-router managed keys/,/^# --- end mini-router managed keys/p' "$K" | grep -c '^[a-z]')" = 2 ] || fail "lab: managed keys"
if [ -r /root/.ssh/authorized_keys ]; then
	n=0
	while IFS= read -r line; do
		[ -n "$line" ] || continue
		grep -qxF -- "$line" "$K" || fail "an existing authorized_keys line was dropped"
		n=$((n + 1))
	done < /root/.ssh/authorized_keys
	ok "authorized_keys keeps this host's $n existing lines"
fi
if [ -e "$H/root/.ssh/authorized_keys" ]; then fail "home: authorized_keys rendered without managed keys"; fi
ok "authorized_keys"

# 5. conf.d files are valid sh and set what the init scripts use
for t in home lab; do
	for f in "$OUT/$t"/etc/conf.d/ntpd "$OUT/$t"/etc/conf.d/dropbear "$OUT/$t"/etc/conf.d/tailscale "$OUT/$t"/etc/conf.d/mr-panel "$OUT/$t"/etc/conf.d/sysctl "$OUT/$t"/etc/conf.d/crond; do
		[ -e "$f" ] || continue
		sh -n "$f" || fail "$f: sh syntax"
	done
done
# shellcheck disable=SC1091
v=$(. "$L/etc/conf.d/mr-panel"; echo "$PANEL_ADDR")
[ "$v" = 192.168.1.6 ] || fail "PANEL_ADDR=$v"
# shellcheck disable=SC1091
v=$(. "$L/etc/conf.d/crond"; echo "$CRON_OPTS|$TZ")
[ "$v" = "-c /etc/crontabs|CET-1CEST,M3.5.0,M10.5.0/3" ] || fail "crond conf: $v"
ok "conf.d files"

# 6. backup (reads the live paths; /etc/mini-router is the CI tmpfs)
mkdir -p /etc/mini-router/dns /etc/mini-router/proxy
cp "$OUT/lab.yaml" /etc/mini-router/router.yaml
{ cat "$OUT/lab-secrets.yaml"; echo 'webui_password: "pbkdf2-sha256$120000$00$11"'; } > /etc/mini-router/secrets.yaml
echo "ci.example" > /etc/mini-router/proxy/ci.domains
ln -sf /etc/shadow /etc/mini-router/proxy/leak.domains
B=$OUT/sys-backup
rm -rf "$B" && mkdir -p "$B"
"$MR" sys backup "$B/plain.tgz" 2>/dev/null
"$MR" sys backup -secrets "$B/full.tgz" 2>/dev/null
tar tzf "$B/plain.tgz" | sort > "$B/plain.list"
grep -qx 'etc/mini-router/router.yaml' "$B/plain.list" || fail "backup: no router.yaml"
grep -qx 'etc/mini-router/proxy/ci.domains' "$B/plain.list" || fail "backup: no proxy list"
grep -qx 'etc/mini-router/dns/cloudflare-dot.domains' "$B/plain.list" || fail "backup: no dns list"
if grep -q 'secrets.yaml\|leak.domains' "$B/plain.list"; then fail "plain backup has secrets or followed a symlink"; fi
tar xzf "$B/full.tgz" -C "$B" etc/mini-router/secrets.yaml
grep -q '^pppoe_password:' "$B/etc/mini-router/secrets.yaml" || fail "backup -secrets: no secrets"
if grep -q webui_password "$B/etc/mini-router/secrets.yaml"; then fail "backup contains the web UI password hash"; fi
rm -f /etc/mini-router/proxy/leak.domains
ok "backup"

# 7. ICMP redirects off everywhere: the kernel sends one when conf.all OR conf.<dev> is set. Writing
#    conf.default copies the value to every netdev whose own value was never written (the boot run:
#    nothing else sets send_redirects); a netdev created later starts from default. (One created after
#    an earlier write to default also inherits the "written" flag and misses later changes of default.)
NS=mrcisys$$
ip netns add "$NS"
# shellcheck disable=SC2064
trap "ip netns del $NS 2>/dev/null" EXIT
ip -n "$NS" link add early type dummy
grep '^net\.ipv4\.conf\.' "$H/etc/sysctl.d/90-mini-router.conf" > "$OUT/sys-netns.conf"
ip netns exec "$NS" sysctl -q -p "$OUT/sys-netns.conf"
ip -n "$NS" link add late type dummy
for d in all default early late; do
	v=$(ip netns exec "$NS" cat "/proc/sys/net/ipv4/conf/$d/send_redirects")
	[ "$v" = 0 ] || fail "send_redirects on $d is $v after loading the rendered sysctl file"
done
ip netns del "$NS"
trap - EXIT
ok "no ICMP redirects on netdevs created before or after the sysctl file"
