#!/bin/sh
# sys module checks. Run by tools/ci.sh inside its private mount namespace (tmpfs on
# /etc/mini-router), with OUT and ROOT set and the home / lab configs rendered to $OUT/home, $OUT/lab.
#  1. /etc/localtime (TZif built from the POSIX TZ string): glibc reading the file must agree with
#     glibc interpreting the POSIX string itself, every 5 days over two years (DST edges included)
#  2. rendered service settings: home unchanged (ntpd, dropbear), lab: NTP server, LAN-only SSH on
#     the LAN-zone addresses only, tailscale port, boot order for nf_conntrack sysctls
#  3. crontab: managed block with fixed commands only (+ the DDNS check); `mr sys run` refuses anything
#     else; `mr ddns status` works offline and never shows the token
#  4. authorized_keys: managed block (login keys), and every line
#     this host already had is still there
#  5. every rendered conf.d file parses as sh and sets what the init scripts read
#  6. `mr sys backup`: archive content, secrets only on request and never the web UI password hash
#  7. sysctl, real kernel (network namespace): after the rendered file is loaded no netdev sends ICMP
#     redirects — neither one that existed before nor one created after
#  8. Wake-on-LAN, real sockets (two network namespaces): `mr wol` sends three 102-byte magic packets
#     from the router's LAN address to the LAN broadcast through br-lan; a host behind the bridge gets
#     them, a WAN-side netdev with the default route sends nothing; bad targets are refused
#  9. events and notifications, real processes: boot / shutdown records, login locks pushed to a local
#     webhook (one message per burst), a failing webhook backed off (event.due), test, recovery, no secret
# 10. `mr doctor` on this host: every check, JSON and text
set -eu
: "${OUT:?}" "${ROOT:?}"
MR=$OUT/mr-host
H=$OUT/home L=$OUT/lab
fail() { echo "FAIL: $*"; exit 1; }
ok() { echo "ok: $*"; }

# 1. TZif vs glibc's own POSIX TZ parser
check_tz() { # name tzstring
	f=$OUT/$1/etc/localtime
	[ -s "$f" ] || fail "$1: no /etc/localtime"
	head -c 5 "$f" | grep -q '^TZif2' || fail "$1: /etc/localtime is not TZif v2"
	t=1767225600 # 2026-01-01
	n=0
	while [ "$n" -lt 146 ]; do
		a=$(TZ=":$f" date -d "@$t" '+%F %T %Z %z')
		b=$(TZ="$2" date -d "@$t" '+%F %T %Z %z')
		[ "$a" = "$b" ] || fail "$1 at $t: TZif says '$a', POSIX '$2' says '$b'"
		t=$((t + 5 * 86400 + 3600))
		n=$((n + 1))
	done
	ok "$1 /etc/localtime matches '$2' ($n instants)"
}
check_tz home '<+08>-8'
check_tz lab 'CET-1CEST,M3.5.0,M10.5.0/3'
[ "$(TZ=":$L/etc/localtime" date -d @1784116800 +%z)" = "+0200" ] || fail "lab: July is not CEST"
[ "$(TZ=":$L/etc/localtime" date -d @1768478400 +%z)" = "+0100" ] || fail "lab: January is not CET"

# 2. service settings
[ "$(cat "$H/etc/conf.d/ntpd")" = '# generated by mr
NTPD_OPTS="-N -S /usr/libexec/mr/clock-save -p ntp.tencent.com -p ntp1.aliyun.com -p ntp.ntsc.ac.cn -p cn.ntp.org.cn"' ] || fail "home ntpd changed: $(cat "$H/etc/conf.d/ntpd")"
[ "$(sed -n 's/^DROPBEAR_OPTS=//p' "$H/etc/conf.d/dropbear")" = '"-p 22 -K 300 -s -g"' ] || fail "home dropbear changed"
grep -q ' -l"$' "$L/etc/conf.d/ntpd" || fail "lab: ntpd not serving (-l)"
if grep -q ' -l"$' "$H/etc/conf.d/ntpd"; then fail "home: ntpd serves time without ntp_server"; fi
grep -q 'DROPBEAR_OPTS="-p 192.168.1.6:22 -p 192.168.30.1:22 -K 300 -s -g"' "$L/etc/conf.d/dropbear" || fail "lab dropbear: $(cat "$L/etc/conf.d/dropbear")"
if grep -q '192.168.20.1' "$L/etc/conf.d/dropbear"; then fail "lab: SSH listens on the guest network"; fi
grep -qx 'TS_PORT=41642' "$L/etc/conf.d/tailscale" || fail "lab: tailscale port"
grep -q 'udp dport 41642 accept comment "tailscale"' "$OUT/lab-nft.nft" || fail "lab: tailscale port not opened"
if grep -Eq '(dport|,|\{) 123( |,|$)' "$OUT/lab-nft.nft"; then fail "lab: NTP opened in the firewall"; fi
for t in home lab; do
	grep -qx 'nf_conntrack' "$OUT/$t/etc/modules-load.d/mr-sys.conf" || fail "$t: nf_conntrack not in modules-load.d"
	grep -qx 'rc_after="modules"' "$OUT/$t/etc/conf.d/sysctl" || fail "$t: sysctl not ordered after modules"
done
grep -qx 'net.netfilter.nf_conntrack_max=100000' "$H/etc/sysctl.d/90-mini-router.conf" || fail "home conntrack max"
grep -qx 'net.netfilter.nf_conntrack_max=131072' "$L/etc/sysctl.d/90-mini-router.conf" || fail "lab conntrack max override"
ok "service settings"

# 3. crontab
C=$L/etc/crontabs/root
# home: no schedules, but the DDNS check and the certificate renewal
[ "$(grep -c '^[^#]' "$H/etc/crontabs/root")" = 2 ] && grep -q ' /usr/sbin/mr ddns sync --cron$' "$H/etc/crontabs/root" &&
	grep -q ' /usr/sbin/mr edge renew --cron$' "$H/etc/crontabs/root" || fail "home crontab: $(cat "$H/etc/crontabs/root")"
grep -qx 'crond' "$L/etc/mini-router/gen/services" || fail "lab: crond not enabled"
grep -qx 'crond' "$H/etc/mini-router/gen/services" || fail "home: crond not enabled"
grep -qx "export TZ='CET-1CEST,M3.5.0,M10.5.0/3'" "$L/etc/conf.d/crond" || fail "lab: crond zone"
block=$(sed -n '/^# --- begin mini-router schedules/,/^# --- end mini-router schedules/p' "$C" | grep -v '^#')
[ "$(echo "$block" | wc -l)" = 11 ] || fail "lab crontab: want 5 jobs + the DDNS check + the certificate check + the adblock check + the wifi, watchcat and presence ticks, got: $block"
echo "$block" | grep -qE '^[0-9]+ \* \* \* \* /usr/sbin/mr dns adblock update --cron$' || fail "lab crontab: hourly adblock check missing"
echo "$block" | while read -r m hr d mo w cmd; do
	if [ "$cmd" = "/usr/sbin/mr ddns sync --cron" ]; then
		[ "$m $hr $d $mo $w" = "*/10 * * * *" ] || fail "DDNS check time spec: $m $hr $d $mo $w"
		continue
	fi
	if [ "$cmd" = "/usr/sbin/mr edge renew --cron" ]; then
		echo "$m $hr $d $mo $w" | grep -Eq '^[0-9]{1,2} [2-5] \* \* \*$' || fail "certificate check time spec: $m $hr $d $mo $w"
		continue
	fi
	if [ "$cmd" = "/usr/sbin/mr dns adblock update --cron" ]; then
		echo "$m $hr $d $mo $w" | grep -Eq '^[0-9]{1,2} \* \* \* \*$' || fail "adblock check time spec: $m $hr $d $mo $w"
		continue
	fi
	if [ "$cmd" = "/usr/sbin/mr wifi tick" ] || [ "$cmd" = "/usr/sbin/mr watchcat tick" ] || [ "$cmd" = "/usr/sbin/mr presence tick" ]; then # per-minute ticks
		[ "$m $hr $d $mo $w" = "* * * * *" ] || fail "wifi tick time spec: $m $hr $d $mo $w"
		continue
	fi
	echo "$m $hr $d $mo $w" | grep -Eq '^[0-9]+ [0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+$' || fail "bad time spec: $m $hr $d $mo $w"
	echo "$cmd" | grep -Eqx '/usr/sbin/mr sys run (reboot|restart [a-z0-9.-]+|reconnect [a-z0-9_-]+|wol [A-Za-z0-9:-]+)' || fail "unexpected crontab command: $cmd"
done
grep -qx '15 \*/6 \* \* \* /usr/sbin/mr sys run reconnect iptv' "$C" || fail "lab crontab: reconnect iptv"
grep -qx '0 7 \* \* 1-5 /usr/sbin/mr sys run wol 02:00:00:00:00:10' "$C" || fail "lab crontab: wol"
grep -qx '\*/10 \* \* \* \* /usr/sbin/mr ddns sync --cron' "$C" || fail "lab crontab: no DDNS check"
CFG="-c $OUT/lab.yaml -s $OUT/lab-secrets.yaml"
for bad in "restart dnsmasq;reboot" "restart mr-network" "reconnect office" "shutdown" "reboot now" "restart sshd" "wol no-such-host" "wol 01:00:5e:00:00:01"; do
	# shellcheck disable=SC2086
	if "$MR" $CFG sys run $bad >/dev/null 2>&1; then fail "mr sys run $bad accepted"; fi
done
ok "crontab + mr sys run"

# 3b. DDNS: status works offline (no lease files here: nothing to publish; no request is made — a url:
#     source says it is looked up at the next sync) and never shows a secret; the home config has no DDNS
# shellcheck disable=SC2086
"$MR" $CFG ddns status > "$OUT/ddns-status.json"
python3 - "$OUT/ddns-status.json" <<'EOF' || fail "lab ddns status"
import json, sys
rows = json.load(open(sys.argv[1]))
want = [("home.example.com", "A", "active"), ("home.example.com", "AAAA", "router"), ("*.example.com", "A", "wan2"), ("nas.example.com", "AAAA", "::10"),
        ("cn.example.net", "A", "url:https://ip4.example.org/"), ("cn.example.net", "AAAA", "mac:02:00:00:00:00:10"),
        ("example.org", "A", "mac:02:00:00:00:00:10"), ("labhome.duckdns.org", "A", "active"), ("labhome.duckdns.org", "AAAA", "router"),
        ("dyn.example.org", "A", "203.0.113.10"), ("hook.example.org", "AAAA", "url:https://ip6.example.org/")]
got = [(r["name"], r["type"], r["source"]) for r in rows]
assert got == want, got
fixed = [r for r in rows if r["name"] == "dyn.example.org"]
assert fixed[0]["local"] == "203.0.113.10" and not fixed[0].get("published"), fixed
assert all(not r.get("published") and r.get("note") for r in rows if r not in fixed), rows
assert [r["note"] for r in rows if r["source"].startswith("url:")] == ["looked up at the next sync"] * 2, rows
assert {r["provider"] for r in rows} == {"cloudflare", "alidns", "dnspod", "duckdns", "dyndns2", "webhook"}, rows
EOF
if grep -qE 'lab-token|not-real' "$OUT/ddns-status.json"; then fail "ddns status shows a secret"; fi
"$MR" -c "$ROOT/examples/router.yaml" -s "$ROOT/mr/testdata/secrets.yaml" ddns status > "$OUT/ddns-home.json" || fail "home: ddns status"
python3 -c 'import json, sys; r = json.load(open(sys.argv[1])); assert len(r) == 4 and {x["provider"] for x in r} == {"cloudflare"} and sorted(x["type"] for x in r) == ["A", "A", "A", "AAAA"], r' \
	"$OUT/ddns-home.json" || fail "home: ddns status: $(cat "$OUT/ddns-home.json")"
if grep -q 'not-real' "$OUT/ddns-home.json"; then fail "home: ddns status shows a secret"; fi
# shellcheck disable=SC2086
if "$MR" $CFG ddns update nope.example.com >/dev/null 2>&1; then fail "ddns update of an unknown record accepted"; fi
ok "ddns status"

# 4. authorized_keys: managed block + everything this host already had
K=$L/root/.ssh/authorized_keys
[ "$(stat -c %a "$K")" = 600 ] || fail "authorized_keys mode"
block=$(sed -n '/^# --- begin mini-router managed keys/,/^# --- end mini-router managed keys/p' "$K")
[ "$(echo "$block" | grep -c '^[a-z]')" = 2 ] || fail "lab: managed keys (2 logins)"
if echo "$block" | grep -q '^command='; then fail "lab: forced command on a login key"; fi
if [ -r /root/.ssh/authorized_keys ]; then
	n=0
	while IFS= read -r line; do
		[ -n "$line" ] || continue
		grep -qxF -- "$line" "$K" || fail "an existing authorized_keys line was dropped"
		n=$((n + 1))
	done < /root/.ssh/authorized_keys
	ok "authorized_keys keeps this host's $n existing lines"
fi
if [ -e "$H/root/.ssh/authorized_keys" ]; then fail "home: authorized_keys rendered without managed keys"; fi
ok "authorized_keys"

# 5. conf.d files are valid sh and set what the init scripts use
for t in home lab; do
	for f in "$OUT/$t"/etc/conf.d/ntpd "$OUT/$t"/etc/conf.d/dropbear "$OUT/$t"/etc/conf.d/tailscale "$OUT/$t"/etc/conf.d/mr-panel "$OUT/$t"/etc/conf.d/sysctl "$OUT/$t"/etc/conf.d/crond; do
		[ -e "$f" ] || continue
		sh -n "$f" || fail "$f: sh syntax"
	done
done
# shellcheck disable=SC1091
v=$(. "$L/etc/conf.d/mr-panel"; echo "$PANEL_ADDR")
[ "$v" = 192.168.1.6 ] || fail "PANEL_ADDR=$v"
# shellcheck disable=SC1091
v=$(. "$L/etc/conf.d/crond"; echo "$CRON_OPTS|$TZ")
[ "$v" = "-c /etc/crontabs|CET-1CEST,M3.5.0,M10.5.0/3" ] || fail "crond conf: $v"
ok "conf.d files"

# 6. backup (reads the live paths; /etc/mini-router is the CI tmpfs)
mkdir -p /etc/mini-router/dns /etc/mini-router/proxy
cp "$OUT/lab.yaml" /etc/mini-router/router.yaml
{ cat "$OUT/lab-secrets.yaml"; echo 'webui_password: "pbkdf2-sha256$120000$00$11"'; } > /etc/mini-router/secrets.yaml
echo "ci.example" > /etc/mini-router/proxy/ci.domains
ln -sf /etc/shadow /etc/mini-router/proxy/leak.domains
B=$OUT/sys-backup
rm -rf "$B" && mkdir -p "$B"
"$MR" sys backup "$B/plain.tgz" 2>/dev/null
"$MR" sys backup -secrets "$B/full.tgz" 2>/dev/null
tar tzf "$B/plain.tgz" | sort > "$B/plain.list"
grep -qx 'etc/mini-router/router.yaml' "$B/plain.list" || fail "backup: no router.yaml"
grep -qx 'etc/mini-router/proxy/ci.domains' "$B/plain.list" || fail "backup: no proxy list"
grep -qx 'etc/mini-router/dns/cloudflare-dot.domains' "$B/plain.list" || fail "backup: no dns list"
if grep -q 'secrets.yaml\|leak.domains' "$B/plain.list"; then fail "plain backup has secrets or followed a symlink"; fi
tar xzf "$B/full.tgz" -C "$B" etc/mini-router/secrets.yaml
grep -q '^pppoe_password:' "$B/etc/mini-router/secrets.yaml" || fail "backup -secrets: no secrets"
if grep -q webui_password "$B/etc/mini-router/secrets.yaml"; then fail "backup contains the web UI password hash"; fi
rm -f /etc/mini-router/proxy/leak.domains
ok "backup"

# 7. ICMP redirects off everywhere: the kernel sends one when conf.all OR conf.<dev> is set. Writing
#    conf.default copies the value to every netdev whose own value was never written (the boot run:
#    nothing else sets send_redirects); a netdev created later starts from default. (One created after
#    an earlier write to default also inherits the "written" flag and misses later changes of default.)
NS=mrcisys$$
ip netns add "$NS"
# shellcheck disable=SC2064
trap "ip netns del $NS 2>/dev/null" EXIT
ip -n "$NS" link add early type dummy
grep '^net\.ipv4\.conf\.' "$H/etc/sysctl.d/90-mini-router.conf" > "$OUT/sys-netns.conf"
ip netns exec "$NS" sysctl -q -p "$OUT/sys-netns.conf"
ip -n "$NS" link add late type dummy
for d in all default early late; do
	v=$(ip netns exec "$NS" cat "/proc/sys/net/ipv4/conf/$d/send_redirects")
	[ "$v" = 0 ] || fail "send_redirects on $d is $v after loading the rendered sysctl file"
done
ip netns del "$NS"
trap - EXIT
ok "no ICMP redirects on netdevs created before or after the sysctl file"

# 8. Wake-on-LAN through br-lan (lab LAN 192.168.1.6/24) to a receiver in another namespace
NA=mrciwola$$ NB=mrciwolb$$
ip netns add "$NA"
ip netns add "$NB"
# shellcheck disable=SC2064
trap "ip netns del $NA 2>/dev/null; ip netns del $NB 2>/dev/null" EXIT
ip -n "$NA" link set lo up
ip -n "$NA" link add br-lan type bridge
ip -n "$NA" link add wol0 type veth peer name wol1 netns "$NB"
ip -n "$NA" link set wol0 master br-lan
ip -n "$NA" link set wol0 up
ip -n "$NA" addr add 192.168.1.6/24 dev br-lan
ip -n "$NA" link set br-lan up
ip -n "$NA" link add wan0 type dummy
ip -n "$NA" addr add 10.99.0.2/24 dev wan0
ip -n "$NA" link set wan0 up
ip -n "$NA" route add default via 10.99.0.1 dev wan0
ip -n "$NB" addr add 192.168.1.50/24 dev wol1
ip -n "$NB" link set wol1 up
rm -f "$OUT/wol.ready" "$OUT/wol.rx"
ip netns exec "$NB" python3 - "$OUT/wol" <<'EOF' &
import socket, sys
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind(("", 9))
s.settimeout(5)
open(sys.argv[1] + ".ready", "w").close()
got = []
try:
    while len(got) < 3:
        d, a = s.recvfrom(512)
        got.append("%s %s" % (d.hex(), a[0]))
except socket.timeout:
    pass
open(sys.argv[1] + ".rx", "w").write("".join(g + "\n" for g in got))
EOF
RX=$!
i=0
while [ ! -e "$OUT/wol.ready" ] && [ $i -lt 50 ]; do sleep 0.1; i=$((i + 1)); done
tx0=$(ip netns exec "$NA" cat /sys/class/net/wan0/statistics/tx_packets)
# shellcheck disable=SC2086
ip netns exec "$NA" "$MR" $CFG wol 02:00:00:00:00:01 > "$OUT/wol.json" || fail "mr wol"
wait "$RX" || true
want="ffffffffffff$(printf '020000000001%.0s' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16) 192.168.1.6"
[ "$(grep -c . "$OUT/wol.rx")" = 3 ] || fail "wol: want 3 packets, got: $(cat "$OUT/wol.rx")"
while read -r line; do [ "$line" = "$want" ] || fail "wol packet: $line"; done < "$OUT/wol.rx"
grep -q '"broadcast":"192.168.1.255"' "$OUT/wol.json" || fail "wol answer: $(cat "$OUT/wol.json")"
[ "$(ip netns exec "$NA" cat /sys/class/net/wan0/statistics/tx_packets)" = "$tx0" ] || fail "wol: packets left through the WAN"
for bad in 01:00:5e:00:00:01 00:00:00:00:00:00 "nas;reboot" no-such-host; do
	# shellcheck disable=SC2086
	if ip netns exec "$NA" "$MR" $CFG wol "$bad" >/dev/null 2>&1; then fail "mr wol $bad accepted"; fi
done
# shellcheck disable=SC2086
if ip netns exec "$NA" "$MR" $CFG wol 02:00:00:00:00:01 office >/dev/null 2>&1; then fail "mr wol on an unknown network accepted"; fi
ip netns del "$NA"
ip netns del "$NB"
trap - EXIT
ok "wol: 3 magic packets to 192.168.1.255:9 through br-lan, none through the WAN, bad targets refused"

# 9. events and notifications with real processes (/run/mini-router is a tmpfs of this private mount
#    namespace; the webhook is a local receiver): boot records (first, same boot, clean restart), the
#    login throttle's lock event reaching the webhook through the detached `mr notify flush --hook`
#    (two locks within its 5 s wait = one message), a failing webhook (kept, backed off, event.due),
#    `mr notify test`, a hook flush after recovery; no secret in any state file or answer
mkdir -p /run/mini-router && mount -t tmpfs tmpfs /run/mini-router
E=$OUT/events
rm -rf "$E" /etc/mini-router/state && mkdir -p "$E"
python3 - "$E/hook" <<'PY' &
import http.server, json, os, sys
base = sys.argv[1]
class H(http.server.BaseHTTPRequestHandler):
    def do_POST(self):
        body = self.rfile.read(int(self.headers.get("Content-Length") or 0)).decode()
        with open(base + ".rx", "a") as f:
            f.write(json.dumps({"path": self.path, "title": self.headers.get("Title"), "body": body}) + "\n")
        self.send_response(500 if os.path.exists(base + ".fail") else 204)
        self.end_headers()
    def log_message(self, *a):
        pass
s = http.server.HTTPServer(("127.0.0.1", 0), H)
open(base + ".port", "w").write(str(s.server_port))
s.serve_forever()
PY
RXPID=$!
# shellcheck disable=SC2064
trap "kill $RXPID 2>/dev/null; umount /run/mini-router 2>/dev/null" EXIT
i=0
while [ ! -s "$E/hook.port" ] && [ $i -lt 50 ]; do sleep 0.1; i=$((i + 1)); done
HOOK="http://127.0.0.1:$(cat "$E/hook.port")/ci-hook-path-secret?token=ci-query-secret"
{ cat "$ROOT/examples/router.yaml"; printf '\nnotify:\n  channels:\n    - {name: hook, type: webhook, url_secret: ci_hook}\n  doctor_interval: 0\n'; } > /etc/mini-router/router.yaml
{ cat "$ROOT/mr/testdata/secrets.yaml"; printf 'ci_hook: "%s"\n' "$HOOK"; } > /etc/mini-router/secrets.yaml
"$MR" validate > /dev/null || fail "events: config with notify"
printf 'correct horse\n' | "$MR" passwd > /dev/null
rx() { if [ -e "$E/hook.rx" ]; then wc -l < "$E/hook.rx"; else echo 0; fi; }
settle() { # wait until no background flush runs any more
	i=0
	while pgrep -f "$MR notify flush" > /dev/null && [ $i -lt 150 ]; do sleep 0.1; i=$((i + 1)); done
	if pgrep -f "$MR notify flush" > /dev/null; then fail "a background flush did not end"; fi
}
login_lock() { # 5 wrong passwords in a row from $1 (CGI runs, like the web UI)
	body='{"password":"wrong guess"}'
	for _ in 1 2 3 4 5; do
		printf '%s' "$body" | REQUEST_METHOD=POST QUERY_STRING=a=login REMOTE_ADDR=$1 HTTP_X_MR=1 CONTENT_LENGTH=${#body} "$MR" api > /dev/null 2>&1
	done
}
L=/etc/mini-router/state/events.log
"$MR" event boot
"$MR" event boot
[ "$(grep -c '"type":"boot"' "$L")" = 1 ] || fail "events: two boot records in one boot"
"$MR" event shutdown
[ -s /etc/mini-router/state/shutdown.json ] || fail "events: no shutdown mark"
sed -i 's/"boot_id":"[^"]*"/"boot_id":"ci-previous-boot"/' /etc/mini-router/state/boot.json /etc/mini-router/state/shutdown.json
"$MR" event boot
tail -n 1 "$L" | grep -q '"msg":"booted after a clean restart"' || fail "events: clean restart: $(tail -n 1 "$L")"
settle
[ "$(rx)" = 0 ] || fail "events: a new channel got the history"
login_lock 192.0.2.77
login_lock 192.0.2.78
settle
[ "$(rx)" = 1 ] || fail "events: two locks within the debounce: $(rx) messages, want 1"
python3 - "$E/hook.rx" <<'PY' || fail "events: webhook message"
import json, sys
m = [json.loads(l) for l in open(sys.argv[1])]
b = json.loads(m[0]["body"])
assert m[0]["path"] == "/ci-hook-path-secret?token=ci-query-secret", m[0]["path"]
assert b["title"] == "mini-router: Login locked (+1)", b["title"]
assert len(b["events"]) == 2 and "192.0.2.77" in b["message"] and "192.0.2.78" in b["message"], b
assert b["severity"] == "warn" and b["host"] == "mini-router", b
PY
touch "$E/hook.fail"
login_lock 192.0.2.79
settle
[ "$(rx)" = 2 ] || fail "events: no attempt with a failing webhook"
"$MR" notify status > "$E/status.json"
python3 - "$E/status.json" /run/mini-router/event.due <<'PY' || fail "events: failed send: $(cat "$E/status.json")"
import json, sys
s = json.load(open(sys.argv[1]))[0]
assert s["name"] == "hook" and s["pending"] == 1 and s["error"] == "webhook: HTTP 500" and s["held"] == "retry", s
assert 50 <= s["retry_in"] <= 60, s
up = float(open("/proc/uptime").read().split()[0])
due = int(open(sys.argv[2]).read())
assert 50 <= due - up <= 61, (due, up)
PY
rm -f "$E/hook.fail"
"$MR" notify flush
[ "$(rx)" = 2 ] || fail "events: retried before the backoff ended"
"$MR" notify test hook | grep -q '"ok": true' || fail "events: notify test"
{ [ "$(rx)" = 3 ] && tail -n 1 "$E/hook.rx" | grep -q 'Test message'; } || fail "events: test message"
"$MR" notify flush --hook
{ [ "$(rx)" = 4 ] && tail -n 1 "$E/hook.rx" | grep -q '192.0.2.79'; } || fail "events: pending event after recovery"
"$MR" notify status | grep -q '"pending": 0' || fail "events: still pending"
"$MR" event list > "$E/list.txt"
[ "$(grep -c 'login_lock' "$E/list.txt")" = 3 ] || fail "events: mr event list: $(cat "$E/list.txt")"
"$MR" event list --json 2 | python3 -c 'import json,sys; e=json.load(sys.stdin); assert len(e)==2 and e[-1]["type"]=="login_lock", e' || fail "events: list --json"
for f in /etc/mini-router/state/* /run/mini-router/* "$E/status.json" "$E/list.txt"; do
	[ -f "$f" ] || continue
	if grep -q 'ci-hook-path-secret\|ci-query-secret' "$f"; then fail "events: the webhook URL is in $f"; fi
done
kill "$RXPID" 2> /dev/null
trap - EXIT
umount /run/mini-router
rm -rf /etc/mini-router/router.yaml /etc/mini-router/secrets.yaml /etc/mini-router/state
ok "events: boot records, lock events pushed (one message per burst), failure backed off with event.due, test, recovery, no secret"

# 10. mr doctor on this host (a real run: nothing here is a router, so the findings vary): valid JSON,
#     every check present, every finding with a known severity, problems with a fix; the text form works
mount -t tmpfs tmpfs /run/mini-router # it keeps its last result there
# shellcheck disable=SC2086
"$MR" $CFG doctor --json > "$OUT/doctor.json" || fail "mr doctor --json"
python3 - "$OUT/doctor.json" <<'PY' || fail "mr doctor: $(head -c 600 "$OUT/doctor.json")"
import json, sys
r = json.load(open(sys.argv[1]))
checks = {f["check"] for f in r["checks"]}
want = {"config", "upgrade", "pending", "wan", "routes", "dns", "dnsguard", "ipv6", "offload", "services", "wifi", "clock", "storage", "memory", "conntrack", "temp", "crash", "ssh", "certs"}
assert checks == want, checks ^ want
assert all(f["sev"] in ("ok", "warn", "risk", "skip") and f["title"] and f["detail"] for f in r["checks"]), r
assert all(f.get("fix") for f in r["checks"] if f["sev"] in ("warn", "risk")), r
assert r["risk"] == sum(f["sev"] == "risk" for f in r["checks"]) and r["warn"] == sum(f["sev"] == "warn" for f in r["checks"])
PY
# shellcheck disable=SC2086
"$MR" $CFG doctor | head -n 1 | grep -q '^mr doctor: [0-9]* risk, [0-9]* warning(s), [0-9]* ok$' || fail "mr doctor text"
if grep -q 'not-real' "$OUT/doctor.json"; then fail "mr doctor shows a secret"; fi
[ -s /run/mini-router/doctor.json ] || fail "mr doctor: no saved result"
umount /run/mini-router
ok "mr doctor: every check, JSON and text"
