#!/bin/sh
# sys module checks. Run by tools/ci.sh inside its private mount namespace (tmpfs on
# /etc/mini-router), with OUT and ROOT set and the home / lab configs rendered to $OUT/home, $OUT/lab.
#  1. /etc/localtime (TZif built from the POSIX TZ string): glibc reading the file must agree with
#     glibc interpreting the POSIX string itself, every 5 days over two years (DST edges included)
#  2. rendered service settings: home unchanged (ntpd, dropbear), lab: NTP server, LAN-only SSH on
#     the LAN-zone addresses only, tailscale port, boot order for nf_conntrack sysctls
#  3. crontab: managed block with fixed commands only (+ the DDNS check); `mr sys run` refuses anything
#     else; `mr ddns status` works offline and never shows the token
#  4. authorized_keys: managed block (login keys + an AI agent's forced `mr mcp`), and every line
#     this host already had is still there
#  5. every rendered conf.d file parses as sh and sets what the init scripts read
#  6. `mr sys backup`: archive content, secrets only on request and never the web UI password hash
#  7. sysctl, real kernel (network namespace): after the rendered file is loaded no netdev sends ICMP
#     redirects — neither one that existed before nor one created after
#  8. Wake-on-LAN, real sockets (two network namespaces): `mr wol` sends three 102-byte magic packets
#     from the router's LAN address to the LAN broadcast through br-lan; a host behind the bridge gets
#     them, a WAN-side netdev with the default route sends nothing; bad targets are refused
set -eu
: "${OUT:?}" "${ROOT:?}"
MR=$OUT/mr-host
H=$OUT/home L=$OUT/lab
fail() { echo "FAIL: $*"; exit 1; }
ok() { echo "ok: $*"; }

# 1. TZif vs glibc's own POSIX TZ parser
check_tz() { # name tzstring
	f=$OUT/$1/etc/localtime
	[ -s "$f" ] || fail "$1: no /etc/localtime"
	head -c 5 "$f" | grep -q '^TZif2' || fail "$1: /etc/localtime is not TZif v2"
	t=1767225600 # 2026-01-01
	n=0
	while [ "$n" -lt 146 ]; do
		a=$(TZ=":$f" date -d "@$t" '+%F %T %Z %z')
		b=$(TZ="$2" date -d "@$t" '+%F %T %Z %z')
		[ "$a" = "$b" ] || fail "$1 at $t: TZif says '$a', POSIX '$2' says '$b'"
		t=$((t + 5 * 86400 + 3600))
		n=$((n + 1))
	done
	ok "$1 /etc/localtime matches '$2' ($n instants)"
}
check_tz home '<+08>-8'
check_tz lab 'CET-1CEST,M3.5.0,M10.5.0/3'
[ "$(TZ=":$L/etc/localtime" date -d @1784116800 +%z)" = "+0200" ] || fail "lab: July is not CEST"
[ "$(TZ=":$L/etc/localtime" date -d @1768478400 +%z)" = "+0100" ] || fail "lab: January is not CET"

# 2. service settings
[ "$(cat "$H/etc/conf.d/ntpd")" = '# generated by mr
NTPD_OPTS="-N -S /usr/libexec/mr/clock-save -p ntp.tencent.com -p ntp1.aliyun.com -p ntp.ntsc.ac.cn -p cn.ntp.org.cn"' ] || fail "home ntpd changed: $(cat "$H/etc/conf.d/ntpd")"
[ "$(sed -n 's/^DROPBEAR_OPTS=//p' "$H/etc/conf.d/dropbear")" = '"-p 22 -K 300 -s -g"' ] || fail "home dropbear changed"
grep -q ' -l"$' "$L/etc/conf.d/ntpd" || fail "lab: ntpd not serving (-l)"
if grep -q ' -l"$' "$H/etc/conf.d/ntpd"; then fail "home: ntpd serves time without ntp_server"; fi
grep -q 'DROPBEAR_OPTS="-p 192.168.1.6:22 -p 192.168.30.1:22 -K 300 -s -g"' "$L/etc/conf.d/dropbear" || fail "lab dropbear: $(cat "$L/etc/conf.d/dropbear")"
if grep -q '192.168.20.1' "$L/etc/conf.d/dropbear"; then fail "lab: SSH listens on the guest network"; fi
grep -qx 'TS_PORT=41642' "$L/etc/conf.d/tailscale" || fail "lab: tailscale port"
grep -q 'udp dport 41642 accept comment "tailscale"' "$OUT/lab-nft.nft" || fail "lab: tailscale port not opened"
if grep -Eq '(dport|,|\{) 123( |,|$)' "$OUT/lab-nft.nft"; then fail "lab: NTP opened in the firewall"; fi
for t in home lab; do
	grep -qx 'nf_conntrack' "$OUT/$t/etc/modules-load.d/mr-sys.conf" || fail "$t: nf_conntrack not in modules-load.d"
	grep -qx 'rc_after="modules"' "$OUT/$t/etc/conf.d/sysctl" || fail "$t: sysctl not ordered after modules"
done
grep -qx 'net.netfilter.nf_conntrack_max=100000' "$H/etc/sysctl.d/90-mini-router.conf" || fail "home conntrack max"
grep -qx 'net.netfilter.nf_conntrack_max=131072' "$L/etc/sysctl.d/90-mini-router.conf" || fail "lab conntrack max override"
ok "service settings"

# 3. crontab
C=$L/etc/crontabs/root
if [ -e "$H/etc/crontabs/root" ]; then fail "home: crontab rendered without schedules"; fi
grep -qx 'crond' "$L/etc/mini-router/gen/services" || fail "lab: crond not enabled"
if grep -qx 'crond' "$H/etc/mini-router/gen/services"; then fail "home: crond enabled without schedules"; fi
grep -qx "export TZ='CET-1CEST,M3.5.0,M10.5.0/3'" "$L/etc/conf.d/crond" || fail "lab: crond zone"
block=$(sed -n '/^# --- begin mini-router schedules/,/^# --- end mini-router schedules/p' "$C" | grep -v '^#')
[ "$(echo "$block" | wc -l)" = 6 ] || fail "lab crontab: want 5 jobs + the DDNS check, got: $block"
echo "$block" | while read -r m hr d mo w cmd; do
	if [ "$cmd" = "/usr/sbin/mr ddns sync --cron" ]; then
		[ "$m $hr $d $mo $w" = "*/10 * * * *" ] || fail "DDNS check time spec: $m $hr $d $mo $w"
		continue
	fi
	echo "$m $hr $d $mo $w" | grep -Eq '^[0-9]+ [0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+$' || fail "bad time spec: $m $hr $d $mo $w"
	echo "$cmd" | grep -Eqx '/usr/sbin/mr sys run (reboot|restart [a-z0-9.-]+|reconnect [a-z0-9_-]+|wol [A-Za-z0-9:-]+)' || fail "unexpected crontab command: $cmd"
done
grep -qx '15 \*/6 \* \* \* /usr/sbin/mr sys run reconnect iptv' "$C" || fail "lab crontab: reconnect iptv"
grep -qx '0 7 \* \* 1-5 /usr/sbin/mr sys run wol 02:00:00:00:00:10' "$C" || fail "lab crontab: wol"
grep -qx '\*/10 \* \* \* \* /usr/sbin/mr ddns sync --cron' "$C" || fail "lab crontab: no DDNS check"
CFG="-c $OUT/lab.yaml -s $OUT/lab-secrets.yaml"
for bad in "restart dnsmasq;reboot" "restart mr-network" "reconnect office" "shutdown" "reboot now" "restart sshd" "wol no-such-host" "wol 01:00:5e:00:00:01"; do
	# shellcheck disable=SC2086
	if "$MR" $CFG sys run $bad >/dev/null 2>&1; then fail "mr sys run $bad accepted"; fi
done
ok "crontab + mr sys run"

# 3b. DDNS: status works offline (no lease files here: nothing to publish, no request is made) and
#     never shows the token; the home config has no DDNS
# shellcheck disable=SC2086
"$MR" $CFG ddns status > "$OUT/ddns-status.json"
python3 - "$OUT/ddns-status.json" <<'EOF' || fail "lab ddns status"
import json, sys
rows = json.load(open(sys.argv[1]))
want = [("home.example.com", "A", "active"), ("home.example.com", "AAAA", "router"), ("*.example.com", "A", "wan2"), ("nas.example.com", "AAAA", "::10")]
got = [(r["name"], r["type"], r["source"]) for r in rows]
assert got == want, got
assert all(not r.get("published") and r.get("note") for r in rows), rows
EOF
if grep -q 'lab-token' "$OUT/ddns-status.json"; then fail "ddns status shows the token"; fi
[ "$("$MR" -c "$ROOT/examples/router.yaml" -s "$ROOT/mr/testdata/secrets.yaml" ddns status | tr -d ' \n')" = "[]" ] || fail "home: ddns status not empty"
# shellcheck disable=SC2086
if "$MR" $CFG ddns update nope.example.com >/dev/null 2>&1; then fail "ddns update of an unknown record accepted"; fi
ok "ddns status"

# 4. authorized_keys: managed block + everything this host already had
K=$L/root/.ssh/authorized_keys
[ "$(stat -c %a "$K")" = 600 ] || fail "authorized_keys mode"
block=$(sed -n '/^# --- begin mini-router managed keys/,/^# --- end mini-router managed keys/p' "$K")
[ "$(echo "$block" | grep -c '^[a-z]')" = 3 ] || fail "lab: managed keys (2 logins + 1 agent)"
# the agent's key runs `mr mcp` and nothing else (services.ssh.agents, docs/mcp.md)
echo "$block" | grep -q '^command="/usr/sbin/mr mcp --scope=apply --agent=claude",no-port-forwarding,no-agent-forwarding,no-X11-forwarding,no-pty ssh-ed25519 [A-Za-z0-9+/=]* mr-agent:claude$' || fail "lab: agent key line"
[ "$(echo "$block" | grep -c '^command=')" = 1 ] || fail "lab: forced command on a login key"
if [ -r /root/.ssh/authorized_keys ]; then
	n=0
	while IFS= read -r line; do
		[ -n "$line" ] || continue
		grep -qxF -- "$line" "$K" || fail "an existing authorized_keys line was dropped"
		n=$((n + 1))
	done < /root/.ssh/authorized_keys
	ok "authorized_keys keeps this host's $n existing lines"
fi
if [ -e "$H/root/.ssh/authorized_keys" ]; then fail "home: authorized_keys rendered without managed keys"; fi
ok "authorized_keys"

# 5. conf.d files are valid sh and set what the init scripts use
for t in home lab; do
	for f in "$OUT/$t"/etc/conf.d/ntpd "$OUT/$t"/etc/conf.d/dropbear "$OUT/$t"/etc/conf.d/tailscale "$OUT/$t"/etc/conf.d/mr-panel "$OUT/$t"/etc/conf.d/sysctl "$OUT/$t"/etc/conf.d/crond; do
		[ -e "$f" ] || continue
		sh -n "$f" || fail "$f: sh syntax"
	done
done
# shellcheck disable=SC1091
v=$(. "$L/etc/conf.d/mr-panel"; echo "$PANEL_ADDR")
[ "$v" = 192.168.1.6 ] || fail "PANEL_ADDR=$v"
# shellcheck disable=SC1091
v=$(. "$L/etc/conf.d/crond"; echo "$CRON_OPTS|$TZ")
[ "$v" = "-c /etc/crontabs|CET-1CEST,M3.5.0,M10.5.0/3" ] || fail "crond conf: $v"
ok "conf.d files"

# 6. backup (reads the live paths; /etc/mini-router is the CI tmpfs)
mkdir -p /etc/mini-router/dns /etc/mini-router/proxy
cp "$OUT/lab.yaml" /etc/mini-router/router.yaml
{ cat "$OUT/lab-secrets.yaml"; echo 'webui_password: "pbkdf2-sha256$120000$00$11"'; } > /etc/mini-router/secrets.yaml
echo "ci.example" > /etc/mini-router/proxy/ci.domains
ln -sf /etc/shadow /etc/mini-router/proxy/leak.domains
B=$OUT/sys-backup
rm -rf "$B" && mkdir -p "$B"
"$MR" sys backup "$B/plain.tgz" 2>/dev/null
"$MR" sys backup -secrets "$B/full.tgz" 2>/dev/null
tar tzf "$B/plain.tgz" | sort > "$B/plain.list"
grep -qx 'etc/mini-router/router.yaml' "$B/plain.list" || fail "backup: no router.yaml"
grep -qx 'etc/mini-router/proxy/ci.domains' "$B/plain.list" || fail "backup: no proxy list"
grep -qx 'etc/mini-router/dns/cloudflare-dot.domains' "$B/plain.list" || fail "backup: no dns list"
if grep -q 'secrets.yaml\|leak.domains' "$B/plain.list"; then fail "plain backup has secrets or followed a symlink"; fi
tar xzf "$B/full.tgz" -C "$B" etc/mini-router/secrets.yaml
grep -q '^pppoe_password:' "$B/etc/mini-router/secrets.yaml" || fail "backup -secrets: no secrets"
if grep -q webui_password "$B/etc/mini-router/secrets.yaml"; then fail "backup contains the web UI password hash"; fi
rm -f /etc/mini-router/proxy/leak.domains
ok "backup"

# 7. ICMP redirects off everywhere: the kernel sends one when conf.all OR conf.<dev> is set. Writing
#    conf.default copies the value to every netdev whose own value was never written (the boot run:
#    nothing else sets send_redirects); a netdev created later starts from default. (One created after
#    an earlier write to default also inherits the "written" flag and misses later changes of default.)
NS=mrcisys$$
ip netns add "$NS"
# shellcheck disable=SC2064
trap "ip netns del $NS 2>/dev/null" EXIT
ip -n "$NS" link add early type dummy
grep '^net\.ipv4\.conf\.' "$H/etc/sysctl.d/90-mini-router.conf" > "$OUT/sys-netns.conf"
ip netns exec "$NS" sysctl -q -p "$OUT/sys-netns.conf"
ip -n "$NS" link add late type dummy
for d in all default early late; do
	v=$(ip netns exec "$NS" cat "/proc/sys/net/ipv4/conf/$d/send_redirects")
	[ "$v" = 0 ] || fail "send_redirects on $d is $v after loading the rendered sysctl file"
done
ip netns del "$NS"
trap - EXIT
ok "no ICMP redirects on netdevs created before or after the sysctl file"

# 8. Wake-on-LAN through br-lan (lab LAN 192.168.1.6/24) to a receiver in another namespace
NA=mrciwola$$ NB=mrciwolb$$
ip netns add "$NA"
ip netns add "$NB"
# shellcheck disable=SC2064
trap "ip netns del $NA 2>/dev/null; ip netns del $NB 2>/dev/null" EXIT
ip -n "$NA" link set lo up
ip -n "$NA" link add br-lan type bridge
ip -n "$NA" link add wol0 type veth peer name wol1 netns "$NB"
ip -n "$NA" link set wol0 master br-lan
ip -n "$NA" link set wol0 up
ip -n "$NA" addr add 192.168.1.6/24 dev br-lan
ip -n "$NA" link set br-lan up
ip -n "$NA" link add wan0 type dummy
ip -n "$NA" addr add 10.99.0.2/24 dev wan0
ip -n "$NA" link set wan0 up
ip -n "$NA" route add default via 10.99.0.1 dev wan0
ip -n "$NB" addr add 192.168.1.50/24 dev wol1
ip -n "$NB" link set wol1 up
rm -f "$OUT/wol.ready" "$OUT/wol.rx"
ip netns exec "$NB" python3 - "$OUT/wol" <<'EOF' &
import socket, sys
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind(("", 9))
s.settimeout(5)
open(sys.argv[1] + ".ready", "w").close()
got = []
try:
    while len(got) < 3:
        d, a = s.recvfrom(512)
        got.append("%s %s" % (d.hex(), a[0]))
except socket.timeout:
    pass
open(sys.argv[1] + ".rx", "w").write("".join(g + "\n" for g in got))
EOF
RX=$!
i=0
while [ ! -e "$OUT/wol.ready" ] && [ $i -lt 50 ]; do sleep 0.1; i=$((i + 1)); done
tx0=$(ip netns exec "$NA" cat /sys/class/net/wan0/statistics/tx_packets)
# shellcheck disable=SC2086
ip netns exec "$NA" "$MR" $CFG wol 02:00:00:00:00:01 > "$OUT/wol.json" || fail "mr wol"
wait "$RX" || true
want="ffffffffffff$(printf '020000000001%.0s' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16) 192.168.1.6"
[ "$(grep -c . "$OUT/wol.rx")" = 3 ] || fail "wol: want 3 packets, got: $(cat "$OUT/wol.rx")"
while read -r line; do [ "$line" = "$want" ] || fail "wol packet: $line"; done < "$OUT/wol.rx"
grep -q '"broadcast":"192.168.1.255"' "$OUT/wol.json" || fail "wol answer: $(cat "$OUT/wol.json")"
[ "$(ip netns exec "$NA" cat /sys/class/net/wan0/statistics/tx_packets)" = "$tx0" ] || fail "wol: packets left through the WAN"
for bad in 01:00:5e:00:00:01 00:00:00:00:00:00 "nas;reboot" no-such-host; do
	# shellcheck disable=SC2086
	if ip netns exec "$NA" "$MR" $CFG wol "$bad" >/dev/null 2>&1; then fail "mr wol $bad accepted"; fi
done
# shellcheck disable=SC2086
if ip netns exec "$NA" "$MR" $CFG wol 02:00:00:00:00:01 office >/dev/null 2>&1; then fail "mr wol on an unknown network accepted"; fi
ip netns del "$NA"
ip netns del "$NB"
trap - EXIT
ok "wol: 3 magic packets to 192.168.1.255:9 through br-lan, none through the WAN, bad targets refused"
