package main

// Change history (Cd1s/mini-router#12, part 1): what a change does in config terms, and a record of
// every apply.
//
//   - Semantic diff: the config last applied is kept as gen/applied.yaml (canonical) and
//     gen/applied-secrets (sha256 per secret, 0600) — bookkeeping files written by every apply,
//     restored by every rollback. `mr plan` / the web UI show "~ path: old → new", "+ path",
//     "- path" (list items by name), secrets only as "(changed)". `mr plan -v` adds the generated
//     files' diffs with every secret value masked.
//   - Revisions: every apply's snapshot gets a sidecar <snapshot>.json — rev, time, origin, comment,
//     mr version, the semantic diff and the result (applying → applied | pending → confirmed, or
//     rolled back: why). `mr history`, the web UI's history page.
//   - `mr rollback N` puts the config from before change N back through the normal path —
//     validate, plan, apply --confirm — as a new revision; the web UI password stays the current.

import (
	"archive/tar"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

var (
	appliedYAML    = GenDir + "/applied.yaml"
	appliedSecrets = GenDir + "/applied-secrets"
)

const defaultHistory = 20

// applyOpts: who applies, and why.
type applyOpts struct {
	Via     string // mr apply | web UI | restore | rollback
	From    string // web UI: the client's address
	Comment string
	// BaseRev: the router.yaml rev the candidate was built from (web UI / API). The apply refuses when
	// the live file differs by the time it installs (Cd1s/mini-router#68).
	BaseRev string
}

// bookkeeping reports files that record state for mr itself (not shown in plans).
func bookkeeping(path string) bool { return path == appliedYAML || path == appliedSecrets }

// appliedFiles: the record of c as applied.
func appliedFiles(c *Config) []File {
	y, _ := yaml.Marshal(c)
	var b strings.Builder
	b.WriteString("# secrets as last applied (sha256), for `mr plan` — generated by mr\n")
	for _, k := range sortedKeys(c.secrets) {
		if k == pwSecretKey {
			continue
		}
		fmt.Fprintf(&b, "%s %s\n", k, secretHash(c.secrets[k]))
	}
	return []File{
		{appliedYAML, 0644, "# the config as last applied (canonical form), for `mr plan` — generated by mr\n" + string(y)},
		{appliedSecrets, 0600, b.String()},
	}
}

func secretHash(v string) string { s := sha256.Sum256([]byte(v)); return hex.EncodeToString(s[:]) }

func sortedKeys(m map[string]string) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

// changesSinceApplied is the semantic diff from the config last applied to c; nil, false when there
// is no record yet (the first apply writes it).
func changesSinceApplied(c *Config) ([]string, bool) {
	b, err := os.ReadFile(appliedYAML)
	if err != nil {
		return nil, false
	}
	var d yaml.Node
	if yaml.Unmarshal(b, &d) != nil || len(d.Content) == 0 {
		return nil, false
	}
	cn, err := canonNode(c)
	if err != nil {
		return nil, false
	}
	out := configChanges(d.Content[0], cn)
	old := map[string]string{}
	if b, err := os.ReadFile(appliedSecrets); err == nil {
		for _, l := range strings.Split(string(b), "\n") {
			if k, h, ok := strings.Cut(l, " "); ok && !strings.HasPrefix(l, "#") {
				old[k] = h
			}
		}
	}
	return append(out, secretChanges(old, c.secrets)...), true
}

// secretChanges: which secrets were added, removed or changed — never their values.
func secretChanges(oldHash, cur map[string]string) []string {
	var out []string
	for _, k := range sortedKeys(cur) {
		if k == pwSecretKey {
			continue
		}
		switch h, ok := oldHash[k]; {
		case !ok:
			out = append(out, "+ secrets."+k)
		case h != secretHash(cur[k]):
			out = append(out, "~ secrets."+k+": (changed)")
		}
	}
	for _, k := range sortedKeys(oldHash) {
		if _, ok := cur[k]; !ok {
			out = append(out, "- secrets."+k)
		}
	}
	return out
}

// configChanges lists what changes from a to b (canonical trees of Config).
func configChanges(a, b *yaml.Node) []string {
	var out []string
	diffNode("", a, b, &out)
	return out
}

func joinPath(p, k string) string {
	if p == "" {
		return k
	}
	return p + "." + k
}

func diffNode(path string, a, b *yaml.Node, out *[]string) {
	switch {
	case a == nil && b == nil, a != nil && b != nil && nodeEqual(a, b):
	case a == nil && b.Kind == yaml.ScalarNode:
		*out = append(*out, "~ "+path+": (default) → "+short(b))
	case b == nil && a.Kind == yaml.ScalarNode:
		*out = append(*out, "~ "+path+": "+short(a)+" → (default)")
	case a == nil:
		*out = append(*out, "+ "+path)
	case b == nil:
		*out = append(*out, "- "+path)
	case a.Kind == yaml.MappingNode && b.Kind == yaml.MappingNode:
		am, bm := mapIndex(a), mapIndex(b)
		for i := 0; i+1 < len(b.Content); i += 2 {
			k := b.Content[i].Value
			diffNode(joinPath(path, k), am[k], b.Content[i+1], out)
		}
		for i := 0; i+1 < len(a.Content); i += 2 {
			if k := a.Content[i].Value; bm[k] == nil {
				diffNode(joinPath(path, k), a.Content[i+1], nil, out)
			}
		}
	case a.Kind == yaml.SequenceNode && b.Kind == yaml.SequenceNode:
		if isInline(a) && isInline(b) {
			*out = append(*out, "~ "+path+": "+short(a)+" → "+short(b))
			return
		}
		if id := listID(a, b); id != "" {
			ai := map[string]*yaml.Node{}
			for _, it := range a.Content {
				ai[mapIndex(it)[id].Value] = it
			}
			seen := map[string]bool{}
			var ao, bo []string
			for _, it := range b.Content {
				nm := mapIndex(it)[id].Value
				seen[nm] = true
				bo = append(bo, nm)
				diffNode(path+"["+nm+"]", ai[nm], it, out)
			}
			for _, it := range a.Content {
				nm := mapIndex(it)[id].Value
				if seen[nm] {
					ao = append(ao, nm)
				} else {
					diffNode(path+"["+nm+"]", it, nil, out)
				}
			}
			if strings.Join(ao, "\x00") != strings.Join(keep(bo, ao), "\x00") {
				*out = append(*out, "~ "+path+": order "+strings.Join(ao, ", ")+" → "+strings.Join(keep(bo, ao), ", "))
			}
			return
		}
		for i := 0; i < len(a.Content) || i < len(b.Content); i++ {
			var x, y *yaml.Node
			if i < len(a.Content) {
				x = a.Content[i]
			}
			if i < len(b.Content) {
				y = b.Content[i]
			}
			diffNode(path+"["+strconv.Itoa(i)+"]", x, y, out)
		}
	default:
		*out = append(*out, "~ "+path+": "+short(a)+" → "+short(b))
	}
}

// keep: the elements of xs that are also in ys, in xs's order.
func keep(xs, ys []string) []string {
	in := map[string]bool{}
	for _, y := range ys {
		in[y] = true
	}
	var out []string
	for _, x := range xs {
		if in[x] {
			out = append(out, x)
		}
	}
	return out
}

// listID: the key that identifies the items of both lists (unique scalar in every item), if any.
func listID(a, b *yaml.Node) string {
	for _, k := range []string{"name", "phy", "ssid", "mac"} {
		ok := true
		for _, l := range []*yaml.Node{a, b} {
			seen := map[string]bool{}
			for _, it := range l.Content {
				v := mapIndex(it)[k]
				if v == nil || v.Kind != yaml.ScalarNode || seen[v.Value] {
					ok = false
					break
				}
				seen[v.Value] = true
			}
		}
		if ok {
			return k
		}
	}
	return ""
}

// short: a value on one line, cut at 60 characters.
func short(n *yaml.Node) string {
	s := renderFlow(n)
	if r := []rune(s); len(r) > 60 {
		s = string(r[:57]) + "..."
	}
	return s
}

// ---- revisions ----

type revision struct {
	Rev      int      `json:"rev"`
	Time     int64    `json:"time"`
	Via      string   `json:"via"`
	From     string   `json:"from,omitempty"`
	Comment  string   `json:"comment,omitempty"`
	Version  string   `json:"version"`
	Result   string   `json:"result"`
	Changes  []string `json:"changes"`
	Snapshot string   `json:"snapshot"` // the state before the change (history file name)
}

func revFile(snap string) string { return strings.TrimSuffix(snap, ".tar.gz") + ".json" }

func readRevisions() []revision {
	ents, _ := os.ReadDir(HistoryDir)
	var out []revision
	for _, e := range ents {
		if !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		var r revision
		if b, err := os.ReadFile(filepath.Join(HistoryDir, e.Name())); err == nil && json.Unmarshal(b, &r) == nil && r.Rev > 0 {
			out = append(out, r)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Rev < out[j].Rev })
	return out
}

// newRevision records the change about to be applied on top of snapshot snap.
func newRevision(snap string, o applyOpts, changes []string) {
	rev := 1
	if rs := readRevisions(); len(rs) > 0 {
		rev = rs[len(rs)-1].Rev + 1
	}
	if changes == nil {
		changes = []string{}
	}
	writeRevision(revision{Rev: rev, Time: time.Now().Unix(), Via: o.Via, From: o.From, Comment: o.Comment,
		Version: version, Result: "applying", Changes: changes, Snapshot: filepath.Base(snap)})
}

func writeRevision(r revision) {
	b, _ := json.MarshalIndent(r, "", " ")
	writeAtomic(filepath.Join(HistoryDir, revFile(r.Snapshot)), append(b, '\n'), 0600)
}

// setResult records how the change applied on top of snapshot snap ended.
func setResult(snap, result string) {
	p := filepath.Join(HistoryDir, revFile(filepath.Base(snap)))
	var r revision
	if b, err := os.ReadFile(p); err != nil || json.Unmarshal(b, &r) != nil {
		return
	}
	r.Result = result
	writeRevision(r)
	eventChange(r) // the event log: applied / confirmed / rolled back (mod_sys_event.go)
}

func historyKeep(c *Config) int {
	if c != nil && c.System.History > 0 {
		return c.System.History
	}
	return defaultHistory
}

// historyCommand prints the revisions, newest first (JSON with --json).
func historyCommand(args []string) error {
	rs := readRevisions()
	if len(args) > 0 && args[0] == "--json" {
		for i, j := 0, len(rs)-1; i < j; i, j = i+1, j-1 {
			rs[i], rs[j] = rs[j], rs[i]
		}
		return json.NewEncoder(os.Stdout).Encode(map[string]any{"revisions": rs})
	}
	if len(rs) == 0 {
		fmt.Println("no revisions yet")
	}
	for i := len(rs) - 1; i >= 0; i-- {
		r := rs[i]
		who := r.Via
		if r.From != "" {
			who += "@" + r.From
		}
		fmt.Printf("#%d  %s  %s  %s", r.Rev, time.Unix(r.Time, 0).Format("2006-01-02 15:04"), who, r.Result)
		if r.Comment != "" {
			fmt.Printf("  %q", r.Comment)
		}
		fmt.Println()
		for _, l := range r.Changes {
			fmt.Println("    " + l)
		}
	}
	return nil
}

// snapshotFile reads one file out of a history snapshot ("" and false when it has none).
func snapshotFile(snap, path string) ([]byte, bool, error) {
	f, err := os.Open(snap)
	if err != nil {
		return nil, false, err
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		return nil, false, err
	}
	tr := tar.NewReader(gz)
	for {
		h, err := tr.Next()
		if err == io.EOF {
			return nil, false, nil
		}
		if err != nil {
			return nil, false, err
		}
		if "/"+h.Name == path {
			b, err := io.ReadAll(io.LimitReader(tr, 4<<20))
			return b, true, err
		}
	}
}

// revSnapshot: the snapshot taken before change rev.
func revSnapshot(rev int) (string, error) {
	for _, r := range readRevisions() {
		if r.Rev == rev {
			return filepath.Join(HistoryDir, r.Snapshot), nil
		}
	}
	return "", fmt.Errorf("no revision #%d (see mr history)", rev)
}

// stageRollback writes the config from before change rev as the apply candidate (CandidateYAML,
// CandidateSec); the web UI password stays the current one.
func stageRollback(rev int) error {
	snap, err := revSnapshot(rev)
	if err != nil {
		return err
	}
	return stageSnapshot(snap)
}

// stageSnapshot: the config saved in history snapshot snap as the apply candidate.
func stageSnapshot(snap string) error {
	y, ok, err := snapshotFile(snap, ConfigPath)
	if err != nil || !ok {
		return fmt.Errorf("%s: no router.yaml in this snapshot", filepath.Base(snap))
	}
	sec := map[string]string{}
	if s, ok, _ := snapshotFile(snap, SecretsPath); ok {
		yaml.Unmarshal(s, &sec)
	}
	cur := readSecretsFile(sysSecretsPath)
	if pw, ok := cur[pwSecretKey]; ok {
		sec[pwSecretKey] = pw
	} else {
		delete(sec, pwSecretKey)
	}
	if err := os.MkdirAll(filepath.Dir(CandidateYAML), 0700); err != nil {
		return err
	}
	if err := writeAtomic(CandidateYAML, y, 0600); err != nil {
		return err
	}
	return writeSecrets(CandidateSec, sec)
}

func readSecretsFile(p string) map[string]string {
	m := map[string]string{}
	if b, err := os.ReadFile(p); err == nil {
		yaml.Unmarshal(b, &m)
	}
	return m
}

// rollbackToRev is `mr rollback N`: the config from before change N, applied like any change.
func rollbackToRev(rev, confirmSecs int) error {
	if err := pendingBlocks(); err != nil {
		return err
	}
	if err := stageRollback(rev); err != nil {
		return err
	}
	err := ApplyCandidate(CandidateYAML, CandidateSec, confirmSecs, applyOpts{Via: "rollback", Comment: fmt.Sprintf("back to before #%d", rev)})
	if err == nil && confirmSecs > 0 {
		fmt.Printf("run `mr confirm` within %ds or the rollback itself is rolled back\n", confirmSecs)
	}
	return err
}

// snapshotChanges: the semantic diff from the config saved in snap to the live router.yaml.
func snapshotChanges(snap string) ([]string, error) {
	y, ok, err := snapshotFile(snap, ConfigPath)
	if err != nil || !ok {
		return nil, fmt.Errorf("%s: no router.yaml in this snapshot", filepath.Base(snap))
	}
	old, err := decodeConfig(y)
	if err != nil {
		return nil, err
	}
	cur, err := loadConfig(ConfigPath, SecretsPath)
	if err != nil {
		return nil, err
	}
	old.secrets = cur.secrets
	old.defaults()
	a, err := canonNode(old)
	if err != nil {
		return nil, err
	}
	b, err := canonNode(cur)
	if err != nil {
		return nil, err
	}
	return configChanges(a, b), nil
}

// ---- file diffs for `mr plan -v` ----

// fileDiff: a unified-style diff of one generated file, every secret value masked.
func fileDiff(path, old, new string, secrets map[string]string) string {
	for _, k := range sortedKeys(secrets) {
		if v := secrets[k]; len(v) >= 4 {
			old, new = strings.ReplaceAll(old, v, "******"), strings.ReplaceAll(new, v, "******")
		}
	}
	if old == new {
		return ""
	}
	a, b := strings.SplitAfter(old, "\n"), strings.SplitAfter(new, "\n")
	i := 0
	for i < len(a) && i < len(b) && a[i] == b[i] {
		i++
	}
	j := 0
	for j < len(a)-i && j < len(b)-i && a[len(a)-1-j] == b[len(b)-1-j] {
		j++
	}
	var out strings.Builder
	fmt.Fprintf(&out, "--- %s\n+++ %s\n@@ -%d +%d @@\n", path, path, i+1, i+1)
	from := i - 3
	if from < 0 {
		from = 0
	}
	for _, l := range a[from:i] {
		out.WriteString(" " + nl(l))
	}
	for _, op := range lineOps(a[i:len(a)-j], b[i:len(b)-j]) {
		out.WriteString(op)
	}
	for k, l := range a[len(a)-j:] {
		if k == 3 || l == "" {
			break
		}
		out.WriteString(" " + nl(l))
	}
	return out.String()
}

func nl(l string) string {
	if strings.HasSuffix(l, "\n") {
		return l
	}
	return l + "\n"
}

// lineOps: the middle of a diff as -/+/space lines (LCS when small, else all of a then all of b).
func lineOps(a, b []string) []string {
	var out []string
	if len(a)*len(b) > 250000 {
		for _, l := range a {
			out = append(out, "-"+nl(l))
		}
		for _, l := range b {
			out = append(out, "+"+nl(l))
		}
		return out
	}
	n, m := len(a), len(b)
	L := make([][]int32, n+1)
	for i := range L {
		L[i] = make([]int32, m+1)
	}
	for i := n - 1; i >= 0; i-- {
		for j := m - 1; j >= 0; j-- {
			if a[i] == b[j] {
				L[i][j] = L[i+1][j+1] + 1
			} else if L[i+1][j] >= L[i][j+1] {
				L[i][j] = L[i+1][j]
			} else {
				L[i][j] = L[i][j+1]
			}
		}
	}
	i, j := 0, 0
	for i < n || j < m {
		switch {
		case i < n && j < m && a[i] == b[j]:
			out = append(out, " "+nl(a[i]))
			i, j = i+1, j+1
		case j < m && (i == n || L[i][j+1] >= L[i+1][j]):
			out = append(out, "+"+nl(b[j]))
			j++
		default:
			out = append(out, "-"+nl(a[i]))
			i++
		}
	}
	return out
}
