package main

// dns module: parental control (dns.parental, #33) — DNS filtering for chosen devices.
//
// A third dnsmasq (mr-parental-dns, port 5356, no DHCP) answers every DNS query (udp/tcp 53, to any
// server) of the devices in dns.parental.devices: nftables redirects them in a nat chain ahead of the
// proxy's and dns.redirect's. It forwards to the main dnsmasq (or to mr-proxy-dns while the proxy is on,
// so proxied domains keep working) and adds, for these devices only:
//   - safe_search: the search engines' safe-search addresses (Google, YouTube strict, Bing strict,
//     DuckDuckGo safe) for their search host names (address=, so AAAA gets no answer and IPv6 cannot
//     bypass it). The addresses are the providers' published safe-search hosts, fixed in mr.
//   - block: domains (and their subdomains) answered NXDOMAIN.
//
// It only covers DNS the router sees: DNS-over-HTTPS in browsers / apps, DoT, a VPN or hard-coded
// resolvers on other ports bypass it (dns.sovereignty blocks the known DoH / DoT endpoints for every
// device), and a device with a new MAC (private address) is not in the list.

import (
	"fmt"
	"strings"
)

// Parental is dns.parental.
type Parental struct {
	Devices    []string `yaml:"devices,omitempty"`     // device names / group:NAME
	SafeSearch bool     `yaml:"safe_search,omitempty"` // force safe search
	Block      []string `yaml:"block,omitempty"`       // blocked domains (with subdomains)
}

const (
	parentalPort = 5356
	parentalConf = GenDir + "/parental-dns.conf"
	parentalMax  = 512
)

var parentalSafe = []string{
	"address=/www.google.com/216.239.38.120",           // forcesafesearch.google.com
	"address=/www.youtube.com/216.239.38.120",          // restrict.youtube.com
	"address=/m.youtube.com/216.239.38.120",            //
	"address=/youtubei.googleapis.com/216.239.38.120",  //
	"address=/youtube.googleapis.com/216.239.38.120",   //
	"address=/www.youtube-nocookie.com/216.239.38.120", //
	"address=/www.bing.com/204.79.197.220",             // strict.bing.com
	"address=/duckduckgo.com/20.43.161.151",            // safe.duckduckgo.com
}

func parentalOn(c *Config) bool {
	p := c.DNS.Parental
	return len(devMACs(c, p.Devices)) > 0 && (p.SafeSearch || len(p.Block) > 0) && len(c.LANBridges()) > 0
}

func parentalValidate(c *Config, v *Validator) {
	p := c.DNS.Parental
	devCheckRefs(c, v, "dns.parental.devices", p.Devices)
	if len(p.Block) > parentalMax {
		v.Add("dns.parental.block: at most %d domains", parentalMax)
	}
	for _, d := range p.Block {
		if !reDomain.MatchString(d) {
			v.Add("dns.parental.block: invalid domain %q", d)
		}
	}
	if !c.Proxy.Enabled {
		return
	}
	bypass := map[string]bool{}
	for _, d := range c.Proxy.Bypass {
		for _, m := range proxyBypassMACs(c, d) {
			bypass[m] = true
		}
	}
	for _, m := range devMACs(c, p.Devices) {
		if bypass[m] {
			v.Add("dns.parental.devices: %s is also in proxy.bypass (its DNS would come from the proxy)", m)
		}
	}
}

func parentalRender(c *Config, out *Out) {
	if !parentalOn(c) {
		return
	}
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	w("# generated by mr (dns.parental) — DNS for the parental-control devices; edit router.yaml instead")
	w("port=%d", parentalPort)
	for _, br := range c.LANBridges() {
		w("interface=%s\nno-dhcp-interface=%s", br, br)
	}
	up := "127.0.0.1#53"
	if c.Proxy.Enabled {
		up = fmt.Sprintf("127.0.0.1#%d", c.Proxy.lanDNSPort())
	}
	w("bind-dynamic\nno-resolv\nno-hosts\ncache-size=1000\nserver=%s", up)
	if c.DNS.Parental.SafeSearch {
		b.WriteString(strings.Join(parentalSafe, "\n") + "\n")
	}
	for _, d := range c.DNS.Parental.Block {
		w("local=/%s/", strings.ToLower(d))
	}
	out.Add(parentalConf, 0644, b.String())
}

// parentalNft (defs): its own nat chain, ahead of the proxy's (dstnat - 5) and dns.redirect (dstnat).
func parentalNft(c *Config, n *Nft) {
	if !parentalOn(c) {
		return
	}
	n.W("chain parental_dns {\n\t\ttype nat hook prerouting priority dstnat - 10; policy accept;")
	n.W("\tiifname { %s } ether saddr %s meta l4proto { tcp, udp } th dport 53 redirect to :%d comment \"parental-dns\"",
		quoteList(c.LANBridges()), nftSet(devMACs(c, c.DNS.Parental.Devices)), parentalPort)
	n.W("}")
}
