package main

import (
	"encoding/binary"
	"encoding/json"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func dnsFiles(t *testing.T, c *Config) map[string]string {
	t.Helper()
	if errs := c.Validate(); len(errs) > 0 {
		t.Fatalf("config invalid:\n%s", strings.Join(errs, "\n"))
	}
	files, err := Render(c)
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]string{}
	for _, f := range files {
		got[f.Path] = f.Data
	}
	return got
}

func wantErrs(t *testing.T, c *Config, subs ...string) {
	t.Helper()
	errs := strings.Join(c.Validate(), "\n")
	for _, s := range subs {
		if !strings.Contains(errs, s) {
			t.Errorf("want error containing %q, got:\n%s", s, errs)
		}
	}
}

// The real home config must render exactly what it rendered before the dns module grew
// records / upstream modes / DHCP options / RA modes (only other modules' lines may follow), plus the
// Firefox DoH canary, on by default since #45.
func TestDNSHomeDnsmasqUnchanged(t *testing.T) {
	c := testConfig(t)
	want := `# generated by mr — edit router.yaml instead
interface=br-lan
bind-dynamic
listen-address=127.0.0.1
domain-needed
localise-queries
expand-hosts
dhcp-authoritative
quiet-ra
local=/lan/
domain=lan
stop-dns-rebind
rebind-localhost-ok
local-service
cache-size=8000
min-cache-ttl=3600
use-stale-cache=3600
no-negcache
edns-packet-max=1232
resolv-file=/run/ppp/resolv.conf
resolv-file=/run/mini-router/resolv.conf
servers-file=` + GenDir + `/dns-split.servers
local=/use-application-dns.net/
dhcp-leasefile=/tmp/dhcp.leases
dhcp-range=set:lan,192.168.1.100,192.168.1.249,255.255.255.0,12h
dhcp-option=tag:lan,option:router,192.168.1.6
dhcp-option=tag:lan,option:dns-server,192.168.1.6
dhcp-range=::,constructor:br-lan,ra-only,45m
ra-param=br-lan,60,1800
dhcp-host=02:98:67:90:62:47,192.168.1.166,nas
dhcp-host=02:bb:dd:96:49:e2,192.168.1.241,server
dhcp-host=02:9a:41:9d:fa:91,192.168.1.237,workstation
dhcp-host=02:c3:06:d6:7f:8a,192.168.1.66,desktop
enable-ra
`
	for _, l := range dnsmasqExtra(c) {
		want += l + "\n"
	}
	got := dnsFiles(t, c)
	if got["/etc/dnsmasq.conf"] != want {
		t.Errorf("home dnsmasq.conf changed:\n--- got\n%s\n--- want\n%s", got["/etc/dnsmasq.conf"], want)
	}
	// stubby is enabled at home and dns.split points at it: its config is now rendered (Alpine's
	// default stubby.yml listens on 127.0.0.1:53, which is dnsmasq's port)
	st := got[StubbyConf]
	for _, s := range []string{"listen_addresses:\n  - 127.0.0.1@5453\n", "address_data: 1.1.1.1\n    tls_auth_name: \"cloudflare-dns.com\"", "GETDNS_AUTHENTICATION_REQUIRED"} {
		if !strings.Contains(st, s) {
			t.Errorf("stubby.yml missing %q:\n%s", s, st)
		}
	}
	if serviceFor(StubbyConf) != "stubby" || serviceFor("/etc/dnsmasq.conf") != "dnsmasq" {
		t.Error("restart mapping")
	}
	if rank("stubby") > rank("dnsmasq") {
		t.Error("stubby must restart before dnsmasq")
	}
}

func TestStubbyYAMLParses(t *testing.T) {
	c := testConfig(t)
	c.DNS.DoT = DoT{Port: 5300, Servers: []DoTServer{{Address: "2606:4700:4700::1111", Name: "one.one.one.one"}, {Address: "9.9.9.9", Name: "dns.quad9.net", Port: 8853}}}
	var y struct {
		Listen  []string `yaml:"listen_addresses"`
		Servers []struct {
			Addr string `yaml:"address_data"`
			Name string `yaml:"tls_auth_name"`
			Port int    `yaml:"tls_port"`
		} `yaml:"upstream_recursive_servers"`
	}
	if err := yaml.Unmarshal([]byte(renderStubby(c)), &y); err != nil {
		t.Fatal(err)
	}
	if len(y.Listen) != 1 || y.Listen[0] != "127.0.0.1@5300" || len(y.Servers) != 2 || y.Servers[0].Addr != "2606:4700:4700::1111" ||
		y.Servers[1].Name != "dns.quad9.net" || y.Servers[1].Port != 8853 || y.Servers[0].Port != 0 {
		t.Fatalf("stubby.yml: %+v", y)
	}
	c.Services.Stubby.Enabled = false
	c.DNS.Split = nil
	if _, ok := dnsFiles(t, c)[StubbyConf]; ok {
		t.Error("stubby.yml rendered with stubby disabled")
	}
}

func TestDNSRecords(t *testing.T) {
	c := testConfig(t)
	c.DNS.Records = []Record{
		{"nas", "A", "192.168.1.10"},
		{"nas.lan", "AAAA", "fd00::10"},
		{"*.home.example.com", "A", "192.168.1.6"},
		{"*.home.example.com", "AAAA", "2001:db8::6"},
		{"photos.lan", "CNAME", "nas.lan"},
		{"192.168.1.11", "PTR", "printer.lan"},
		{"2001:db8::1", "PTR", "gw.lan"},
		{"_smb._tcp.lan", "SRV", "nas.lan:445"},
		{"_http._tcp.lan", "SRV", "nas.lan:8080:10:5"},
		{"nas.lan", "TXT", "home server; v=1, #tag"},
	}
	conf := dnsFiles(t, c)["/etc/dnsmasq.conf"]
	for _, s := range []string{
		"host-record=nas,nas.lan,192.168.1.10\n",
		"host-record=nas.lan,fd00::10\n",
		"address=/home.example.com/192.168.1.6\n",
		"address=/home.example.com/2001:db8::6\n",
		"cname=photos.lan,nas.lan\n",
		"ptr-record=11.1.168.192.in-addr.arpa,printer.lan\n",
		"ptr-record=1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa,gw.lan\n",
		"srv-host=_smb._tcp.lan,nas.lan,445,0,0\n",
		"srv-host=_http._tcp.lan,nas.lan,8080,10,5\n",
		"txt-record=nas.lan,\"home server; v=1, #tag\"\n",
	} {
		if !strings.Contains(conf, s) {
			t.Errorf("dnsmasq.conf missing %q", s)
		}
	}
	// records come before DHCP so dnsmasq.conf stays grouped
	if strings.Index(conf, "host-record=") > strings.Index(conf, "dhcp-leasefile=") {
		t.Error("records after DHCP section")
	}

	bad := []Record{
		{"a\nserver=/x/1.2.3.4", "A", "1.2.3.4"},
		{"a.lan", "A", "1.2.3.4\nlog-queries"},
		{"a.lan", "A", "fd00::1"},
		{"a.lan", "AAAA", "10.0.0.1"},
		{"a,b.lan", "A", "10.0.0.1"},
		{"a/b", "A", "10.0.0.1"},
		{"*.lan*", "A", "10.0.0.1"},
		{"x.lan", "CNAME", "x.lan"},
		{"*.x.lan", "CNAME", "y.lan"},
		{"host.lan", "PTR", "y.lan"},
		{"smb.lan", "SRV", "nas.lan:445"},
		{"_smb._tcp.lan", "SRV", "nas.lan"},
		{"_smb._tcp.lan", "SRV", "nas.lan:0"},
		{"_smb._tcp.lan", "SRV", "nas.lan,1:445"},
		{"t.lan", "TXT", `a"b`},
		{"t.lan", "TXT", `a\b`},
		{"t.lan", "TXT", "a\nb"},
		{"t.lan", "TXT", strings.Repeat("x", 256)},
		{"m.lan", "MX", "10 mail.lan"},
		{"dup.lan", "CNAME", "a.lan"},
		{"dup.lan", "CNAME", "b.lan"},
		{"both.lan", "CNAME", "a.lan"},
		{"both.lan", "A", "10.0.0.2"},
	}
	for _, r := range bad {
		c.DNS.Records = []Record{r}
		if r.Name == "dup.lan" || r.Name == "both.lan" {
			continue
		}
		if len(c.Validate()) == 0 {
			t.Errorf("accepted bad record %+v", r)
		}
	}
	c.DNS.Records = bad[len(bad)-4:]
	wantErrs(t, c, "duplicate CNAME", "both.lan has a CNAME and other records")
}

func TestDNSUpstreamModes(t *testing.T) {
	c := testConfig(t)
	c.DNS.Upstream = "manual"
	c.DNS.Servers = []string{"1.1.1.1", "2606:4700:4700::1111", "9.9.9.9#9953"}
	conf := dnsFiles(t, c)["/etc/dnsmasq.conf"]
	for _, s := range []string{"no-resolv\nserver=1.1.1.1\nserver=2606:4700:4700::1111\nserver=9.9.9.9#9953\n"} {
		if !strings.Contains(conf, s) {
			t.Errorf("manual: missing %q in\n%s", s, conf)
		}
	}
	if strings.Contains(conf, "resolv-file=") {
		t.Error("manual mode still reads the PPPoE resolv file")
	}

	c.DNS.Upstream = "dot"
	c.System.NTP = []string{"ntp.tencent.com", "162.159.200.1"}
	conf = dnsFiles(t, c)["/etc/dnsmasq.conf"]
	for _, s := range []string{"no-resolv\nserver=127.0.0.1#5453\n", "server=/ntp.tencent.com/1.1.1.1\n", "server=/ntp.tencent.com/1.0.0.1\n"} {
		if !strings.Contains(conf, s) {
			t.Errorf("dot: missing %q in\n%s", s, conf)
		}
	}
	if strings.Contains(conf, "server=/162.159.200.1/") || strings.Contains(conf, "resolv-file=") {
		t.Error("dot: bad bootstrap / resolv lines")
	}
	c.DNS.DoT.Bootstrap = []string{"223.5.5.5"}
	if conf = dnsFiles(t, c)["/etc/dnsmasq.conf"]; !strings.Contains(conf, "server=/ntp.tencent.com/223.5.5.5\n") || strings.Contains(conf, "server=/ntp.tencent.com/1.1.1.1") {
		t.Error("dot: explicit bootstrap not used")
	}

	c.Services.Stubby.Enabled = false
	c.DNS.Servers = []string{"1.1.1.1;reboot", "127.0.0.1", "::1#53", "1.1.1.1#99999", "-1.1.1.1"}
	c.DNS.DoT = DoT{Port: 5453, Servers: []DoTServer{{Address: "dns.google", Name: "dns.google"}, {Address: "8.8.8.8", Name: "bad name\n"}}, Bootstrap: []string{"x"}}
	wantErrs(t, c, "dot needs services.stubby.enabled", `"1.1.1.1;reboot"`, "127.0.0.1 is dnsmasq itself", "::1#53 is dnsmasq itself",
		`"1.1.1.1#99999"`, `"-1.1.1.1"`, "servers[0].address", "servers[1].name", "dns.dot.bootstrap",
		"dns.split[0].server: 127.0.0.1#5453 is stubby (DoT) but services.stubby is disabled")
	c.DNS.DoT.Port = 53
	wantErrs(t, c, "dns.dot.port: 1-65535 and not 53")
	c.DNS.Upstream = "manual"
	c.DNS.Servers = nil
	wantErrs(t, c, "upstream manual needs at least one server")
	c.DNS.Upstream = "google"
	wantErrs(t, c, "dns.upstream: isp|manual|dot")
}

func TestDHCPOptionsHostLeasesAndRA(t *testing.T) {
	c := testConfig(t)
	c.DHCP.DNS = []string{"192.168.1.6", "192.168.1.10"}
	c.DHCP.NTP = []string{"192.168.1.10"}
	c.DHCP.Search = []string{"lan", "home.example.com"}
	c.DHCP.Options = []DHCPOpt{{26, "1492"}, {121, "0.0.0.0/0,192.168.1.6,10.8.0.0/24,192.168.1.10"}, {252, "http://wpad.lan/wpad.dat"}}
	c.DHCP.HostLeases = map[string]string{"02:C3:06:D6:7F:8A": "infinite"}
	c.DHCP.IPv6 = RA{Mode: "stateful", DNS: []string{"::", "2606:4700:4700::1111"}, Priority: "high", MTU: 1492, Interval: 30, Lifetime: 900}
	c.Networks = []Network{
		{Name: "guest", IPv4: "192.168.20.1/24", IPv6RA: true, DHCP: Pool{Enabled: true, Start: 100, End: 150,
			DHCPOpts: DHCPOpts{DNS: []string{"1.1.1.1"}}, IPv6: RA{Mode: "stateless"}}},
		{Name: "iot", IPv4: "192.168.30.1/24", IPv6RA: true}, // RA without a DHCPv4 pool
	}
	c.defaults()
	conf := dnsFiles(t, c)["/etc/dnsmasq.conf"]
	for _, s := range []string{
		"dhcp-option=tag:lan,option:dns-server,192.168.1.6,192.168.1.10\n",
		"dhcp-option=tag:lan,option:ntp-server,192.168.1.10\n",
		"dhcp-option=tag:lan,option:domain-search,lan,home.example.com\n",
		"dhcp-option=tag:lan,26,1492\n",
		"dhcp-option=tag:lan,121,0.0.0.0/0,192.168.1.6,10.8.0.0/24,192.168.1.10\n",
		"dhcp-option=tag:lan,252,http://wpad.lan/wpad.dat\n",
		"dhcp-host=02:c3:06:d6:7f:8a,192.168.1.66,desktop,infinite\n",
		"dhcp-host=02:bb:dd:96:49:e2,192.168.1.241,server\n",
		"dhcp-range=::1000,::ffff,constructor:br-lan,slaac,64,45m\n",
		"ra-param=br-lan,mtu:1492,high,30,900\n",
		"dhcp-option=tag:br-lan,option6:dns-server,[::],[2606:4700:4700::1111]\n",
		"dhcp-option=tag:guest,option:dns-server,1.1.1.1\n",
		"dhcp-range=::,constructor:br-guest,ra-stateless,45m\nra-param=br-guest,60,1800\n",
		"dhcp-range=::,constructor:br-iot,ra-only,45m\nra-param=br-iot,60,1800\n",
		"enable-ra\n",
	} {
		if !strings.Contains(conf, s) {
			t.Errorf("dnsmasq.conf missing %q", s)
		}
	}
	if strings.Contains(conf, "set:iot") {
		t.Error("iot has no DHCPv4 pool")
	}
}

// Names dnsmasq would parse as something else, upstreams that are dnsmasq itself, an RA block kept
// while RA is off, and the router's own statistics probes in the query log.
func TestDNSMisparsedNamesLoopsAndQueryLog(t *testing.T) {
	for _, name := range []string{"12345", "5m", "2w", "infinite", "ignore"} {
		c := testConfig(t)
		c.DHCP.Hosts = append(c.DHCP.Hosts, Host{Name: name, MAC: "aa:bb:cc:dd:ee:01", IP: "192.168.1.50"})
		wantErrs(t, c, "dnsmasq would read")
	}
	for _, name := range []string{"123", "10.0.0.1"} {
		c := testConfig(t)
		c.DNS.Records = []Record{{Name: name, Type: "A", Value: "192.168.1.10"}}
		wantErrs(t, c, "cannot be all digits")
	}
	c := testConfig(t)
	c.DHCP.Hosts = append(c.DHCP.Hosts, Host{Name: "cam-12345", MAC: "aa:bb:cc:dd:ee:01", IP: "192.168.1.50"})
	c.DNS.Records = []Record{{Name: "*.123", Type: "A", Value: "192.168.1.10"}, {Name: "nas10", Type: "A", Value: "192.168.1.10"}}
	c.DNS.Upstream = "manual"
	c.DNS.Servers = []string{"192.168.1.6#5335"}
	c.Networks = []Network{{Name: "guest", IPv4: "192.168.20.1/24", DHCP: Pool{IPv6: RA{Mode: "stateful"}}}} // RA off
	c.defaults()
	if errs := c.Validate(); len(errs) > 0 {
		t.Fatalf("valid config rejected: %v", errs)
	}
	c.DNS.Servers = []string{"192.168.1.6", "192.168.20.1#53"}
	c.DNS.Split[0].Server = "192.168.1.6#53"
	wantErrs(t, c, "dns.servers: 192.168.1.6 is dnsmasq itself", "dns.servers: 192.168.20.1#53 is dnsmasq itself",
		"dns.split[0].server: 192.168.1.6#53 is dnsmasq itself")

	log := strings.Join([]string{
		"Sep 24 20:31:00 r daemon.info dnsmasq[1]: query[A] www.apple.com from 192.168.1.233",
		"Sep 24 20:31:00 r daemon.info dnsmasq[1]: query[TXT] hits.bind from 127.0.0.1",
		"Sep 24 20:31:00 r daemon.info dnsmasq[1]: config hits.bind is <TXT>",
		"Sep 24 20:31:00 r daemon.info dnsmasq[1]: query[TXT] servers.bind from 127.0.0.1",
		"Sep 24 20:31:00 r daemon.info mr: dns: query logging on for 10 min",
		"Sep 24 20:31:01 r daemon.info dnsmasq[1]: reply www.apple.com is 17.253.144.10",
	}, "\n")
	got := filterQueryLog(log, 300)
	if len(got) != 2 || !strings.Contains(got[0], "www.apple.com from") || !strings.Contains(got[1], "reply www.apple.com") {
		t.Fatalf("query log filter: %q", got)
	}
	if got = filterQueryLog(log, 1); len(got) != 1 || !strings.Contains(got[0], "reply") {
		t.Fatalf("limit: %q", got)
	}
}

func TestDHCPValidation(t *testing.T) {
	c := testConfig(t)
	c.DHCP.DNS = []string{"fd00::1", "1.2.3.4\n"}
	c.DHCP.NTP = []string{"pool.ntp.org"}
	c.DHCP.Search = []string{"a b"}
	c.DHCP.Options = []DHCPOpt{{3, "10.0.0.1"}, {6, "1.1.1.1"}, {53, "1"}, {0, "x"}, {255, "x"}, {66, "a b"}, {67, `"x"`}, {43, "a#b"},
		{44, "x\nlog-queries"}, {45, ""}, {46, "a,,b"}, {100, "x"}, {100, "y"}, {121, "10.8.0.0/24,192.168.1.10"}}
	c.DHCP.HostLeases = map[string]string{"aa:bb:cc:dd:ee:ff": "12h", "02:c3:06:d6:7f:8a": "forever"}
	c.DHCP.IPv6 = RA{Mode: "managed", Start: "2001:db8::1", End: "::1", Lease: "3600", DNS: []string{"1.1.1.1"}, Interval: 2, Lifetime: 10, Priority: "urgent", MTU: 100}
	wantErrs(t, c,
		`dhcp.dns: IPv4 address required, got "fd00::1"`, `dhcp.dns: IPv4 address required, got "1.2.3.4\n"`,
		`dhcp.ntp: IPv4 address required`, `dhcp.search: invalid domain "a b"`,
		"options[0].code: option 3 cannot be set here", "options[1].code: option 6", "options[2].code: option 53",
		"options[3].code: 1-254", "options[4].code: 1-254", "options[5].value", "options[6].value", "options[7].value",
		"options[8].value", "options[9].value", "options[10].value", "options[12].code: duplicate option 100",
		"options[13].value: option 121 must start with the default route",
		`"aa:bb:cc:dd:ee:ff" is not the MAC of a dhcp.hosts entry`, `dhcp.host_leases[02:c3:06:d6:7f:8a]`,
		"dhcp.ipv6.mode", "dhcp.ipv6.start/end", "dhcp.ipv6.lease", `dhcp.ipv6.dns: IPv6 address required`,
		"dhcp.ipv6.ra_interval", "dhcp.ipv6.ra_lifetime", "dhcp.ipv6.ra_priority", "dhcp.ipv6.ra_mtu")
	c = testConfig(t)
	c.DHCP.IPv6.Interval = 901 // dnsmasq would advertise lifetimes >= 2703 s, above the RFC 9096 cap
	wantErrs(t, c, "dhcp.ipv6.ra_interval: 4-900 seconds, got 901")
	c = testConfig(t)
	c.DHCP.IPv6 = RA{Mode: "stateful", Start: "::ffff", End: "::1000"}
	wantErrs(t, c, "dhcp.ipv6: start must not be above end")
}

func TestParseLeases(t *testing.T) {
	data := `1790291888 02:e3:50:10:6a:63 192.168.1.233 laptop 01:02:e3:50:10:6a:63
0 02:c3:06:d6:7f:8a 192.168.1.66 desktop *
1790289177 02:13:2c:f7:cb:f2 192.168.20.167 * *
garbage line
duid 00:01:00:01:2c:5f:aa:bb:cc:dd:ee:ff
1790291000 12345 2001:db8::1000 nas 02:76:5f:9a:cb:ec
`
	v4, v6 := parseLeases(data)
	if len(v4) != 3 || len(v6) != 1 {
		t.Fatalf("got %d v4 / %d v6", len(v4), len(v6))
	}
	if v4[0].clientID != "01:02:e3:50:10:6a:63" || v4[1].Expires != 0 || v4[1].clientID != "" || v6[0].IP != "2001:db8::1000" || v6[0].IAID != "12345" {
		t.Fatalf("%+v %+v", v4, v6)
	}
	c := testConfig(t)
	c.Networks = []Network{{Name: "guest", IPv4: "192.168.20.1/24"}}
	for i := range v4 {
		if n := lanNetFor(c, net.ParseIP(v4[i].IP)); n != nil {
			v4[i].Network = n.Name
		}
	}
	if v4[0].Network != "lan" || v4[2].Network != "guest" {
		t.Fatalf("networks: %+v", v4)
	}
}

func TestDHCPReleasePacket(t *testing.T) {
	mac, _ := net.ParseMAC("02:c3:06:d6:7f:8a")
	p := dhcpReleasePacket(net.ParseIP("192.168.1.6"), net.ParseIP("192.168.1.66"), mac, []byte{1, 0x5c, 0x1b, 0xf4, 0x77, 0x87, 0x9b})
	if len(p) != 300 || p[0] != 1 || p[1] != 1 || p[2] != 6 {
		t.Fatalf("header: len %d % x", len(p), p[:4])
	}
	if !net.IP(p[12:16]).Equal(net.ParseIP("192.168.1.66")) || string(p[28:34]) != string(mac) || binary.BigEndian.Uint32(p[236:]) != 0x63825363 {
		t.Fatal("ciaddr / chaddr / cookie")
	}
	opts := p[240:]
	want := []byte{53, 1, 7, 54, 4, 192, 168, 1, 6, 61, 7, 1, 0x5c, 0x1b, 0xf4, 0x77, 0x87, 0x9b, 255}
	if string(opts[:len(want)]) != string(want) {
		t.Fatalf("options % x", opts[:len(want)])
	}
	if err := releaseLease(testConfig(t), "192.168.1.66;x", ""); err == nil {
		t.Error("bad ip accepted")
	}
	if err := releaseLease(testConfig(t), "192.168.1.66", "zz"); err == nil {
		t.Error("bad mac accepted")
	}
	r := apiDNSRelease(apiReq{method: "GET", body: []byte(`{"ip":"192.168.1.66","mac":"02:c3:06:d6:7f:8a"}`)})
	if r.status != 405 {
		t.Error("release must require POST")
	}
	r = apiDNSRelease(apiReq{method: "POST", body: []byte(`{"ip":"192.168.1.66","mac":"-x"}`)})
	if r.status != 400 {
		t.Error("bad mac accepted by API")
	}
}

// ---- DNS client ----

// dnsTestReply builds a reply to query q with the given answers (each a pre-encoded RR after the name pointer).
func dnsTestReply(q []byte, answers ...[]byte) []byte {
	r := append([]byte{}, q...)
	binary.BigEndian.PutUint16(r[2:], 0x8180)
	binary.BigEndian.PutUint16(r[6:], uint16(len(answers)))
	for _, a := range answers {
		r = append(r, 0xC0, 12) // name = the question name
		r = append(r, a...)
	}
	return r
}

func rrBytes(typ, class uint16, ttl uint32, rdata []byte) []byte {
	b := make([]byte, 10)
	binary.BigEndian.PutUint16(b, typ)
	binary.BigEndian.PutUint16(b[2:], class)
	binary.BigEndian.PutUint32(b[4:], ttl)
	binary.BigEndian.PutUint16(b[8:], uint16(len(rdata)))
	return append(b, rdata...)
}

func txtData(ss ...string) []byte {
	var b []byte
	for _, s := range ss {
		b = append(b, byte(len(s)))
		b = append(b, s...)
	}
	return b
}

func TestDNSParseResponse(t *testing.T) {
	q, err := dnsEncodeQuery(0x1234, "nas.lan.", dnsTypeA, dnsClassIN)
	if err != nil {
		t.Fatal(err)
	}
	srv := append([]byte{0, 0, 0, 5, 0x01, 0xbd}, 0xC0, 12) // prio 0 weight 5 port 445 target = nas.lan
	msg := dnsTestReply(q,
		rrBytes(dnsTypeA, 1, 60, []byte{192, 168, 1, 10}),
		rrBytes(dnsTypeCNAME, 1, 60, []byte{0xC0, 12}),
		rrBytes(dnsTypeSRV, 1, 60, srv),
		rrBytes(dnsTypeTXT, 1, 0, txtData("a b", "c")),
		rrBytes(dnsTypeAAAA, 1, 60, net.ParseIP("fd00::10")))
	rc, rrs, err := dnsParseResponse(msg, 0x1234)
	if err != nil || rc != 0 || len(rrs) != 5 {
		t.Fatalf("rc %d err %v rrs %+v", rc, err, rrs)
	}
	want := []string{"192.168.1.10", "nas.lan", "0 5 445 nas.lan", "a b c", "fd00::10"}
	for i, w := range want {
		if rrs[i].Data != w || rrs[i].Name != "nas.lan" {
			t.Errorf("rr %d = %+v, want %q", i, rrs[i], w)
		}
	}
	if _, _, err := dnsParseResponse(msg, 0x4321); err != errDNSWrongID {
		t.Error("id not checked")
	}
	// no truncation or corruption may panic
	for n := 0; n < len(msg); n++ {
		dnsParseResponse(msg[:n], 0x1234)
		bad := append([]byte{}, msg...)
		bad[n] ^= 0xff
		dnsParseResponse(bad, 0x1234)
	}
	loop := append(append([]byte{}, msg[:12]...), 0xC0, 12, 0, 1, 0, 1)
	binary.BigEndian.PutUint16(loop[4:], 1)
	if _, _, err := dnsParseResponse(loop, 0x1234); err == nil {
		t.Error("compression loop accepted")
	}
	if _, err := dnsEncodeQuery(1, "a..b", dnsTypeA, dnsClassIN); err == nil {
		t.Error("empty label accepted")
	}
}

// A fake dnsmasq answering the CHAOS statistics queries end to end over UDP.
func TestDnsmasqStatsQuery(t *testing.T) {
	pc, err := net.ListenPacket("udp", "127.0.0.1:0")
	if err != nil {
		t.Skip(err)
	}
	defer pc.Close()
	vals := map[string][]string{"cachesize.bind": {"8000"}, "insertions.bind": {"120"}, "evictions.bind": {"0"},
		"hits.bind": {"900"}, "misses.bind": {"100"}, "servers.bind": {"127.0.0.1#5453 40 1", "192.0.2.1#53 60 0"}}
	go func() {
		buf := make([]byte, 512)
		for {
			n, addr, err := pc.ReadFrom(buf)
			if err != nil {
				return
			}
			q := append([]byte{}, buf[:n]...)
			name, next, _ := dnsReadName(q, 12)
			if binary.BigEndian.Uint16(q[next+2:]) != dnsClassCHAOS {
				continue
			}
			pc.WriteTo(dnsTestReply(q, rrBytes(dnsTypeTXT, dnsClassCHAOS, 0, txtData(vals[name]...))), addr)
		}
	}()
	st, err := queryDnsmasqStats(pc.LocalAddr().String())
	if err != nil {
		t.Fatal(err)
	}
	if st.CacheSize != 8000 || st.Insertions != 120 || st.Hits != 900 || st.Misses != 100 || len(st.Servers) != 2 ||
		st.Servers[0] != (upstreamStat{"127.0.0.1#5453", 40, 1}) || st.Servers[1].Queries != 60 {
		t.Fatalf("%+v", st)
	}
}

func TestDNSConfigJSONRoundTrip(t *testing.T) {
	c := testConfig(t)
	c.DNS.Records = []Record{{"nas", "A", "192.168.1.10"}}
	c.DHCP.HostLeases = map[string]string{"02:c3:06:d6:7f:8a": "infinite"}
	c.DHCP.Options = []DHCPOpt{{26, "1492"}}
	c.DHCP.IPv6.Mode = "stateless"
	c.DNS.Upstream = "manual"
	c.DNS.Servers = []string{"1.1.1.1"}
	m, err := configToJSON(c)
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := json.Marshal(m)
	back, _, err := configFromJSON(raw)
	if err != nil {
		t.Fatal(err)
	}
	back.secrets = c.secrets
	back.defaults()
	back.DNS.Split = c.DNS.Split
	if len(back.DNS.Records) != 1 || back.DHCP.HostLeases["02:c3:06:d6:7f:8a"] != "infinite" || back.DHCP.Options[0].Code != 26 ||
		back.DHCP.IPv6.Mode != "stateless" || back.DNS.Upstream != "manual" || back.DNS.DoT.Port != 5453 {
		t.Fatalf("round trip lost dns data: %+v %+v", back.DNS, back.DHCP)
	}
	if errs := back.Validate(); len(errs) > 0 {
		t.Fatal(errs)
	}
	// the UI always sees these keys, so it never has to create them (that would mark the page dirty)
	js := string(raw)
	for _, k := range []string{`"records":[`, `"host_leases":{`, `"options":[`, `"ipv6":{`, `"search":[`, `"dot":{`} {
		if !strings.Contains(js, k) {
			t.Errorf("config JSON lacks %s", k)
		}
	}
}

// Every DHCP/RA/record/upstream feature at once must pass the real dnsmasq parser.
func TestDnsmasqAcceptsFeatureConfig(t *testing.T) {
	bin, err := exec.LookPath("dnsmasq")
	if err != nil {
		t.Skip("dnsmasq not installed")
	}
	c := testConfig(t)
	c.DNS.Split = nil
	c.DNS.AddnHosts = nil
	c.DNS.Upstream = "dot"
	c.DNS.Records = []Record{{"nas", "A", "192.168.1.10"}, {"nas", "AAAA", "fd00::10"}, {"*.home.example.com", "A", "192.168.1.6"},
		{"photos", "CNAME", "nas.lan"}, {"192.168.1.11", "PTR", "printer.lan"}, {"_smb._tcp.lan", "SRV", "nas.lan:445:1:2"},
		{"nas.lan", "TXT", "home server; v=1, #x"}}
	c.DHCP.DHCPOpts = DHCPOpts{DNS: []string{"192.168.1.6"}, NTP: []string{"192.168.1.10"}, Search: []string{"lan"},
		Options: []DHCPOpt{{26, "1492"}, {121, "0.0.0.0/0,192.168.1.6,10.8.0.0/24,192.168.1.10"}, {252, "http://wpad.lan/wpad.dat"}, {66, "nas.lan"}}}
	c.DHCP.HostLeases = map[string]string{"02:c3:06:d6:7f:8a": "infinite", "02:bb:dd:96:49:e2": "1d"}
	c.DHCP.IPv6 = RA{Mode: "stateful", DNS: []string{"::"}, Priority: "low", MTU: 1492}
	c.Networks = []Network{{Name: "guest", IPv4: "192.168.20.1/24", IPv6RA: true,
		DHCP: Pool{Enabled: true, Start: 10, End: 20, DHCPOpts: DHCPOpts{Search: []string{"guest.lan"}}, IPv6: RA{Mode: "stateless"}}}}
	c.defaults()
	for _, mode := range []string{"dot", "manual", "isp"} {
		c.DNS.Upstream = mode
		c.DNS.Servers = []string{"1.1.1.1", "2606:4700:4700::1111#53"}
		conf := dnsFiles(t, c)["/etc/dnsmasq.conf"]
		path := filepath.Join(t.TempDir(), "dnsmasq.conf")
		os.WriteFile(path, []byte(conf), 0644)
		if out, err := exec.Command(bin, "--test", "--conf-file="+path).CombinedOutput(); err != nil {
			t.Fatalf("%s: dnsmasq --test: %v\n%s\n%s", mode, err, out, conf)
		}
	}
}
