package main

// sys module: hostname, time (timezone, NTP client/server), sysctl, SSH (dropbear, managed
// authorized_keys), add-on services (tailscale, lucky, dstatus, stubby, web UI, zram), scheduled
// tasks (busybox crond), backup/restore, firmware upgrade / factory reset, logs, diagnostics.
// Owns router.yaml: system, services, schedules. Files: mod_sys_time.go (TZ, TZif, NTP),
// mod_sys_ssh.go, mod_sys_cron.go, mod_sys_backup.go, mod_sys_fw.go, mod_sys_api.go.
// Docs: docs/modules/sys.md.

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

type System struct {
	Hostname  string            `yaml:"hostname"`
	Timezone  string            `yaml:"timezone"`             // POSIX TZ string, e.g. "<+07>-7"
	NTP       []string          `yaml:"ntp"`                  // servers the router syncs from
	NTPServer bool              `yaml:"ntp_server,omitempty"` // also answer NTP on udp/123 (LAN zone only, via the firewall)
	Sysctl    map[string]string `yaml:"sysctl"`
	Zram      bool              `yaml:"zram"`
	// Watchdog: feed the hardware watchdog (busybox watchdog on /dev/watchdog). Default on; set false
	// on hardware without one (the service would fail and every apply would roll back).
	Watchdog *bool `yaml:"watchdog,omitempty"`
	// LEDs: front-panel status / network LEDs (default on; false = all off, e.g. at night)
	LEDs *bool `yaml:"leds,omitempty"`
}

type Services struct {
	Tailscale Tailscale `yaml:"tailscale"`
	Lucky     Lucky     `yaml:"lucky"`
	Dstatus   Toggle    `yaml:"dstatus"`
	Stubby    Toggle    `yaml:"stubby"`
	SSH       SSH       `yaml:"ssh"`
	Panel     Toggle    `yaml:"panel"`
}

type Toggle struct {
	Enabled bool `yaml:"enabled"`
}

type Tailscale struct {
	Enabled bool `yaml:"enabled"`
	Port    int  `yaml:"port"` // tailscaled --port (UDP, opened on the WANs)
}

type Lucky struct {
	Enabled bool `yaml:"enabled"`
	Port    int  `yaml:"port,omitempty"` // Lucky's own web UI port (only used for the link in the web UI)
}

type SSH struct {
	Enabled       bool     `yaml:"enabled"`
	Port          int      `yaml:"port"`
	PasswordLogin bool     `yaml:"password_login"`
	LANOnly       bool     `yaml:"lan_only,omitempty"`        // listen only on the LAN-zone router addresses (IPv4)
	Keys          []string `yaml:"authorized_keys,omitempty"` // managed block in /root/.ssh/authorized_keys
}

// conntrackMax is the default nf_conntrack_max (overridable with system.sysctl).
const conntrackMax = "100000"

func renderSysctl(c *Config) string {
	base := map[string]string{
		"net.ipv4.ip_forward":                  "1",
		"net.ipv6.conf.all.forwarding":         "1",
		"net.ipv6.conf.default.forwarding":     "1",
		"net.ipv4.tcp_syncookies":              "1",
		"net.ipv4.conf.all.arp_ignore":         "1",
		"net.ipv4.conf.default.arp_ignore":     "1",
		"net.ipv4.icmp_echo_ignore_broadcasts": "1",
		"net.core.default_qdisc":               "fq_codel",
		"net.core.rps_sock_flow_entries":       "32768",
		"net.core.netdev_max_backlog":          "2000",
		"net.netfilter.nf_conntrack_max":       conntrackMax,
		"kernel.panic":                         "3",
	}
	for k, v := range c.System.Sysctl {
		base[k] = v
	}
	keys := make([]string, 0, len(base))
	for k := range base {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("# generated by mr — edit router.yaml instead\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, base[k])
	}
	return b.String()
}

// Boot order for net.netfilter.* keys: nf_conntrack is a module that the firewall would only load
// after the boot-time `sysctl` service ran, so those keys failed ("unknown key") and were never
// applied at boot. The `modules` service loads it from /etc/modules-load.d/mr-sys.conf and
// /etc/conf.d/sysctl orders `sysctl` after `modules` (both in the boot runlevel).
const (
	modulesLoadFile = "/etc/modules-load.d/mr-sys.conf"
	modulesLoad     = "# generated by mr: net.netfilter.* sysctls (nf_conntrack_max, ...) need it before the boot sysctl run\nnf_conntrack\n"
	sysctlConfFile  = "/etc/conf.d/sysctl"
	sysctlConf      = "# generated by mr: apply sysctl.d after kernel modules are loaded (nf_conntrack for net.netfilter.*)\nrc_after=\"modules\"\n"
)

func sysRender(c *Config, out *Out) error {
	sv := c.Services
	out.Add("/etc/hostname", 0644, c.System.Hostname+"\n")
	out.Add("/etc/sysctl.d/90-mini-router.conf", 0644, renderSysctl(c))
	out.Add(modulesLoadFile, 0644, modulesLoad)
	out.Add(sysctlConfFile, 0644, sysctlConf)
	tzif, err := tzifFromPOSIX(sysTZ(c))
	if err != nil {
		return fmt.Errorf("system.timezone: %w", err)
	}
	out.Add("/etc/localtime", 0644, string(tzif))
	out.Add("/etc/profile.d/tz.sh", 0644, fmt.Sprintf("export TZ=%q\n", c.System.Timezone))
	out.Add("/etc/conf.d/ntpd", 0644, renderNtpd(c))
	// conf.d files of optional services only while they are enabled: a changed file restarts its
	// service, which must not start a service that is being switched off
	if sv.SSH.Enabled {
		out.Add("/etc/conf.d/dropbear", 0644, renderDropbear(c))
	}
	if sv.Tailscale.Enabled {
		out.Add("/etc/conf.d/tailscale", 0644, fmt.Sprintf("# generated by mr\nTS_PORT=%d\n", sv.Tailscale.Port))
	}
	if ip, _, ok := strings.Cut(c.LAN.IPv4, "/"); ok && sv.Panel.Enabled {
		out.Add("/etc/conf.d/mr-panel", 0644, fmt.Sprintf("# generated by mr: the web UI listens on the main LAN address\nPANEL_ADDR=%s\n", ip))
	}
	if cronWanted(c) {
		out.Add("/etc/conf.d/crond", 0644, renderCrondConf(c))
	}
	if data, ok := renderCrontab(c); ok {
		out.Add(cronFile, 0600, data)
	}
	if data, ok := renderAuthKeys(c); ok {
		out.Add(authKeysFile, 0600, data)
	}
	return nil
}

func sysRestart(path string) string {
	switch {
	case path == "/etc/hostname":
		return "hostname"
	case strings.HasPrefix(path, "/etc/sysctl.d/"):
		return "sysctl"
	case path == modulesLoadFile, path == sysctlConfFile, path == "/etc/profile.d/tz.sh":
		return "-" // boot-time only / login shells
	case path == "/etc/localtime":
		return "syslog" // log timestamps; musl reads the zone once per process
	case path == "/etc/conf.d/ntpd":
		return "ntpd"
	case path == "/etc/conf.d/dropbear":
		return "dropbear"
	case path == "/etc/conf.d/tailscale":
		return "tailscale"
	case path == "/etc/conf.d/mr-panel":
		return "mr-panel"
	case path == "/etc/conf.d/crond":
		return "crond"
	case path == cronFile, path == authKeysFile:
		return "-" // crond rescans /etc/crontabs when the directory changes; dropbear reads keys per login
	}
	return ""
}

func sysServices(c *Config) []string {
	s := []string{"ntpd"}
	sv := c.Services
	if sv.SSH.Enabled {
		s = append(s, "dropbear")
	}
	if sv.Tailscale.Enabled {
		s = append(s, "tailscale")
	}
	if sv.Lucky.Enabled {
		s = append(s, "lucky", "lucky-dns-inotify")
	}
	if sv.Dstatus.Enabled {
		s = append(s, "dstatus-agent")
	}
	if sv.Stubby.Enabled {
		s = append(s, "stubby")
	}
	if sv.Panel.Enabled {
		s = append(s, "mr-panel")
	}
	if c.System.Zram {
		s = append(s, "mr-zram")
	}
	if cronWanted(c) {
		s = append(s, "crond")
	}
	return s
}

func init() {
	register(&Module{
		Name: "sys",
		Prio: 70,
		Defaults: func(c *Config) {
			if c.Services.SSH.Port == 0 {
				c.Services.SSH.Port = 22
			}
			if c.Services.Tailscale.Port == 0 {
				c.Services.Tailscale.Port = 41641
			}
			if c.Services.Lucky.Port == 0 {
				c.Services.Lucky.Port = 16601
			}
			if len(c.System.NTP) == 0 {
				c.System.NTP = []string{"pool.ntp.org"} // no RTC: the clock must come from somewhere
			}
		},
		Validate: sysValidate,
		Render:   sysRender,
		Nft: func(c *Config, hook string, n *Nft) {
			if hook == "input" && c.Services.Tailscale.Enabled {
				n.W("iifname { %s } udp dport %d accept comment \"tailscale\"", quoteList(c.WANIfnames()), c.Services.Tailscale.Port)
			}
		},
		FlowDevs: func(c *Config) []string {
			if c.Services.Tailscale.Enabled {
				return []string{"tailscale0"}
			}
			return nil
		},
		Services:     sysServices,
		Managed:      []string{"dropbear", "tailscale", "lucky", "lucky-dns-inotify", "dstatus-agent", "stubby", "mr-panel", "mr-zram", "crond"},
		Restart:      sysRestart,
		RestartOrder: []string{"ntpd", "syslog", "dropbear", "crond", "tailscale", "mr-panel"},
		Status: func(c *Config, st map[string]any) {
			ts := map[string]any{"state": "unavailable"}
			if !c.Services.Tailscale.Enabled {
				ts["state"] = "disabled"
			} else if out, err := run("tailscale", "status", "--json"); err == nil {
				if t, err := tailscaleStatus([]byte(out)); err == nil {
					self, _ := t["self"].(*tsNode)
					ip := ""
					if self != nil && len(self.TailscaleIPs) > 0 {
						ip = self.TailscaleIPs[0]
					}
					ts = map[string]any{"state": t["state"], "ip": ip, "peers_online": t["peers_online"], "peers_total": t["peers_total"]}
				}
			}
			st["tailscale"] = ts
		},
		API: map[string]func(r apiReq) apiResp{
			"diag":              apiDiag,
			"service":           apiService,
			"sys.time":          apiSysTime,
			"sys.sshkeys":       apiSysSSHKeys,
			"sys.services":      apiSysServices,
			"sys.logs":          apiSysLogs,
			"sys.backup":        apiSysBackup,
			"sys.restore":       apiSysRestore,
			"sys.fw":            apiSysFw,
			"sys.fwupload":      apiSysFwUpload,
			"sys.fwupgrade":     apiSysFwUpgrade,
			"sys.factoryreset":  apiSysFactoryReset,
			"sys.schedulecheck": apiSysScheduleCheck,
		},
		Commands: map[string]func(c *Config, args []string) error{
			"sys": sysCommand,
		},
	})
}

var (
	reHostnameSys = regexp.MustCompile(`^[A-Za-z0-9]([A-Za-z0-9-]{0,62})$`)
	reSysctlKey   = regexp.MustCompile(`^[a-z0-9_]+(\.[A-Za-z0-9_-]+)+$`)
)

func sysValidate(c *Config, v *Validator) {
	s := c.System
	if !reHostnameSys.MatchString(s.Hostname) {
		v.Add("system.hostname: letters, digits, '-', got %q", s.Hostname)
	}
	if s.Timezone != "" {
		if _, err := parseTZ(s.Timezone); err != nil {
			v.Add("system.timezone: POSIX TZ string (e.g. \"<+07>-7\", \"CET-1CEST,M3.5.0,M10.5.0/3\"): %v", err)
		}
	}
	if len(s.NTP) > 8 {
		v.Add("system.ntp: at most 8 servers")
	}
	for _, n := range s.NTP {
		if !validNTPServer(n) {
			v.Add("system.ntp: invalid server %q (host name or IP address)", n)
		}
	}
	if len(s.Sysctl) > 64 {
		v.Add("system.sysctl: at most 64 keys")
	}
	for k, val := range s.Sysctl {
		if !reSysctlKey.MatchString(k) || len(k) > 128 {
			v.Add("system.sysctl: invalid key %q", k)
		}
		if !safeText(val) || strings.ContainsAny(val, "=") || len(val) > 256 {
			v.Add("system.sysctl.%s: invalid value", k)
		}
	}
	sv := c.Services
	if sv.Tailscale.Port < 1 || sv.Tailscale.Port > 65535 {
		v.Add("services.tailscale.port: 1-65535")
	}
	if sv.Lucky.Port < 1 || sv.Lucky.Port > 65535 {
		v.Add("services.lucky.port: 1-65535")
	}
	validateSSH(c, v)
	validateSchedules(c, v)
}

// apiSysScheduleCheck: POST {cron, action, target} → {ok, error, cron (normalized)} so the schedule
// editor can check a time spec before the whole config is validated.
func apiSysScheduleCheck(r apiReq) apiResp {
	var in struct {
		Cron   string `json:"cron"`
		Action string `json:"action"`
	}
	json.Unmarshal(r.body, &in)
	spec, err := checkCron(in.Cron, in.Action)
	if err != nil {
		return apiResp{body: map[string]any{"ok": false, "error": err.Error()}}
	}
	return apiResp{body: map[string]any{"ok": true, "cron": spec}}
}
