package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"gopkg.in/yaml.v3"
)

// sysTemp points the files the sys module reads while rendering at a temp dir.
func sysTemp(t *testing.T) string {
	t.Helper()
	d := t.TempDir()
	oldAK, oldCron := authKeysFile, cronFile
	authKeysFile, cronFile = filepath.Join(d, "authorized_keys"), filepath.Join(d, "crontab")
	t.Cleanup(func() { authKeysFile, cronFile = oldAK, oldCron })
	return d
}

// fakeKey builds a syntactically valid public key line (type string + 32 bytes in the blob).
func fakeKey(typ string, seed byte, comment string) string {
	var b []byte
	put := func(s []byte) {
		var l [4]byte
		binary.BigEndian.PutUint32(l[:], uint32(len(s)))
		b = append(append(b, l[:]...), s...)
	}
	put([]byte(typ))
	put(bytes.Repeat([]byte{seed}, 32))
	line := typ + " " + base64.StdEncoding.EncodeToString(b)
	if comment != "" {
		line += " " + comment
	}
	return line
}

func TestSysParseTZ(t *testing.T) {
	good := map[string][2]int{ // std offset, dst offset (east of UTC)
		"<+07>-7":                        {25200, 0},
		"UTC0":                           {0, 0},
		"CST-8":                          {28800, 0},
		"IST-5:30":                       {19800, 0},
		"<-03>3":                         {-10800, 0},
		"CET-1CEST,M3.5.0,M10.5.0/3":     {3600, 7200},
		"EST5EDT,M3.2.0,M11.1.0":         {-18000, -14400},
		"AEST-10AEDT,M10.1.0,M4.1.0/3":   {36000, 39600},
		"NZST-12NZDT,M9.5.0,M4.1.0/3":    {43200, 46800},
		"<+0330>-3:30":                   {12600, 0},
		"ABC+5DEF+4:30,J60/2,300/1:30:5": {-18000, -16200},
	}
	for s, want := range good {
		z, err := parseTZ(s)
		if err != nil {
			t.Errorf("%q rejected: %v", s, err)
			continue
		}
		if z.StdOff != want[0] || (z.HasDST && z.DSTOff != want[1]) {
			t.Errorf("%q: offsets %d/%d, want %v", s, z.StdOff, z.DSTOff, want)
		}
	}
	for _, s := range []string{"", "Asia/Bangkok", ":Asia/Bangkok", "UT0", "CET", "CET-1CEST", "<+7>-7", "<+07-7",
		"UTC0\n", "UTC0;reboot", "UTC 0", "UTC25", "CET-1CEST,M3.5.0", "CET-1CEST,M13.5.0,M10.5.0", "CET-1CEST,M3.6.0,M10.5.0",
		"CET-1CEST,M3.5.7,M10.5.0", "CET-1CEST,M3.5.0,M10.5.0/25", "CET-1CEST,J0,J365", "CET-1CEST,M3.5.0,M10.5.0,x",
		"UTC0'", `UTC0"`, "UTC-1:60", strings.Repeat("A", 70) + "0"} {
		if _, err := parseTZ(s); err == nil {
			t.Errorf("%q accepted", s)
		}
	}
}

func TestSysTZif(t *testing.T) {
	jan := time.Date(2026, 1, 15, 12, 0, 0, 0, time.UTC)
	jul := time.Date(2026, 7, 15, 12, 0, 0, 0, time.UTC)
	past := time.Date(1990, 7, 1, 0, 0, 0, 0, time.UTC)
	for tz, want := range map[string][3]int{ // offset in January, July, July 1990
		"<+07>-7":                      {25200, 25200, 25200},
		"UTC0":                         {0, 0, 0},
		"IST-5:30":                     {19800, 19800, 19800},
		"CET-1CEST,M3.5.0,M10.5.0/3":   {3600, 7200, 7200},
		"EST5EDT,M3.2.0,M11.1.0":       {-18000, -14400, -14400},
		"AEST-10AEDT,M10.1.0,M4.1.0/3": {39600, 36000, 36000},
	} {
		data, err := tzifFromPOSIX(tz)
		if err != nil {
			t.Fatalf("%s: %v", tz, err)
		}
		if !bytes.HasPrefix(data, []byte("TZif2")) || !bytes.HasSuffix(data, []byte("\n"+tz+"\n")) {
			t.Errorf("%s: bad framing", tz)
		}
		loc, err := time.LoadLocationFromTZData(tz, data)
		if err != nil {
			t.Fatalf("%s: Go rejects the TZif: %v", tz, err)
		}
		for i, at := range []time.Time{jan, jul, past} {
			if _, off := at.In(loc).Zone(); off != want[i] {
				t.Errorf("%s at %s: offset %d, want %d", tz, at.Format("2006-01"), off, want[i])
			}
		}
	}
	if name, _ := jul.In(sysLocation(&Config{System: System{Timezone: "CET-1CEST,M3.5.0,M10.5.0/3"}})).Zone(); name != "CEST" {
		t.Errorf("zone name %q, want CEST", name)
	}
	if sysLocation(&Config{}).String() != "UTC0" {
		t.Error("empty timezone must be UTC")
	}
}

// The real home config renders the same service options as before this module grew, plus the
// new boot-order and time files.
func TestSysRenderHome(t *testing.T) {
	d := sysTemp(t)
	os.WriteFile(authKeysFile, []byte(fakeKey("ssh-ed25519", 1, "image-build")+"\n"), 0600)
	c := testConfig(t)
	f := renderMap(t, c)
	for p, want := range map[string]string{
		"/etc/conf.d/ntpd":                "# generated by mr\nNTPD_OPTS=\"-N -S /usr/libexec/mr/clock-save -p ntp.tencent.com -p ntp1.aliyun.com -p ntp.ntsc.ac.cn -p cn.ntp.org.cn\"\n",
		"/etc/conf.d/dropbear":            "# generated by mr\nDROPBEAR_OPTS=\"-p 22 -K 300 -s -g\"\n",
		"/etc/profile.d/tz.sh":            "export TZ=\"<+08>-8\"\n",
		"/etc/hostname":                   "mini-router\n",
		"/etc/conf.d/tailscale":           "# generated by mr\nTS_PORT=41641\n",
		"/etc/modules-load.d/mr-sys.conf": modulesLoad,
		"/etc/conf.d/sysctl":              sysctlConf,
	} {
		if f[p] != want {
			t.Errorf("%s = %q, want %q", p, f[p], want)
		}
	}
	wantSubs(t, "sysctl", f["/etc/sysctl.d/90-mini-router.conf"], "net.netfilter.nf_conntrack_max=100000\n", "net.ipv4.tcp_congestion_control=bbr\n", "net.ipv4.ip_forward=1\n",
		"net.ipv4.conf.all.send_redirects=0\n", "net.ipv4.conf.default.send_redirects=0\n",
		"kernel.kptr_restrict=2\n", "kernel.dmesg_restrict=1\n", "net.core.bpf_jit_harden=2\n", "net.core.rmem_max=7500000\n",
		"net.core.wmem_max=7500000\n", "net.ipv4.tcp_notsent_lowat=131072\n", "net.ipv4.tcp_slow_start_after_idle=0\n")
	wantSubs(t, "mr-panel", f["/etc/conf.d/mr-panel"], "PANEL_ADDR=192.168.1.6\n")
	wantSubs(t, "rc_after", f["/etc/conf.d/sysctl"], `rc_after="modules"`)
	loc, err := time.LoadLocationFromTZData("x", []byte(f["/etc/localtime"]))
	if err != nil {
		t.Fatal(err)
	}
	if _, off := time.Now().In(loc).Zone(); off != 8*3600 {
		t.Errorf("localtime offset %d", off)
	}
	// no schedules, no managed keys, no block in the files: mr leaves crontab and authorized_keys alone
	for _, p := range []string{cronFile, authKeysFile, "/etc/conf.d/crond"} {
		if _, ok := f[p]; ok {
			t.Errorf("%s rendered without schedules / managed keys", p)
		}
	}
	svcs := strings.Join(enabledServices(c), " ")
	for _, s := range []string{"ntpd", "dropbear", "tailscale", "lucky", "dstatus-agent", "stubby", "mr-panel", "mr-zram"} {
		if !strings.Contains(" "+svcs+" ", " "+s+" ") {
			t.Errorf("service %s not enabled: %s", s, svcs)
		}
	}
	if strings.Contains(svcs, "crond") {
		t.Error("crond enabled without schedules")
	}
	_ = d
}

func TestSysRestartMap(t *testing.T) {
	for p, want := range map[string]string{
		"/etc/hostname": "hostname", "/etc/sysctl.d/90-mini-router.conf": "sysctl", "/etc/localtime": "syslog",
		"/etc/conf.d/ntpd": "ntpd", "/etc/conf.d/dropbear": "dropbear", "/etc/conf.d/tailscale": "tailscale",
		"/etc/conf.d/mr-panel": "mr-panel", "/etc/conf.d/crond": "crond", "/etc/crontabs/root": "",
		"/root/.ssh/authorized_keys": "", "/etc/modules-load.d/mr-sys.conf": "", "/etc/conf.d/sysctl": "",
		"/etc/profile.d/tz.sh": "",
	} {
		if got := serviceFor(p); got != want {
			t.Errorf("serviceFor(%s) = %q, want %q", p, got, want)
		}
	}
}

func TestSysValidate(t *testing.T) {
	sysTemp(t)
	c := testConfig(t)
	c.System.Timezone = "Asia/Bangkok"
	c.System.NTP = []string{"pool.ntp.org", "keyno:1:x", "-p", "a b", "2001:db8::1"}
	c.System.Sysctl["bad key"] = "1"
	c.Services.SSH.Port = 80
	c.Services.SSH.Keys = []string{
		fakeKey("ssh-ed25519", 1, "ok"),
		fakeKey("ssh-ed25519", 1, "dup"),
		`command="/bin/sh" ` + fakeKey("ssh-ed25519", 2, ""),
		"ssh-ed25519 AAAA\nssh-rsa x",
		"ssh-ed25519 " + base64.StdEncoding.EncodeToString([]byte("\x00\x00\x00\x07ssh-rsa")),
		"ssh-dss AAAAB3NzaC1kc3M=",
	}
	c.Services.Lucky.Port = 70000
	errs := strings.Join(c.Validate(), "\n")
	for _, s := range []string{"system.timezone", `invalid server "keyno:1:x"`, `invalid server "-p"`, `invalid server "a b"`,
		`system.sysctl: invalid key "bad key"`, "services.ssh.port: 80", "authorized_keys[1]: duplicate", "authorized_keys[2]: unsupported key type",
		"authorized_keys[3]: control characters", "authorized_keys[4]: key data does not match", "authorized_keys[5]: unsupported key type",
		"services.lucky.port"} {
		if !strings.Contains(errs, s) {
			t.Errorf("want error %q in:\n%s", s, errs)
		}
	}
	if strings.Contains(errs, "2001:db8::1") || strings.Contains(errs, `"pool.ntp.org"`) {
		t.Errorf("valid NTP server rejected:\n%s", errs)
	}
	c = testConfig(t)
	c.System.NTP = nil
	c.defaults()
	if strings.Join(c.System.NTP, " ") != "pool.ntp.org" {
		t.Errorf("empty NTP list not defaulted: %v", c.System.NTP)
	}
}

func TestSysNTPServer(t *testing.T) {
	sysTemp(t)
	c := testConfig(t)
	c.System.NTPServer = true
	f := renderMap(t, c)
	wantSubs(t, "ntpd", f["/etc/conf.d/ntpd"], `-p cn.ntp.org.cn -l"`)
	// reachable from the LAN zone only: the fw input chain accepts LAN-zone interfaces and drops
	// the rest; sys must not open udp/123 anywhere
	nft := renderNft(c, func(string) bool { return true })
	if strings.Contains(nft, "dport 123") {
		t.Error("NTP server opened in the firewall")
	}
}

func TestSysSSH(t *testing.T) {
	sysTemp(t)
	k1, k2 := fakeKey("ssh-ed25519", 1, "laptop"), fakeKey("ecdsa-sha2-nistp256", 2, "phone key")
	c := testConfig(t)
	c.Networks = []Network{
		{Name: "guest", IPv4: "192.168.20.1/24", Zone: "guest"},
		{Name: "iot", IPv4: "192.168.30.1/24", Zone: "lan"},
	}
	c.Services.SSH.LANOnly = true
	c.Services.SSH.PasswordLogin = true
	c.Services.SSH.Port = 2222
	c.Services.SSH.Keys = []string{k1, "  " + strings.ReplaceAll(k2, " ", "   ") + "  "}
	c.defaults()
	if errs := c.Validate(); len(errs) > 0 {
		t.Fatal(errs)
	}
	existing := "# keys from the image build\n" + fakeKey("ssh-ed25519", 9, "image") + "\n" + `no-pty ` + fakeKey("ssh-rsa", 8, "") + "\n"
	os.WriteFile(authKeysFile, []byte(existing), 0600)
	f := renderMap(t, c)
	if got := f["/etc/conf.d/dropbear"]; got != "# generated by mr\nDROPBEAR_OPTS=\"-p 192.168.1.6:2222 -p 192.168.30.1:2222 -K 300\"\n" {
		t.Errorf("dropbear: %q", got)
	}
	ak := f[authKeysFile]
	want := existing + akBegin + "\n" + k1 + "\n" + k2 + "\n" + akEnd + "\n"
	if ak != want {
		t.Fatalf("authorized_keys:\n%s\nwant:\n%s", ak, want)
	}
	// idempotent, block replaced in place, unmanaged lines kept (also after the block)
	os.WriteFile(authKeysFile, []byte(ak+"ssh-ed25519 added-by-hand-after\n"), 0600)
	c.Services.SSH.Keys = []string{k2}
	ak2 := renderMap(t, c)[authKeysFile]
	if ak2 != existing+akBegin+"\n"+k2+"\n"+akEnd+"\nssh-ed25519 added-by-hand-after\n" {
		t.Errorf("replace in place:\n%s", ak2)
	}
	// no managed keys left: the block goes, everything else stays
	os.WriteFile(authKeysFile, []byte(ak2), 0600)
	c.Services.SSH.Keys = nil
	if got := renderMap(t, c)[authKeysFile]; got != existing+"ssh-ed25519 added-by-hand-after\n" {
		t.Errorf("remove block:\n%s", got)
	}
	// ssh disabled: dropbear's conf.d is not rendered (a restart must not start it again)
	c.Services.SSH.Enabled = false
	if _, ok := renderMap(t, c)["/etc/conf.d/dropbear"]; ok {
		t.Error("dropbear conf.d rendered while ssh is disabled")
	}
	k, err := parseAuthKey(k1)
	if err != nil || k.Type != "ssh-ed25519" || k.Comment != "laptop" || !strings.HasPrefix(k.FP, "SHA256:") || len(k.FP) != 7+43 {
		t.Errorf("parseAuthKey: %+v %v", k, err)
	}
}

func TestSysMergeManaged(t *testing.T) {
	const b, e = "#B", "#E"
	for _, tc := range []struct {
		cur   string
		lines []string
		want  string
		ok    bool
	}{
		{"", nil, "", false},
		{"a\n", nil, "a\n", false},
		{"", []string{"x"}, "#B\nx\n#E\n", true},
		{"a", []string{"x"}, "a\n#B\nx\n#E\n", true},
		{"a\n#B\nold\n#E\nz\n", []string{"x", "y"}, "a\n#B\nx\ny\n#E\nz\n", true},
		{"a\n#B\nold\n#E\nz\n", nil, "a\nz\n", true},
		{"a\n#B\nold\nswallowed\n", []string{"x"}, "a\n#B\nx\n#E\n", true}, // begin without end: rest was ours
		{"a\n#E\nb\n", nil, "a\nb\n", true},                                // stray end marker dropped
		{"a\n\n\nb\n\n", []string{"x"}, "a\n\n\nb\n\n#B\nx\n#E\n", true},   // blank lines kept
		{"#B\nold\n#E\n", nil, "", true},
	} {
		got, ok := mergeManaged(tc.cur, b, e, tc.lines)
		if got != tc.want || ok != tc.ok {
			t.Errorf("mergeManaged(%q, %q) = %q %v, want %q %v", tc.cur, tc.lines, got, ok, tc.want, tc.ok)
		}
		if ok {
			if again, _ := mergeManaged(got, b, e, tc.lines); again != got {
				t.Errorf("not idempotent for %q: %q", tc.cur, again)
			}
		}
	}
}

func TestSysCron(t *testing.T) {
	for spec, act := range map[string]string{
		"30 4 * * *": "reboot", "0 3 * * 1": "reboot", "5 4 1,15 * *": "reboot", "0 4 * * 1-5": "reboot",
		"0 */6 * * *": "restart", "15 0-23/2 * * *": "reconnect", "0 1,13 * 1-12/3 0,6": "restart", "59 23 31 12 6": "reboot",
		" 0  4 * * * ": "reboot",
	} {
		if _, err := checkCron(spec, act); err != nil {
			t.Errorf("%q (%s) rejected: %v", spec, act, err)
		}
	}
	for spec, act := range map[string]string{
		"* * * * *": "restart", "*/5 * * * *": "restart", "0 */6 * * *": "reboot", "0 1,2 * * *": "reboot",
		"0 4 * * 7": "reboot", "60 4 * * *": "reboot", "0 24 * * *": "reboot", "0 4 0 * *": "reboot",
		"0 4 * 13 *": "reboot", "0 4 * * mon": "reboot", "@reboot": "reboot", "0 4 * *": "reboot",
		"0 4 * * * *": "reboot", "0 4-2 * * *": "restart", "0 5/2 * * *": "restart", "0 */0 * * *": "restart",
		"0 4 * * *;reboot": "reboot", "0 4 * * $(x)": "reboot", "-1 4 * * *": "reboot", "0 004 * * *": "reboot",
	} {
		if _, err := checkCron(spec, act); err == nil {
			t.Errorf("%q (%s) accepted", spec, act)
		}
	}

	sysTemp(t)
	os.WriteFile(cronFile, []byte("# do daily/weekly/monthly maintenance\n*/15\t*\t*\t*\t*\trun-parts /etc/periodic/15min\n"), 0600)
	c := testConfig(t)
	off := false
	c.Schedules = []Schedule{
		{Name: "weekly-reboot", Cron: "30 4 * * 1", Action: "reboot"},
		{Name: "wifi", Cron: "0 5 * * *", Action: "restart", Target: "mr-hostapd"},
		{Name: "redial-wan2", Cron: "0 */6 * * *", Action: "reconnect", Target: "wan2"},
		{Name: "paused", Enabled: &off, Cron: "0 1 * * *", Action: "reboot"},
	}
	if errs := c.Validate(); len(errs) > 0 {
		t.Fatal(errs)
	}
	f := renderMap(t, c)
	want := "# do daily/weekly/monthly maintenance\n*/15\t*\t*\t*\t*\trun-parts /etc/periodic/15min\n" + cronBegin + "\n" +
		"# weekly-reboot\n30 4 * * 1 /usr/sbin/mr sys run reboot\n" +
		"# wifi\n0 5 * * * /usr/sbin/mr sys run restart mr-hostapd\n" +
		"# redial-wan2\n0 */6 * * * /usr/sbin/mr sys run reconnect wan2\n" + cronEnd + "\n"
	if f[cronFile] != want {
		t.Errorf("crontab:\n%s\nwant:\n%s", f[cronFile], want)
	}
	if f["/etc/conf.d/crond"] != "# generated by mr\nCRON_OPTS=\"-c /etc/crontabs\"\n# schedules run in the router's zone (system.timezone)\nexport TZ='<+08>-8'\n" {
		t.Errorf("conf.d/crond: %q", f["/etc/conf.d/crond"])
	}
	if !strings.Contains(strings.Join(enabledServices(c), " "), "crond") {
		t.Error("crond not enabled")
	}
	if svc, err := scheduleService(c, "reconnect", "wan"); err != nil || svc != "mr-pppoe.wan" {
		t.Errorf("reconnect wan: %q %v", svc, err)
	}

	c.Schedules = []Schedule{
		{Name: "bad name!", Cron: "0 4 * * *", Action: "reboot"},
		{Name: "x", Cron: "0 4 * * *", Action: "restart", Target: "sshd; reboot"},
		{Name: "x", Cron: "0 4 * * *", Action: "reconnect", Target: "nope"},
		{Name: "y", Cron: "0 4 * * *", Action: "restart", Target: "mr-network"},
		{Name: "z", Cron: "0 4 * * *", Action: "reboot", Target: "now"},
		{Name: "w", Cron: "0 4 * * *", Action: "shutdown"},
		{Name: "v", Cron: "* 4 * * *", Action: "restart", Target: "dnsmasq"},
	}
	errs := strings.Join(c.Validate(), "\n")
	for _, s := range []string{"schedules[0].name", `is not a service this config enables`, `no wan "nope"`, "mr-network cannot",
		"reboot takes no target", "schedules[5]: action", "schedules[2].name: duplicate", "schedules[6].cron: minute must be one number"} {
		if !strings.Contains(errs, s) {
			t.Errorf("want error %q in:\n%s", s, errs)
		}
	}
	// removing every schedule removes the block but keeps Alpine's lines
	os.WriteFile(cronFile, []byte(want), 0600)
	c.Schedules = nil
	f = renderMap(t, c)
	if f[cronFile] != "# do daily/weekly/monthly maintenance\n*/15\t*\t*\t*\t*\trun-parts /etc/periodic/15min\n" {
		t.Errorf("crontab after removing schedules:\n%s", f[cronFile])
	}
	if _, ok := f["/etc/conf.d/crond"]; ok {
		t.Error("conf.d/crond rendered without schedules")
	}
}

// backupEnv points backup/restore at a temp tree: live config (the home config with its split
// list moved into the temp dns dir), secrets, list dirs, history, staging.
func backupEnv(t *testing.T) (dir string, cfg *Config) {
	t.Helper()
	d := sysTemp(t)
	oldC, oldS, oldH, oldR, oldL := sysConfigPath, sysSecretsPath, sysHistoryDir, restoreDir, backupListDirs
	t.Cleanup(func() {
		sysConfigPath, sysSecretsPath, sysHistoryDir, restoreDir, backupListDirs = oldC, oldS, oldH, oldR, oldL
	})
	sysConfigPath, sysSecretsPath = filepath.Join(d, "router.yaml"), filepath.Join(d, "secrets.yaml")
	sysHistoryDir, restoreDir = filepath.Join(d, "history"), filepath.Join(d, "restore")
	backupListDirs = map[string]string{"dns": filepath.Join(d, "dns"), "proxy": filepath.Join(d, "proxy")}
	os.MkdirAll(backupListDirs["dns"], 0755)
	os.MkdirAll(backupListDirs["proxy"], 0755)
	c := testConfig(t)
	c.DNS.Split[0].DomainsFile = filepath.Join(backupListDirs["dns"], "cloudflare-dot.domains")
	y, err := yaml.Marshal(c)
	if err != nil {
		t.Fatal(err)
	}
	os.WriteFile(sysConfigPath, y, 0644)
	os.WriteFile(sysSecretsPath, []byte("pppoe_password: live-pw\nwifi_key: live-key-123\nwebui_password: pbkdf2-sha256$1$aa$bb\n"), 0600)
	os.WriteFile(c.DNS.Split[0].DomainsFile, []byte("old.example\n"), 0644)
	os.WriteFile(filepath.Join(backupListDirs["proxy"], "work.domains"), []byte("work.example\n"), 0644)
	os.Symlink("/etc/passwd", filepath.Join(backupListDirs["proxy"], "evil.domains"))
	return d, c
}

func tarGz(t *testing.T, entries ...[3]string) []byte { // name, typeflag ("0", "5", "2"), content
	t.Helper()
	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gz)
	for _, e := range entries {
		h := &tar.Header{Name: e[0], Typeflag: e[1][0], Mode: 0644, Size: int64(len(e[2]))}
		if e[1] != "0" {
			h.Size = 0
		}
		if e[1] == "2" {
			h.Linkname = "/etc/passwd"
		}
		tw.WriteHeader(h)
		if e[1] == "0" {
			tw.Write([]byte(e[2]))
		}
	}
	tw.Close()
	gz.Close()
	return buf.Bytes()
}

func TestSysBackupRestore(t *testing.T) {
	d, c := backupEnv(t)
	dnsList := c.DNS.Split[0].DomainsFile
	plain, names, err := makeBackup(false)
	if err != nil {
		t.Fatal(err)
	}
	if got := strings.Join(names, " "); got != "etc/mini-router/router.yaml etc/mini-router/dns/cloudflare-dot.domains etc/mini-router/proxy/work.domains" {
		t.Errorf("backup files: %s", got)
	}
	withSec, names, _ := makeBackup(true)
	if !strings.Contains(strings.Join(names, " "), "etc/mini-router/secrets.yaml") {
		t.Error("secrets not included")
	}
	rs, err := parseBackup(withSec)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := rs.secrets[pwSecretKey]; ok || rs.secrets["pppoe_password"] != "live-pw" {
		t.Errorf("backup secrets: %v", rs.secrets)
	}
	if rs2, _ := parseBackup(plain); rs2.secrets != nil {
		t.Error("plain backup carries secrets")
	}

	// restore a backup whose lists differ: lists are snapshotted and replaced, the candidate is valid
	os.WriteFile(dnsList, []byte("changed.example\n"), 0644)
	y, sec, snap, errs, err := restoreStage(rs)
	if err != nil || len(errs) > 0 {
		t.Fatal(err, errs)
	}
	if b, _ := os.ReadFile(dnsList); string(b) != "old.example\n" {
		t.Errorf("list not restored: %q", b)
	}
	if !strings.HasSuffix(snap, "-restore-lists.tar.gz") || len(y) == 0 || sec[pwSecretKey] != "pbkdf2-sha256$1$aa$bb" || sec["pppoe_password"] != "live-pw" {
		t.Errorf("stage: snap %q, secrets %v", snap, sec)
	}
	undoLists(snap) // the snapshot is in the core format: restore() puts the list back
	if b, _ := os.ReadFile(dnsList); string(b) != "changed.example\n" {
		t.Errorf("undo: %q", b)
	}

	// a backup whose config does not validate leaves the lists untouched
	bad := tarGz(t, [3]string{"etc/mini-router/router.yaml", "0", "system: {hostname: \"a b\"}\n"},
		[3]string{"etc/mini-router/dns/cloudflare-dot.domains", "0", "new.example\n"})
	rs, err = parseBackup(bad)
	if err != nil {
		t.Fatal(err)
	}
	_, _, _, errs, err = restoreStage(rs)
	if err != nil || len(errs) == 0 {
		t.Fatalf("invalid config accepted: %v %v", err, errs)
	}
	if b, _ := os.ReadFile(dnsList); string(b) != "changed.example\n" {
		t.Errorf("failed restore left list changed: %q", b)
	}
	if ents, _ := os.ReadDir(restoreDir); len(ents) != 0 {
		t.Errorf("staging files left behind: %v", ents)
	}

	// a list the config needs, emptied by the backup: render fails, lists go back
	y0, _ := os.ReadFile(sysConfigPath)
	rs, _ = parseBackup(tarGz(t, [3]string{"etc/mini-router/router.yaml", "0", string(y0)},
		[3]string{"etc/mini-router/dns/cloudflare-dot.domains", "0", "# nothing\n"}))
	if _, _, _, errs, _ := restoreStage(rs); len(errs) == 0 || !strings.Contains(errs[0], "has no domains") {
		t.Errorf("render error not reported: %v", errs)
	}
	if b, _ := os.ReadFile(dnsList); string(b) != "changed.example\n" {
		t.Errorf("list changed after render failure: %q", b)
	}

	for name, arch := range map[string][]byte{
		"traversal":     tarGz(t, [3]string{"etc/mini-router/../../etc/passwd", "0", "x"}),
		"absolute":      tarGz(t, [3]string{"/etc/mini-router/router.yaml", "0", "x"}),
		"other file":    tarGz(t, [3]string{"etc/shadow", "0", "x"}),
		"symlink":       tarGz(t, [3]string{"etc/mini-router/router.yaml", "2", ""}),
		"list subdir":   tarGz(t, [3]string{"etc/mini-router/router.yaml", "0", "x"}, [3]string{"etc/mini-router/dns/a/b.domains", "0", "x"}),
		"dotdot list":   tarGz(t, [3]string{"etc/mini-router/router.yaml", "0", "x"}, [3]string{"etc/mini-router/dns/..domains", "0", "x"}),
		"hidden list":   tarGz(t, [3]string{"etc/mini-router/router.yaml", "0", "x"}, [3]string{"etc/mini-router/dns/.x", "0", "x"}),
		"binary list":   tarGz(t, [3]string{"etc/mini-router/router.yaml", "0", "x"}, [3]string{"etc/mini-router/dns/a.domains", "0", "a\x00b"}),
		"no router.yml": tarGz(t, [3]string{"etc/mini-router/dns/a.domains", "0", "a"}),
		"duplicate":     tarGz(t, [3]string{"etc/mini-router/router.yaml", "0", "x"}, [3]string{"etc/mini-router/router.yaml", "0", "y"}),
		"bad secret":    tarGz(t, [3]string{"etc/mini-router/router.yaml", "0", "x"}, [3]string{"etc/mini-router/secrets.yaml", "0", "\"a b\": x\n"}),
		"other dir":     tarGz(t, [3]string{"etc/init.d/", "5", ""}),
		"not gzip":      []byte("hello"),
		"too big":       bytes.Repeat([]byte{1}, backupMaxUpload+1),
	} {
		if _, err := parseBackup(arch); err == nil {
			t.Errorf("%s: accepted", name)
		}
	}
	// GNU tar style "./" entries are fine
	if _, err := parseBackup(tarGz(t, [3]string{"./", "5", ""}, [3]string{"./etc/mini-router/", "5", ""}, [3]string{"./etc/mini-router/router.yaml", "0", "x"})); err != nil {
		t.Errorf("./ prefixed archive rejected: %v", err)
	}
	_ = d
}

func TestSysLogs(t *testing.T) {
	d := t.TempDir()
	old := logFiles
	t.Cleanup(func() { logFiles = old })
	logFiles = []string{filepath.Join(d, "messages.0"), filepath.Join(d, "messages")}
	os.WriteFile(logFiles[0], []byte("Sep 24 11:00:00 mini-router daemon.err dnsmasq[1]: old error\n"), 0644)
	os.WriteFile(logFiles[1], []byte(strings.Join([]string{
		"Sep 24 11:09:53 mini-router daemon.info dnsmasq-dhcp[15210]: RTR-ADVERT(br-lan) 2001:db8::",
		"Sep 24 11:10:05 mini-router authpriv.info dropbear[15413]: Exit (root) from <192.168.1.137:58135>: Disconnect received",
		"Sep 24 11:11:43 mini-router daemon.warn hostapd: phy1-ap0: STA 02:e3:50:10:6a:63 IEEE 802.11: disassociated",
		"Sep 24 11:12:00 mini-router kern.err kernel: [ 1.0] oops",
		"garbage line",
	}, "\n")+"\n"), 0644)
	e := parseSyslogLine("Sep 24 11:10:05 mini-router authpriv.info dropbear[15413]: Exit (root): x")
	if e.T != "Sep 24 11:10:05" || e.Lvl != 6 || e.Fac != "authpriv" || e.Tag != "dropbear" || e.Msg != "Exit (root): x" {
		t.Errorf("parse: %+v", e)
	}
	get := func(body string) map[string]any {
		t.Helper()
		resp := apiSysLogs(apiReq{method: "POST", body: []byte(body)})
		if resp.status != 0 && resp.status != 200 {
			t.Fatalf("%s: %v", body, resp.body)
		}
		b, _ := json.Marshal(resp.body)
		var m map[string]any
		json.Unmarshal(b, &m)
		return m
	}
	all := get(`{}`)
	if n := len(all["lines"].([]any)); n != 6 {
		t.Errorf("all: %d lines", n)
	}
	first := all["lines"].([]any)[0].([]any)
	if first[4] != "garbage line" || first[1].(float64) != -1 {
		t.Errorf("newest first / unknown level: %v", first)
	}
	if n := len(get(`{"level":3}`)["lines"].([]any)); n != 2 {
		t.Errorf("level<=err: %d", n)
	}
	if n := len(get(`{"level":4,"tag":"hostapd"}`)["lines"].([]any)); n != 1 {
		t.Errorf("warn+hostapd: %d", n)
	}
	if n := len(get(`{"q":"DISCONNECT"}`)["lines"].([]any)); n != 1 {
		t.Errorf("q: %d", n)
	}
	if tags := get(`{}`)["tags"].(map[string]any); tags["dnsmasq-dhcp"].(float64) != 1 || tags["kernel"].(float64) != 1 {
		t.Errorf("tags: %v", tags)
	}
	if r := apiSysLogs(apiReq{method: "POST", body: []byte(`{"level":9}`)}); r.status != 400 {
		t.Error("bad level accepted")
	}
}

func TestSysFirmwareUpload(t *testing.T) {
	d := t.TempDir()
	oldS, oldF, oldD, oldR := fwSysupgrade, fwFactoryReset, fwDir, fwRunDir
	t.Cleanup(func() { fwSysupgrade, fwFactoryReset, fwDir, fwRunDir = oldS, oldF, oldD, oldR })
	fwSysupgrade, fwFactoryReset = filepath.Join(d, "sysupgrade"), filepath.Join(d, "factory-reset")
	fwDir, fwRunDir = filepath.Join(d, "up"), filepath.Join(d, "run")
	// a symlink or foreign file where the private upload dir goes is replaced, never followed
	os.Symlink(d, fwDir)
	post := func(f func(apiReq) apiResp, body any) apiResp {
		b, _ := json.Marshal(body)
		return f(apiReq{method: "POST", body: b})
	}
	img := bytes.Repeat([]byte("firmware-"), 1000)
	chunk := func(off, n int) map[string]any {
		return map[string]any{"offset": off, "total": len(img), "data": base64.StdEncoding.EncodeToString(img[off : off+n])}
	}
	if r := post(apiSysFwUpload, chunk(0, 4000)); r.status != 501 {
		t.Errorf("upload without the platform script: %d", r.status)
	}
	if st := apiSysFw(apiReq{method: "GET"}).body.(map[string]any); st["sysupgrade"] != false {
		t.Error("sysupgrade reported without the script")
	}
	os.WriteFile(fwSysupgrade, []byte("#!/bin/sh\necho \"refused: $1 is not an AX6000 image\" >&2\nexit 3\n"), 0755)
	if r := post(apiSysFwUpload, chunk(0, 4000)); r.status != 0 {
		t.Fatalf("first chunk: %v", r.body)
	}
	r := post(apiSysFwUpload, chunk(5000, 1000)) // gap
	if r.status != 409 || r.body.(map[string]any)["received"] != int64(4000) {
		t.Errorf("gap accepted: %d %v", r.status, r.body)
	}
	if r := post(apiSysFwUpgrade, map[string]any{"sha256": strings.Repeat("0", 64)}); r.status != 409 {
		t.Errorf("upgrade with a partial image: %d", r.status)
	}
	if r := post(apiSysFwUpload, chunk(4000, len(img)-4000)); r.status != 0 {
		t.Fatalf("last chunk: %v", r.body)
	}
	if r := post(apiSysFwUpload, map[string]any{"offset": len(img) - 10, "total": len(img), "data": base64.StdEncoding.EncodeToString(make([]byte, 20))}); r.status != 400 {
		t.Errorf("chunk past the end: %d", r.status)
	}
	if fi, err := os.Lstat(fwDir); err != nil || !fi.IsDir() || fi.Mode().Perm() != 0700 {
		t.Errorf("upload dir: %v %v", fi, err)
	}
	if b, _ := os.ReadFile(fwImage()); !bytes.Equal(b, img) {
		t.Fatal("assembled image differs")
	}
	if r := post(apiSysFwUpgrade, map[string]any{"sha256": strings.Repeat("0", 64)}); r.status != 400 {
		t.Errorf("sha mismatch accepted: %d", r.status)
	}
	sum := sha256.Sum256(img)
	if r := post(apiSysFwUpgrade, map[string]any{"sha256": strings.ToUpper(hex.EncodeToString(sum[:]))}); r.status != 0 {
		t.Fatalf("upgrade: %v", r.body)
	}
	// the (fake) platform script refuses: its exit code and stderr reach the status
	var st map[string]any
	for i := 0; i < 50; i++ {
		st = fwRunStatus()
		if st["state"] != "running" {
			break
		}
		time.Sleep(100 * time.Millisecond)
	}
	if st["state"] != "failed" || st["rc"] != 3 || !strings.Contains(st["message"].(string), "refused: "+fwImage()) {
		t.Errorf("run status: %v", st)
	}
	if r := post(apiSysFactoryReset, map[string]any{"confirm": "yes"}); r.status != 400 {
		t.Errorf("factory reset without RESET: %d", r.status)
	}
	if r := post(apiSysFactoryReset, map[string]any{"confirm": "RESET"}); r.status != 501 {
		t.Errorf("factory reset without the script: %d", r.status)
	}
	if r := post(apiSysFwUpload, map[string]any{"cancel": true}); r.status != 0 {
		t.Error("cancel")
	}
	if _, err := os.Stat(fwImage()); err == nil {
		t.Error("cancel kept the image")
	}
}

// API input checks that must reject before anything runs (no command is executed here).
func TestSysAPIRejects(t *testing.T) {
	post := func(f func(apiReq) apiResp, body string) int {
		return f(apiReq{method: "POST", body: []byte(body)}).status
	}
	for _, body := range []string{`{"tool":"ping","host":"-c 1 x"}`, `{"tool":"ping","host":"a;reboot"}`, `{"tool":"ping","host":"$(id)"}`,
		`{"tool":"rm","host":"x"}`, `{"tool":"ping","host":""}`, `{"tool":"nslookup","host":"a b"}`} {
		if st := post(apiDiag, body); st != 400 {
			t.Errorf("diag %s: status %d", body, st)
		}
	}
	for name, f := range map[string]func(apiReq) apiResp{"diag": apiDiag, "service": apiService, "sys.backup": apiSysBackup,
		"sys.restore": apiSysRestore, "sys.fwupload": apiSysFwUpload, "sys.fwupgrade": apiSysFwUpgrade, "sys.factoryreset": apiSysFactoryReset} {
		if st := f(apiReq{method: "GET"}).status; st != 405 {
			t.Errorf("%s via GET: status %d", name, st)
		}
	}
	valid := base64.StdEncoding.EncodeToString(tarGz(t, [3]string{"etc/mini-router/router.yaml", "0", "x"}))
	for body, want := range map[string]int{
		`{"data":"not base64!"}`: 400,
		`{"data":"` + base64.StdEncoding.EncodeToString(tarGz(t, [3]string{"etc/passwd", "0", "x"})) + `"}`: 400,
		`{"data":"` + valid + `","confirm":5}`:                           400,
		`{"data":"` + valid + `","confirm":9999}`:                        400,
		`{"data":"` + strings.Repeat("A", backupMaxUpload*4/3+12) + `"}`: 413,
	} {
		if st := post(apiSysRestore, body); st != want {
			t.Errorf("restore %.60s: status %d, want %d", body, st, want)
		}
	}
	r := apiSysScheduleCheck(apiReq{method: "POST", body: []byte(`{"cron":" 30  4 * * 1","action":"reboot"}`)}).body.(map[string]any)
	if r["ok"] != true || r["cron"] != "30 4 * * 1" {
		t.Errorf("schedulecheck: %v", r)
	}
	r = apiSysScheduleCheck(apiReq{method: "POST", body: []byte(`{"cron":"* * * * *","action":"restart"}`)}).body.(map[string]any)
	if r["ok"] != false || !strings.Contains(r["error"].(string), "minute") {
		t.Errorf("schedulecheck: %v", r)
	}
}

func TestSysTailscaleStatus(t *testing.T) {
	raw := `{"BackendState":"Running","AuthURL":"","MagicDNSSuffix":"tail1234.ts.net",
	 "Self":{"HostName":"mini-router","DNSName":"mini-router.tail1234.ts.net.","OS":"linux","TailscaleIPs":["100.64.0.1","fd7a:115c:a1e0::1"],"Online":true},
	 "Peer":{"k1":{"HostName":"zeta","OS":"iOS","TailscaleIPs":["100.64.0.3"],"Online":false,"LastSeen":"2026-09-20T10:00:00Z"},
	         "k2":{"HostName":"alpha","OS":"macOS","TailscaleIPs":["100.64.0.2"],"Online":true,"CurAddr":"203.0.113.5:41641","RxBytes":10,"TxBytes":20}},
	 "CurrentTailnet":{"Name":"example@github"}}`
	ts, err := tailscaleStatus([]byte(raw))
	if err != nil {
		t.Fatal(err)
	}
	peers := ts["peers"].([]*tsNode)
	if len(peers) != 2 || peers[0].HostName != "alpha" || peers[0].CurAddr == "" || ts["peers_online"] != 1 || ts["tailnet"] != "example@github" {
		t.Errorf("tailscale: %+v %v", ts, peers)
	}
	if _, ok := ts["auth_url"]; ok {
		t.Error("auth_url while running")
	}
	ts, _ = tailscaleStatus([]byte(`{"BackendState":"NeedsLogin","AuthURL":"https://login.tailscale.com/a/abc"}`))
	if ts["auth_url"] != "https://login.tailscale.com/a/abc" {
		t.Errorf("auth_url: %v", ts)
	}
}
