package main

// mon module: realtime monitoring (interface traffic, CPU per core, memory, load, conntrack,
// temperature), 24 h history, per-device traffic, connections, processes and kernel log.
// No router.yaml section. Nothing stays resident except the tiny busybox-sh history sampler
// (rootfs/usr/libexec/mr/mon-collect, service mr-mon); everything else is computed on demand by
// the `mr api` CGI (web UI) or `mr mon ...` (CLI / agent). Docs: docs/modules/mon.md.
//
// Files: mod_mon.go (module, mon.now, CLI), mod_mon_hist.go (mon.history),
// mod_mon_ct.go (conntrack: mon.devices, mon.conns), mod_mon_sys.go (mon.procs, mon.dmesg),
// mod_mon_linux.go / mod_mon_other.go (rtnetlink neighbour dump, kernel log syscall).

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	monDir      = "/run/mr-mon" // RAM only (tmpfs): history ring + per-flow byte snapshot
	monHistFile = monDir + "/history"
	monFlowFile = monDir + "/flows"
	monSysctl   = "/etc/sysctl.d/91-mon.conf"
	monConfD    = "/etc/conf.d/mr-mon"
)

// monRoot prefixes every /proc, /sys, /run and lease path the module reads (tests use a fake tree).
var monRoot = ""

func monPath(p string) string { return monRoot + p }

func init() {
	register(&Module{
		Name:   "mon",
		Prio:   50,
		Render: monRender,
		// the history sampler is always on: ~1 MB RSS, one sample per minute
		Services: func(c *Config) []string { return []string{"mr-mon"} },
		Managed:  []string{"mr-mon"},
		Restart: func(path string) string {
			switch path {
			case monSysctl:
				return "sysctl"
			case monConfD:
				return "mr-mon"
			}
			return ""
		},
		RestartOrder: []string{"mr-mon"},
		API: map[string]func(r apiReq) apiResp{
			"mon.now":     monAPI(true, func(c *Config, _ []byte) (any, error) { return monNow(c), nil }),
			"mon.history": monAPI(true, func(c *Config, _ []byte) (any, error) { return monHistoryFor(c, monPath(monHistFile)) }),
			"mon.devices": monAPI(true, func(c *Config, _ []byte) (any, error) { return monDevices(c) }),
			"mon.conns":   monAPI(true, monConns),
			"mon.procs":   monAPI(false, func(*Config, []byte) (any, error) { return monProcs(), nil }),
			"mon.dmesg":   monAPI(false, func(*Config, []byte) (any, error) { return monDmesg() }),
		},
		Commands: map[string]func(c *Config, args []string) error{"mon": monCmd},
	})
}

// monRender: conntrack byte accounting (per-device traffic) and the sampler's WAN device list.
func monRender(c *Config, out *Out) error {
	out.Add(monSysctl, 0644, "# generated by mr (mon) — per-connection byte/packet counters for per-device traffic\n"+
		"net.netfilter.nf_conntrack_acct=1\n")
	out.Add(monConfD, 0644, fmt.Sprintf("# generated by mr (mon) — physical WAN devices whose counters the history sampler sums\nMON_WAN=%q\n",
		strings.Join(monWANDevs(c), " ")))
	return nil
}

// monWANDevs: the distinct physical WAN devices. Both PPPoE sessions of the home config share
// `wan`; the physical device also sees flow-offloaded packets that bypass pppoe-* counters.
// Names go into a shell-sourced file, so anything that is not a plain netdev name is dropped.
func monWANDevs(c *Config) []string {
	var out []string
	seen := map[string]bool{}
	if c == nil {
		return out
	}
	for _, w := range c.WAN {
		d := w.Device
		if d == "" || d == "." || d == ".." || !reDev.MatchString(d) || seen[d] {
			continue
		}
		seen[d] = true
		out = append(out, d)
	}
	return out
}

// monAPI adapts a read-only handler (GET or POST, no side effects on the router). With needCfg it
// loads router.yaml for names/roles; handlers cope with a nil config if the file is broken.
func monAPI(needCfg bool, f func(c *Config, body []byte) (any, error)) func(r apiReq) apiResp {
	return func(r apiReq) apiResp {
		var c *Config
		if needCfg {
			if lc, err := loadConfig(ConfigPath, SecretsPath); err == nil {
				c = lc
			}
		}
		v, err := f(c, r.body)
		if err != nil {
			return errResp(400, "%v", err)
		}
		return apiResp{body: v}
	}
}

// monCmd: `mr mon now|history [FILE]|devices|conns [FILTER-JSON]|procs|dmesg` prints the same JSON
// as the web UI API, for agents and SSH.
func monCmd(c *Config, args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: mr mon now | history [FILE] | devices | conns ['{\"proto\":\"tcp\",\"limit\":50}'] | procs | dmesg")
	}
	var v any
	var err error
	switch args[0] {
	case "now":
		v = monNow(c)
	case "history":
		p := monPath(monHistFile)
		if len(args) > 1 {
			p = args[1]
		}
		v, err = monHistoryFor(c, p)
	case "devices":
		v, err = monDevices(c)
	case "conns":
		var body []byte
		if len(args) > 1 {
			body = []byte(args[1])
		}
		v, err = monConns(c, body)
	case "procs":
		v = monProcs()
	case "dmesg":
		v, err = monDmesg()
	default:
		return fmt.Errorf("mr mon: unknown view %q", args[0])
	}
	if err != nil {
		return err
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", " ")
	return enc.Encode(v)
}

// ---- mon.now: raw counters + timestamp; the UI computes rates between its 2 s polls ----

type monIface struct {
	Name  string `json:"name"`
	Role  string `json:"role,omitempty"`     // wan | wan-dev | lan | port | wifi | vpn
	State string `json:"state"`              // up | down | … (operstate; ppp/tun "unknown" resolved by IFF_UP|IFF_RUNNING)
	Raw   string `json:"oper_raw,omitempty"` // the kernel's operstate when State was derived from the flags
	RX    uint64 `json:"rx"`                 // bytes
	TX    uint64 `json:"tx"`
	RXP   uint64 `json:"rxp"` // packets
	TXP   uint64 `json:"txp"`
	Err   uint64 `json:"err"`  // rx + tx errors
	Drop  uint64 `json:"drop"` // rx + tx drops
}

// monDisk: a filesystem the monitor shows (config storage on flash, /tmp in RAM).
type monDisk struct {
	Name    string `json:"name"` // config | tmp
	Path    string `json:"path"`
	TotalKB int64  `json:"total_kb"`
	AvailKB int64  `json:"avail_kb"`
}

func monDisks() []monDisk {
	out := []monDisk{}
	for _, d := range []monDisk{{Name: "config", Path: "/etc/mini-router"}, {Name: "tmp", Path: "/tmp"}} {
		if d.TotalKB, d.AvailKB = dfKB(d.Path); d.TotalKB > 0 {
			out = append(out, d)
		}
	}
	return out
}

type monTemp struct {
	Zone string `json:"zone"`
	Type string `json:"type"`
	MC   int64  `json:"mc"` // millidegrees Celsius
}

func monNow(c *Config) map[string]any {
	cpu, cpus := monParseStat(readFile(monPath("/proc/stat")))
	mem := monParseMeminfo(readFile(monPath("/proc/meminfo")))
	st := map[string]any{
		"t":    time.Now().UnixMilli(),
		"up":   monUptime(),
		"hz":   100,  // USER_HZ of /proc/stat
		"cpu":  cpu,  // user nice system idle iowait irq softirq steal (jiffies, cumulative)
		"cpus": cpus, // same, per core
		"mem": map[string]int64{
			"total": mem["MemTotal"], "avail": mem["MemAvailable"], "free": mem["MemFree"],
			"buffers": mem["Buffers"], "cached": mem["Cached"], "swap_total": mem["SwapTotal"], "swap_free": mem["SwapFree"],
		},
		"ct":     atoi(strings.TrimSpace(readFile(monPath("/proc/sys/net/netfilter/nf_conntrack_count")))),
		"ct_max": atoi(strings.TrimSpace(readFile(monPath("/proc/sys/net/netfilter/nf_conntrack_max")))),
		"temps":  monTemps(),
		"disks":  monDisks(),
		"ifaces": monIfaces(c),
	}
	if f := strings.Fields(readFile(monPath("/proc/loadavg"))); len(f) >= 4 {
		st["load"] = []float64{atof(f[0]), atof(f[1]), atof(f[2])}
		if r, t, ok := strings.Cut(f[3], "/"); ok {
			st["procs_running"], st["procs"] = atoi(r), atoi(t)
		}
	}
	return st
}

func monUptime() float64 { return atof(firstField(readFile(monPath("/proc/uptime")))) }

// monParseStat returns the aggregate and per-core counters (8 fields each) of /proc/stat.
func monParseStat(s string) ([]uint64, [][]uint64) {
	var total []uint64
	cores := [][]uint64{}
	for _, l := range strings.Split(s, "\n") {
		if !strings.HasPrefix(l, "cpu") {
			continue
		}
		f := strings.Fields(l)
		v := make([]uint64, 8)
		for i := 0; i < 8 && i+1 < len(f); i++ {
			v[i], _ = strconv.ParseUint(f[i+1], 10, 64)
		}
		if f[0] == "cpu" {
			total = v
		} else {
			cores = append(cores, v)
		}
	}
	return total, cores
}

func monParseMeminfo(s string) map[string]int64 {
	m := map[string]int64{}
	for _, l := range strings.Split(s, "\n") {
		f := strings.Fields(l)
		if len(f) >= 2 {
			m[strings.TrimSuffix(f[0], ":")], _ = strconv.ParseInt(f[1], 10, 64)
		}
	}
	return m
}

func monTemps() []monTemp {
	out := []monTemp{}
	zones, _ := filepath.Glob(monPath("/sys/class/thermal/thermal_zone*"))
	sort.Strings(zones)
	for _, z := range zones {
		t := strings.TrimSpace(readFile(z + "/temp"))
		if t == "" {
			continue
		}
		v, _ := strconv.ParseInt(t, 10, 64)
		out = append(out, monTemp{Zone: filepath.Base(z), Type: strings.TrimSpace(readFile(z + "/type")), MC: v})
	}
	return out
}

// monRoles labels netdevs by what router.yaml says they are, then by what sysfs says.
func monRoles(c *Config) map[string]string {
	r := map[string]string{}
	if c == nil {
		return r
	}
	for _, w := range c.WAN {
		r[w.Device] = "wan-dev"
	}
	for _, w := range c.WAN {
		r[w.Ifname()] = "wan"
	}
	for _, b := range c.LANBridges() {
		r[b] = "lan"
	}
	return r
}

func monIfaces(c *Config) []monIface {
	roles := monRoles(c)
	out := []monIface{}
	for _, l := range strings.Split(readFile(monPath("/proc/net/dev")), "\n") {
		name, rest, ok := strings.Cut(l, ":")
		name = strings.TrimSpace(name)
		if !ok || name == "" || name == "lo" || strings.Contains(name, "|") {
			continue
		}
		f := strings.Fields(rest)
		if len(f) < 16 {
			continue
		}
		n := func(i int) uint64 { v, _ := strconv.ParseUint(f[i], 10, 64); return v }
		sys := monPath("/sys/class/net/" + name)
		raw := strings.TrimSpace(readFile(sys + "/operstate"))
		it := monIface{Name: name, Role: roles[name], State: effOper(raw, readFile(sys+"/flags")),
			RX: n(0), RXP: n(1), TX: n(8), TXP: n(9), Err: n(2) + n(10), Drop: n(3) + n(11)}
		if raw != it.State {
			it.Raw = raw
		}
		if it.Role == "" {
			switch {
			case monExists(sys + "/phy80211"):
				it.Role = "wifi"
			case monExists(sys + "/brport"):
				it.Role = "port"
			case name == "tailscale0" || strings.HasPrefix(name, "tun") || strings.HasPrefix(name, "wg"):
				it.Role = "vpn"
			}
		}
		out = append(out, it)
	}
	return out
}

func monExists(p string) bool { _, err := os.Stat(p); return err == nil }
