package main

import (
	"encoding/json"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"gopkg.in/yaml.v3"
)

// wifiLabConfig is the home config with the wifi section of examples/lab.d/20-wifi.yaml, the lab's extra
// networks (guest, iot) and the lab wifi secrets.
func wifiLabConfig(t *testing.T) *Config {
	t.Helper()
	c := testConfig(t)
	b, err := os.ReadFile("../examples/lab.d/20-wifi.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var frag struct {
		WiFi WiFi `yaml:"wifi"`
	}
	dec := yaml.NewDecoder(strings.NewReader(string(b)))
	dec.KnownFields(true)
	if err := dec.Decode(&frag); err != nil {
		t.Fatal(err)
	}
	c.WiFi = frag.WiFi
	c.Networks = []Network{
		{Name: "guest", IPv4: "192.168.20.1/24", DHCP: Pool{Enabled: true, Start: 100, End: 199}},
		{Name: "iot", IPv4: "192.168.30.1/24", Zone: "lan", DHCP: Pool{Enabled: true, Start: 50, End: 99}},
	}
	sb, err := os.ReadFile("testdata/secrets.d/wifi.yaml")
	if err != nil {
		t.Fatal(err)
	}
	extra := map[string]string{}
	if err := yaml.Unmarshal(sb, &extra); err != nil {
		t.Fatal(err)
	}
	for k, v := range extra {
		c.secrets[k] = v
	}
	c.defaults()
	if errs := c.Validate(); len(errs) > 0 {
		t.Fatalf("lab wifi invalid:\n%s", strings.Join(errs, "\n"))
	}
	return c
}

// The real home config must render exactly what it rendered before the wifi module grew (golden files
// captured from the base commit): same hostapd configs, same wifi-post.sh, same network.sh wifi phase.
func TestWifiHomeUnchanged(t *testing.T) {
	c := testConfig(t)
	got := renderMap(t, c)
	var ns strings.Builder
	wifiNetSh(c, "wifi", &ns)
	for path, golden := range map[string]string{
		"/etc/hostapd/hostapd-phy0.conf": "hostapd-phy0.conf.golden",
		"/etc/hostapd/hostapd-phy1.conf": "hostapd-phy1.conf.golden",
		GenDir + "/wifi-post.sh":         "wifi-post.sh.golden",
		"netsh":                          "netsh-wifi.golden",
	} {
		want, err := os.ReadFile(filepath.Join("testdata/wifi-home", golden))
		if err != nil {
			t.Fatal(err)
		}
		have := got[path]
		if path == "netsh" {
			have = ns.String()
		}
		if have != string(want) {
			t.Errorf("%s changed for the home config:\n--- want\n%s\n--- got\n%s", path, want, have)
		}
	}
	for p := range got {
		if strings.HasSuffix(p, ".maclist") {
			t.Errorf("home config has no MAC filter, got %s", p)
		}
	}
}

func TestWifiLabRender(t *testing.T) {
	c := wifiLabConfig(t)
	got := renderMap(t, c)
	p0, p1 := got["/etc/hostapd/hostapd-phy0.conf"], got["/etc/hostapd/hostapd-phy1.conf"]
	for _, s := range []string{
		"bss=phy0-ap0-1\n", "bridge=br-iot\n", "ignore_broadcast_ssid=1\n", "dtim_period=3\n",
		"macaddr_acl=1\naccept_mac_file=/etc/hostapd/phy0-ap0-1.maclist\n",
		"wpa_key_mgmt=WPA-PSK\nieee80211w=0\nwpa_passphrase=iot-key-7654321\n",
	} {
		if !strings.Contains(p0, s) {
			t.Errorf("phy0: missing %q", s)
		}
	}
	if strings.Contains(p0, "supported_rates=") {
		t.Error("phy0: legacy_rates must keep the 802.11b rates (no supported_rates)")
	}
	for _, s := range []string{
		"beacon_int=200\n", "interface=phy1-ap0\n", "bss=phy1-ap0-1\n", "bss=phy1-ap0-2\n", "bss=phy1-ap0-3\n",
		"macaddr_acl=0\ndeny_mac_file=/etc/hostapd/phy1-ap0.maclist\n",
		"wpa_key_mgmt=SAE\nieee80211w=2\n", "sae_password=wpa3 key|with pipe\n",
		"bridge=br-guest\n", "ap_isolate=1\nmax_num_sta=16\n", "ap_isolate=1\nmax_num_sta=8\n",
		"wpa_key_mgmt=WPA-PSK WPA-PSK-SHA256\nieee80211w=1\nwpa_passphrase=guest-key-2468\n",
		"ssid2=" + "4d696e69526f7574657220e8aebfe5aea2" + "\n", // "MiniRouter 访客"
	} {
		if !strings.Contains(p1, s) {
			t.Errorf("phy1: missing %q", s)
		}
	}
	// the open guest SSID is the last BSS: no security lines after it
	if last := p1[strings.LastIndex(p1, "bss="):]; strings.Contains(last, "wpa=") {
		t.Error("open SSID got WPA settings")
	}
	if got["/etc/hostapd/phy0-ap0-1.maclist"] != "# generated by mr — edit router.yaml instead\naa:bb:cc:00:00:01\naa:bb:cc:00:00:02\n" {
		t.Errorf("allow list: %q", got["/etc/hostapd/phy0-ap0-1.maclist"])
	}
	if !strings.Contains(got["/etc/hostapd/phy1-ap0.maclist"], "de:ad:be:ef:00:01\n") {
		t.Error("deny list missing")
	}
	post := got[GenDir+"/wifi-post.sh"]
	for _, s := range []string{"mr_wait phy1-ap0-2 && echo 1 > /sys/class/net/phy1-ap0-2/brport/isolated", "mr_wait phy1-ap0-3 &&",
		// every extra BSS is waited for, so the `mr fw` after this script puts it into the offload flowtable
		"\nmr_wait phy0-ap0-1\n", "\nmr_wait phy1-ap0-1\n", "-ge 660 ]"} {
		if !strings.Contains(post, s) {
			t.Errorf("wifi-post.sh missing %q", s)
		}
	}
	if strings.Contains(post, "phy1-ap0-1/brport") || strings.Contains(post, "mr_wait phy0-ap0\n") {
		t.Error("non-isolated SSID got bridge isolation, or a waitless primary is waited for")
	}
	if strings.Index(post, "mr_wait phy0-ap0-1") > strings.Index(post, "mr_wait phy1-ap0-1") ||
		strings.Index(post, "mr_wait phy1-ap0-3 &&") > strings.Index(post, "mr_wait phy0-ap0-1") {
		t.Error("isolated BSSes first, and 2.4 GHz (never DFS) before 5 GHz")
	}
	ns := got[GenDir+"/network.sh"]
	for _, s := range []string{"mr_apmac() {", `[ -n "$p" ] && mr_apmac "$p" phy0-ap0 4`, `[ -n "$p" ] && mr_apmac "$p" phy1-ap0 8`} {
		if !strings.Contains(ns, s) {
			t.Errorf("network.sh missing %q", s)
		}
	}
	nft := renderNft(c, func(string) bool { return true })
	for _, d := range []string{`"phy1-ap0-3"`, `"phy0-ap0-1"`} {
		if !strings.Contains(nft, d) {
			t.Errorf("flowtable missing %s", d)
		}
	}
}

// mr_apmac (network.sh) runs under a real sh against a fake sysfs and a fake `ip`: the base address must be
// aligned, locally administered, different per band and above the factory address (a bridge without a fixed
// MAC takes its lowest port's; an AP address below the wired ports' would become the LAN MAC).
func TestWifiAPMac(t *testing.T) {
	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skip("no sh")
	}
	var fn string
	for _, l := range strings.Split(renderMap(t, wifiLabConfig(t))[GenDir+"/network.sh"], "\n") {
		if strings.HasPrefix(l, "mr_apmac() {") {
			fn = l
		}
	}
	if fn == "" {
		t.Fatal("no mr_apmac in network.sh")
	}
	dir := t.TempDir()
	fn = strings.NewReplacer("/sys/class/ieee80211/", dir+"/phy/", "/sys/class/net/", dir+"/net/").Replace(fn)
	os.MkdirAll(dir+"/bin", 0755)
	os.WriteFile(dir+"/bin/ip", []byte("#!/bin/sh\necho \"$*\" >> \""+dir+"/ip.log\"\n"), 0755)
	for _, tc := range []struct{ factory, cur, x, want string }{
		{"a4:a9:30:6e:2b:8a", "a4:a9:30:6e:2b:8a", "4", "aa:a9:30:6e:2b:88"}, // 2.4 GHz
		{"a4:a9:30:6e:2b:8b", "a4:a9:30:6e:2b:8b", "8", "ae:a9:30:6e:2b:88"}, // 5 GHz: other band, other block
		{"a6:00:00:00:00:07", "a6:00:00:00:00:07", "4", "aa:00:00:00:00:04"}, // factory already local
		{"a4:a9:30:6e:2b:8a", "aa:a9:30:6e:2b:88", "4", ""},                  // already set: no change
	} {
		os.RemoveAll(dir + "/phy")
		os.RemoveAll(dir + "/net")
		os.Remove(dir + "/ip.log")
		os.MkdirAll(dir+"/phy/phyx", 0755)
		os.MkdirAll(dir+"/net/phy0-ap0", 0755)
		os.WriteFile(dir+"/phy/phyx/macaddress", []byte(tc.factory+"\n"), 0644)
		os.WriteFile(dir+"/net/phy0-ap0/address", []byte(tc.cur+"\n"), 0644)
		cmd := exec.Command(sh, "-c", fn+"\nmr_apmac phyx phy0-ap0 "+tc.x)
		cmd.Env = append(os.Environ(), "PATH="+dir+"/bin:"+os.Getenv("PATH"))
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("mr_apmac: %v %s", err, out)
		}
		log, _ := os.ReadFile(dir + "/ip.log")
		want := ""
		if tc.want != "" {
			want = "link set phy0-ap0 down\nlink set phy0-ap0 address " + tc.want + "\n"
			if tc.want <= tc.factory {
				t.Errorf("test case: %s is not above %s", tc.want, tc.factory)
			}
		}
		if string(log) != want {
			t.Errorf("factory %s x=%s: ip calls %q, want %q", tc.factory, tc.x, log, want)
		}
	}
}

// loadKeys reads mr/testdata/hostapd-2.11.keys (exact keys + "prefix*" entries).
func loadKeys(t *testing.T) (map[string]bool, []string) {
	t.Helper()
	b, err := os.ReadFile("testdata/hostapd-2.11.keys")
	if err != nil {
		t.Fatal(err)
	}
	keys := map[string]bool{}
	var pre []string
	for _, l := range strings.Split(string(b), "\n") {
		switch {
		case l == "" || strings.HasPrefix(l, "#"):
		case strings.HasSuffix(l, "*"):
			pre = append(pre, strings.TrimSuffix(l, "*"))
		default:
			keys[l] = true
		}
	}
	if len(keys) < 300 || !keys["noscan"] || !keys["ssid2"] {
		t.Fatalf("key list looks wrong (%d keys)", len(keys))
	}
	return keys, pre
}

// Every key mr writes into a hostapd config must be one upstream hostapd 2.11 (+ noscan patch) accepts;
// an unknown key makes hostapd refuse to start and takes the whole radio down.
func TestHostapdKeysUpstream(t *testing.T) {
	keys, pre := loadKeys(t)
	for name, c := range map[string]*Config{"home": testConfig(t), "lab": wifiLabConfig(t)} {
		for _, r := range c.WiFi.Radios {
			s, err := renderHostapd(c, r)
			if err != nil {
				t.Fatal(err)
			}
		lines:
			for i, l := range strings.Split(s, "\n") {
				if l == "" || strings.HasPrefix(l, "#") {
					continue
				}
				k, _, ok := strings.Cut(l, "=")
				if !ok {
					t.Errorf("%s %s:%d: not key=value: %q", name, r.Phy, i+1, l)
					continue
				}
				if keys[k] {
					continue
				}
				for _, p := range pre {
					if strings.HasPrefix(k, p) {
						continue lines
					}
				}
				t.Errorf("%s %s:%d: key %q is not accepted by hostapd 2.11", name, r.Phy, i+1, k)
			}
		}
	}
}

func TestWifiValidateRejects(t *testing.T) {
	cases := []struct {
		edit func(c *Config)
		want string
	}{
		{func(c *Config) {
			for i := 0; i < 4; i++ {
				c.WiFi.Radios[0].SSIDs = append(c.WiFi.Radios[0].SSIDs, SSID{SSID: "x" + string(rune('a'+i)), Encryption: "none"})
			}
		}, "1-4 SSIDs per radio"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[1].PMF = "optional" }, "WPA3-SAE always requires"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[0].PMF = "disabled" }, "use optional or required"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[3].PMF = "required" }, "needs encryption"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[0].PMF = "on" }, "disabled|optional|required"},
		{func(c *Config) { c.WiFi.Radios[0].SSIDs[1].MACList = nil }, "lock every device out"},
		{func(c *Config) { c.WiFi.Radios[0].SSIDs[1].MACList = []string{"aa:bb:cc:00:00:0g"} }, "invalid MAC"},
		{func(c *Config) {
			c.WiFi.Radios[0].SSIDs[1].MACList = []string{"aa:bb:cc:00:00:01", "AA:BB:CC:00:00:01"}
		}, "listed twice"},
		{func(c *Config) { c.WiFi.Radios[0].SSIDs[1].MACFilter = "block" }, "allow|deny"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[2].MaxClients = -1 }, "max_clients"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[2].MaxClients = 5000 }, "max_clients"},
		{func(c *Config) { c.secrets["wifi_wpa3_key"] = "password|id=evil" }, `must not contain "|id="`},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[1].SSID = "MiniRouter-5G" }, "twice on this radio"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[1].SSID = "bad\nname" }, "control characters"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[1].SSID = strings.Repeat("x", 33) }, "1-32 bytes"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[1].Key = "webui_password" }, "secret name"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[1].Key = "../etc" }, "secret name"},
		{func(c *Config) { c.WiFi.Radios[1].SSIDs[2].Network = "nope" }, "unknown network"},
		{func(c *Config) { c.WiFi.Radios[1].BeaconInt = 5 }, "beacon_int"},
		{func(c *Config) { c.WiFi.Radios[1].DTIM = 300 }, "dtim_period"},
		{func(c *Config) { c.WiFi.Radios[0].HTMode = "HE80" }, "2.4 GHz supports"},
		{func(c *Config) { c.WiFi.Radios[1].Band = "2g" }, "only one radio per band"},
		{func(c *Config) { c.secrets["wifi_guest_key"] = "short" }, "8-63 char"},
		{func(c *Config) { c.secrets["wifi_guest_key"] = "tab\there-long" }, "printable ASCII"},
	}
	for _, tc := range cases {
		c := wifiLabConfig(t)
		tc.edit(c)
		errs := strings.Join(c.Validate(), "\n")
		if !strings.Contains(errs, tc.want) {
			t.Errorf("want error containing %q, got:\n%s", tc.want, errs)
		}
	}
}

func TestWifiNoCountryNo80211h(t *testing.T) {
	c := testConfig(t)
	c.WiFi.Country = ""
	s, err := renderHostapd(c, c.WiFi.Radios[1])
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(s, "ieee80211h=") || strings.Contains(s, "ieee80211d=") {
		t.Error("802.11h/d without a country code makes hostapd refuse the config")
	}
}

func TestParseStations(t *testing.T) {
	out := "Station 02:E3:50:10:6A:63 (on phy0-ap0)\n\tinactive time:\t10 ms\n\trx bytes:\t123456789\n\trx packets:\t12\n" +
		"\ttx bytes:\t987654321\n\ttx packets:\t34\n\ttx retries:\t5\n\ttx failed:\t1\n" +
		"\tsignal:  \t-29 [-35, -38, -39, -31] dBm\n\ttx bitrate:\t68.8 MBit/s HE-MCS 3 HE-NSS 2 HE-GI 0 HE-DCM 0\n" +
		"\trx bitrate:\t229.4 MBit/s HE-MCS 9 HE-NSS 2 HE-GI 0 HE-DCM 0\n\tMFP:\t\tyes\n\tbeacon interval:100\n" +
		"\tconnected time:\t465 seconds\n\tassociated at [boottime]:\t1.000s\n" +
		"Station 02:d9:44:2f:7a:85 (on phy0-ap0)\n\tsignal:  \t-68 dBm\n\tconnected time:\t10 seconds\n"
	st := parseStations(out, "phy0-ap0")
	if len(st) != 2 {
		t.Fatalf("got %d stations", len(st))
	}
	s := st[0]
	if s.MAC != "02:e3:50:10:6a:63" || s.SignalDBm != -29 || s.TxMbps != 68.8 || s.RxMbps != 229.4 || s.RxBytes != 123456789 ||
		s.TxBytes != 987654321 || s.TxRetries != 5 || s.TxFailed != 1 || s.Connected != 465 || s.Inactive != 10 || !s.MFP ||
		s.Signal != "-29 [-35, -38, -39, -31] dBm" {
		t.Errorf("parsed %+v", s)
	}
	if st[1].SignalDBm != -68 || st[1].Connected != 10 {
		t.Errorf("parsed %+v", st[1])
	}
}

func TestParseSurvey(t *testing.T) {
	out := "Survey data from phy1-ap0\n\tfrequency:\t\t\t5180 MHz [in use]\n\tnoise:\t\t\t\t-92 dBm\n" +
		"\tchannel active time:\t\t1000 ms\n\tchannel busy time:\t\t250 ms\n\tchannel receive time:\t\t200 ms\n\tchannel transmit time:\t\t30 ms\n" +
		"Survey data from phy1-ap0\n\tfrequency:\t\t\t5200 MHz\n" + // never visited: dropped
		"Survey data from phy1-ap0\n\tfrequency:\t\t\t5745 MHz\n\tnoise:\t\t\t\t-95 dBm\n\tchannel active time:\t\t50 ms\n\tchannel busy time:\t\t5 ms\n"
	s := parseSurvey(out)
	if len(s) != 2 {
		t.Fatalf("got %+v", s)
	}
	if s[0].Channel != 36 || !s[0].InUse || s[0].Noise != -92 || s[0].ActiveMs != 1000 || s[0].BusyMs != 250 || s[0].RxMs != 200 || s[0].TxMs != 30 {
		t.Errorf("parsed %+v", s[0])
	}
	if s[1].Channel != 149 || s[1].InUse {
		t.Errorf("parsed %+v", s[1])
	}
	for f, ch := range map[int]int{2412: 1, 2462: 11, 2484: 14, 5180: 36, 5825: 165, 5955: 1} {
		if freqChan(f) != ch {
			t.Errorf("freqChan(%d) = %d, want %d", f, freqChan(f), ch)
		}
	}
}

func TestParseScan(t *testing.T) {
	out := "BSS 11:22:33:44:55:66(on phy1-ap0)\n\tlast seen: 12.345s [boottime]\n\tTSF: 1 usec (0d, 00:00:00)\n\tfreq: 5180\n" +
		"\tbeacon interval: 100 TUs\n\tcapability: ESS Privacy SpectrumMgmt (0x1511)\n\tsignal: -71.00 dBm\n\tlast seen: 256 ms ago\n" +
		"\tInformation elements from Probe Response frame:\n\tSSID: \\xe5\\xae\\xb6 Home\\x20\n" +
		"\tBSS Load:\n\t\t * station count: 3\n\t\t * channel utilisation: 51/255\n" +
		"\tHT operation:\n\t\t * primary channel: 36\n\t\t * secondary channel offset: above\n" +
		"\tRSN:\t * Version: 1\n\t\t * Group cipher: CCMP\n\t\t * Pairwise ciphers: CCMP\n\t\t * Authentication suites: PSK SAE\n" +
		"\tVHT operation:\n\t\t * channel width: 1 (80 MHz)\n\t\t * center freq segment 1: 42\n\t\t * center freq segment 2: 50\n" +
		"\tHE capabilities:\n\t\tHE MAC Capabilities (0x0000):\n" +
		"\tInformation elements from Beacon frame:\n\tSSID: other\n" +
		"BSS aa:bb:cc:dd:ee:ff(on phy1-ap0) -- associated\n\tfreq: 2437\n\tcapability: ESS (0x0401)\n\tsignal: -50.00 dBm\n\tSSID: \n" +
		"\tHT operation:\n\t\t * primary channel: 6\n\t\t * secondary channel offset: no secondary\n" +
		"BSS 00:11:22:33:44:55(on phy1-ap0)\n\tfreq: 5745\n\tcapability: ESS Privacy (0x0011)\n\tsignal: -80.00 dBm\n\tSSID: corp\n" +
		"\tRSN:\t * Version: 1\n\t\t * Authentication suites: IEEE 802.1X\n\tVHT operation:\n\t\t * channel width: 2 (160 MHz)\n"
	n := parseScan(out)
	if len(n) != 3 {
		t.Fatalf("got %d: %+v", len(n), n)
	}
	// sorted by signal
	open, home, corp := n[0], n[1], n[2]
	if home.BSSID != "11:22:33:44:55:66" || home.SSID != "家 Home " || home.Channel != 36 || home.Width != 160 || home.Security != "WPA2/WPA3" ||
		home.Stations != 3 || home.Util != 20 || home.Signal != -71 || home.Seen != 256 || home.Standard != "ax" || home.Band != "5g" {
		t.Errorf("home: %+v", home)
	}
	if open.SSID != "" || open.Security != "open" || open.Width != 20 || open.Channel != 6 || open.Stations != -1 || open.Band != "2g" {
		t.Errorf("open: %+v", open)
	}
	if corp.Security != "802.1X" || corp.Width != 160 || corp.Channel != 149 {
		t.Errorf("corp: %+v", corp)
	}
}

func TestParseHostapdStatus(t *testing.T) {
	st := "state=ENABLED\nphy=phy1\nfreq=5180\nhw_mode=a\ncountry_code=PA\ncac_time_seconds=60\ncac_time_left_seconds=N/A\n" +
		"channel=36\nsecondary_channel=1\nieee80211n=1\nieee80211ac=1\nieee80211ax=1\nhe_oper_chwidth=2\nvht_oper_chwidth=2\n" +
		"bss[0]=phy1-ap0\nbssid[0]=a6:a9:30:6e:2b:8c\nssid[0]=MiniRouter-5G\nnum_sta[0]=3\n" +
		"bss[1]=phy1-ap0-1\nbssid[1]=a6:a9:30:6e:2b:8d\nssid[1]=Guest\nnum_sta[1]=1\n"
	op := parseHostapdStatus(st)
	if op.State != "ENABLED" || op.Channel != 36 || op.Width != 160 || len(op.BSS) != 2 || op.BSS[1].Ifname != "phy1-ap0-1" || op.BSS[0].Clients != 3 {
		t.Errorf("parsed %+v", op)
	}
	op = parseHostapdStatus("state=DFS\nhw_mode=g\nchannel=6\nsecondary_channel=-1\ncac_time_left_seconds=42\nhe_oper_chwidth=0\n")
	if op.Width != 40 || op.CACLeft != 42 {
		t.Errorf("parsed %+v", op)
	}
}

// fakeHostapd answers control-socket commands like hostapd does for the given BSS.
func fakeHostapd(t *testing.T, dir, ifname string, reply func(cmd string) string) {
	t.Helper()
	c, err := net.ListenUnixgram("unixgram", &net.UnixAddr{Name: filepath.Join(dir, ifname), Net: "unixgram"})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { c.Close() })
	go func() {
		buf := make([]byte, 4096)
		for {
			n, from, err := c.ReadFromUnix(buf)
			if err != nil {
				return
			}
			c.WriteToUnix([]byte(reply(string(buf[:n]))), from)
		}
	}()
}

func TestKickViaControlSocket(t *testing.T) {
	dir := t.TempDir()
	old := hostapdCtrlDir
	hostapdCtrlDir = dir
	defer func() { hostapdCtrlDir = old }()
	var deauthed []string
	for _, ifn := range []string{"phy1-ap0", "phy1-ap0-1", "phy1-ap0-2", "phy1-ap0-3", "phy0-ap0", "phy0-ap0-1", "phy0-ap0-2"} {
		ifn := ifn
		fakeHostapd(t, dir, ifn, func(cmd string) string {
			switch {
			case cmd == "STATUS" && ifn == "phy1-ap0":
				return "state=ENABLED\nhw_mode=a\nchannel=36\nsecondary_channel=1\nhe_oper_chwidth=2\nbss[0]=phy1-ap0\nbssid[0]=02:00:00:00:00:00\nnum_sta[0]=0\nbss[1]=phy1-ap0-1\nnum_sta[1]=0\nbss[2]=phy1-ap0-2\nnum_sta[2]=2\nbss[3]=phy1-ap0-3\nnum_sta[3]=0\n"
			case cmd == "STATUS":
				return "state=ENABLED\nhw_mode=g\nchannel=6\nbss[0]=phy0-ap0\nnum_sta[0]=1\nbss[1]=phy0-ap0-1\nnum_sta[1]=0\nbss[2]=phy0-ap0-2\nnum_sta[2]=0\n"
			case cmd == "STA 02:c3:06:d6:7f:8a" && ifn == "phy1-ap0-2":
				return "02:c3:06:d6:7f:8a\nflags=[AUTH][ASSOC][AUTHORIZED]\n"
			case strings.HasPrefix(cmd, "STA "):
				return "FAIL\n"
			case strings.HasPrefix(cmd, "DEAUTHENTICATE "):
				deauthed = append(deauthed, ifn+" "+strings.TrimPrefix(cmd, "DEAUTHENTICATE "))
				return "OK\n"
			}
			return "UNKNOWN COMMAND\n"
		})
	}
	c := wifiLabConfig(t)
	ifn, err := kick(c, "02:C3:06:D6:7F:8A", "")
	if err != nil || ifn != "phy1-ap0-2" || len(deauthed) != 1 || deauthed[0] != "phy1-ap0-2 02:c3:06:d6:7f:8a" {
		t.Fatalf("kick: %q %v %v", ifn, err, deauthed)
	}
	if _, err := kick(c, "02:c3:06:d6:7f:8a", "phy1-ap0"); err != errNotConnected {
		t.Errorf("kick on the wrong BSS: %v", err)
	}
	for _, bad := range [][2]string{{"02:aa:bb:cc:dd", ""}, {"02:c3:06:d6:7f:8a;reboot", ""}, {"02:c3:06:d6:7f:8a", "../../etc/x"}, {"02:c3:06:d6:7f:8a", "eth0"}} {
		if _, err := kick(c, bad[0], bad[1]); err == nil || !strings.HasPrefix(err.Error(), "bad ") {
			t.Errorf("kick(%q, %q) = %v, want rejection", bad[0], bad[1], err)
		}
	}
	if len(wifiNotReady(c)) != 0 {
		t.Errorf("not ready: %v", wifiNotReady(c))
	}
	st := wifiStatusAll(c)
	if len(st) != 7 || !st[5].Up || st[5].Clients != 2 || st[5].SSID != "MiniRouter-Guest" || st[5].HTMode != "160MHz" || st[5].Network != "guest" {
		b, _ := json.Marshal(st)
		t.Errorf("status: %s", b)
	}
	// hostapd down: not ready, reported as down
	hostapdCtrlDir = t.TempDir()
	if bad := wifiNotReady(c); len(bad) != 2 || !strings.Contains(bad[0], "not answering") {
		t.Errorf("want 2 radios not answering, got %v", bad)
	}
	start := time.Now()
	if st := wifiStatusAll(c); st[0].Up || time.Since(start) > 3*time.Second {
		t.Error("status must report down quickly when hostapd is not running")
	}
}

func TestWifiAPIMethods(t *testing.T) {
	for _, a := range []string{"wifi.kick", "wifi.scan"} {
		var h func(apiReq) apiResp
		for _, m := range modules {
			if f, ok := m.API[a]; ok {
				h = f
			}
		}
		if h == nil {
			t.Fatalf("%s not registered", a)
		}
		if r := h(apiReq{method: "GET", action: a}); r.status != 405 {
			t.Errorf("%s via GET: status %d, want 405", a, r.status)
		}
	}
	if r := apiScan(apiReq{method: "POST", body: []byte(`{"phy":"phy1;reboot"}`)}); r.status != 400 {
		t.Errorf("bad phy accepted: %d", r.status)
	}
	if r := apiKick(apiReq{method: "POST", body: []byte(`not json`)}); r.status != 400 {
		t.Errorf("bad body accepted: %d", r.status)
	}
}

func TestWifiGenericProfile(t *testing.T) {
	c := testConfig(t)
	for i := range c.WiFi.Radios {
		c.WiFi.Radios[i].Profile = "generic"
	}
	c.WiFi.Radios[1].HTMode = "VHT80"
	if errs := c.Validate(); len(errs) > 0 {
		t.Fatal(errs)
	}
	g := renderMap(t, c)
	two, five := g["/etc/hostapd/hostapd-phy0.conf"], g["/etc/hostapd/hostapd-phy1.conf"]
	for _, bad := range []string{"noscan=", "[LDPC]", "he_mu_edca", "ieee80211ax=1"} {
		if strings.Contains(five, bad) {
			t.Errorf("generic VHT80 5 GHz config has %q", bad)
		}
	}
	for _, want := range []string{"ieee80211ac=1", "vht_oper_chwidth=1", "vht_oper_centr_freq_seg0_idx=42", "ht_capab=[HT40+]\n"} {
		if !strings.Contains(five, want) {
			t.Errorf("generic 5 GHz config lacks %q:\n%s", want, five)
		}
	}
	if strings.Contains(two, "noscan=") || !strings.Contains(two, "ieee80211ax=1") {
		t.Errorf("generic 2.4 GHz HE40: noscan must be off, ax on:\n%s", two)
	}
	c.WiFi.Radios[0].HTMode = "VHT40"
	if !strings.Contains(strings.Join(c.Validate(), "\n"), "2.4 GHz supports") {
		t.Error("VHT on 2.4 GHz accepted")
	}
}
