package main

// fw module: the nftables ruleset (table inet mr). renderNft is the skeleton every module hooks
// into (nftHooks in module.go, each emitted at its documented place); fwNft is this module's own
// hook output. Everything rendered here comes from validated config (fwValidate) and is
// normalized (addresses re-printed by net, names restricted to reLabel) before it is written.
//
// Chain order (filter):
//
//	input:   [pause] → [access: proxy bypass] → ct state → lo → [rules → router] → lan accept → guest
//	         (dhcp/dns/icmp) → synflood → wan ping → required ICMPv6 / DHCPv6 / MLD / IGMP → hook input
//	         (open ports, tailscale, …) → [log] → counted wan drop → policy drop
//	forward: [pause] → hook forward_first (policy route fallback: drop) → [access control] → flow
//	         offload → ct state → hook forward_early (traffic rules, …) → lan accept → guest→wan →
//	         dnat accept → hook forward (IPv6 pinholes, …) → ICMPv6 → drop
//
// [pause] (`mr pause`, mod_dev_pause.go) is runtime state, not config: fwLoad inserts it in the same
// transaction while a pause is active, so it is never in the rendered file (nor in `mr plan`).

import (
	"encoding/json"
	"fmt"
	"net"
	"os"
	"sort"
	"strings"
)

// renderNft builds the whole ruleset. exists() reports whether a netdev is present right now:
// nft refuses flowtables that reference missing devices, and PPPoE / WiFi netdevs come and go,
// so the ruleset is re-rendered by the ppp and hostapd hooks.
func renderNft(c *Config, exists func(string) bool) string {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	r := func(f string, a ...any) { fmt.Fprintf(&b, "\t\t"+f+"\n", a...) } // one rule line
	hook := func(name string) { emitNft(c, name, &b, exists) }
	fw := &c.Firewall
	clk := fwClockFor(c)
	trustedSet := quoteList(fwZoneIfs(c, "lan"))
	wanSet := "{ " + quoteList(c.WANIfnames()) + " }"
	hasWAN := len(c.WAN) > 0 // mode bypass / ap: none (an empty anonymous set is a syntax error)
	ctState := "ct state vmap { established : accept, related : accept, invalid : drop }"
	if !on(fw.DropInvalid) {
		ctState = "ct state vmap { established : accept, related : accept }"
	}

	guests := strings.Join(fwZoneIfs(c, "guest"), " ")
	if guests == "" {
		guests = "-"
	}
	w("# generated by mr — edit router.yaml instead")
	w("# zones: lan (trusted) = %s | guest (internet only) = %s | wan = %s",
		strings.Join(fwZoneIfs(c, "lan"), " "), guests, strings.Join(c.WANIfnames(), " "))
	w("table inet mr")
	w("delete table inet mr")
	w("table inet mr {")
	w("\tset lan6 {\n\t\ttype ipv6_addr\n\t\tflags interval\n\t\telements = { fe80::/10, ff00::/8 }\n\t}")

	haveFT := false
	if fw.Offload != "off" && !c.apMode() { // an AP routes nothing
		var devs []string
		for _, m := range modules {
			if m.FlowDevs != nil {
				devs = append(devs, m.FlowDevs(c)...)
			}
		}
		var present []string
		seen := map[string]bool{}
		for _, d := range devs {
			if !seen[d] && exists(d) {
				present = append(present, d)
				seen[d] = true
			}
		}
		sort.Strings(present)
		if len(present) > 0 {
			haveFT = true
			w("\tflowtable ft {\n\t\thook ingress priority filter\n\t\tdevices = { %s }", quoteList(present))
			if fw.Offload == "hardware" {
				w("\t\tflags offload")
			}
			// write fast-path / PPE bytes back to conntrack so per-device traffic (mon) stays accurate
			w("\t\tcounter")
			w("\t}")
		}
	}
	hook("defs")

	// ---- filter ----
	w("\tchain input {\n\t\ttype filter hook input priority filter; policy drop;")
	// before ct state: a transparent proxy's connections of a blocked device are cut too, not only new ones
	for _, l := range fwAccessInput(c, clk) {
		r("%s", l)
	}
	r("%s", ctState)
	r("iif lo accept")
	for _, x := range fw.Rules {
		if on(x.Enabled) && x.Dest == "router" {
			for _, l := range fwRuleLines(c, x, clk) {
				r("%s", l)
			}
		}
	}
	r("iifname { %s } accept", trustedSet)
	// guest-zone networks reach the router only for DHCP / DNS / ICMP
	for _, br := range fwZoneIfs(c, "guest") {
		r("iifname %q meta l4proto { tcp, udp } th dport { 53, 67, 547 } accept", br)
		r("iifname %q meta l4proto { icmp, ipv6-icmp } accept", br)
		r("iifname %q drop", br)
	}
	// from here on: WAN side (and anything not in a zone)
	if fw.SynFlood {
		r("tcp flags & (fin|syn|rst|ack) == syn limit rate over 50/second burst 100 packets drop")
	}
	if on(fw.WANPing) {
		r("icmp type echo-request limit rate 20/second accept")
	}
	// ICMPv6 the protocols need (RFC 4890) is always allowed; echo is rate limited
	r("meta nfproto ipv6 icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } accept")
	r("meta nfproto ipv6 icmpv6 type echo-request limit rate 20/second accept")
	r("ip6 saddr fe80::/10 icmpv6 type { mld-listener-query, mld-listener-report, mld-listener-done, mld2-listener-report } accept")
	r("ip6 saddr fc00::/6 ip6 daddr fc00::/6 udp dport 546 accept comment \"dhcpv6-client\"")
	var dhcpWAN []string
	for _, x := range c.WAN {
		if x.Proto == "dhcp" {
			dhcpWAN = append(dhcpWAN, x.Ifname())
		}
	}
	if len(dhcpWAN) > 0 {
		r("iifname { %s } meta nfproto ipv4 udp sport 67 udp dport 68 accept comment \"dhcp-client\"", quoteList(dhcpWAN))
	}
	r("meta l4proto igmp accept")
	hook("input")
	if fw.LogDrops && hasWAN {
		r("iifname %s limit rate 10/minute burst 20 packets log prefix \"mr-drop wan-in: \" level info", wanSet)
	}
	if hasWAN {
		r("iifname %s counter drop comment \"wan-in-drop\"", wanSet)
	}
	w("\t}")

	w("\tchain forward {\n\t\ttype filter hook forward priority filter; policy drop;")
	hook("forward_first")
	acc := fwAccessForward(c, clk)
	for _, l := range acc {
		r("%s", l)
	}
	if haveFT {
		if len(acc) > 0 {
			// controlled devices are never offloaded, so a schedule also cuts their existing connections
			r("meta nfproto ipv4 meta l4proto { tcp, udp } ct state established ip saddr != @ac_4 ip daddr != @ac_4 flow add @ft")
			r("meta nfproto ipv6 meta l4proto { tcp, udp } ct state established ip6 saddr != @ac_6 ip6 daddr != @ac_6 flow add @ft")
		} else {
			r("meta l4proto { tcp, udp } ct state established flow add @ft")
		}
	}
	r("%s", ctState)
	hook("forward_early")
	r("iifname { %s } accept", trustedSet)
	// guest zone: internet only (WAN), never other LAN-side networks
	for _, br := range fwZoneIfs(c, "guest") {
		r("iifname %q oifname { %s } accept", br, quoteList(c.WANIfnames()))
	}
	r("ct status dnat accept")
	hook("forward")
	r("meta nfproto ipv6 icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, echo-request } accept")
	w("\t}")

	w("\tchain output {\n\t\ttype filter hook output priority filter; policy accept;")
	hook("output")
	w("\t}")

	// ---- mangle ----
	w("\tchain mangle_forward {\n\t\ttype filter hook forward priority mangle; policy accept;")
	if hasWAN {
		r("oifname %s tcp flags syn / syn,rst tcp option maxseg size set rt mtu", wanSet)
		r("iifname %s tcp flags syn / syn,rst tcp option maxseg size set rt mtu", wanSet)
	}
	w("\t}")
	w("\tchain mark_pre {\n\t\ttype filter hook prerouting priority mangle + 1; policy accept;")
	hook("mark")
	w("\t}")

	// ---- nat ----
	w("\tchain dstnat {\n\t\ttype nat hook prerouting priority dstnat; policy accept;")
	hook("dstnat")
	w("\t}")
	w("\tchain srcnat {\n\t\ttype nat hook postrouting priority srcnat; policy accept;")
	hook("srcnat")
	w("\t}")
	w("}")
	return b.String()
}

// fwNft: this module's own rules at the shared hook points.
func fwNft(c *Config, hook string, n *Nft) {
	fw := &c.Firewall
	fwd := fwEnabledForwards(c)
	switch hook {
	case "defs":
		if len(fwAccessEntries(c)) > 0 {
			// learned addresses of access-controlled devices (see fwAccessForward)
			n.W("set ac_4 { type ipv4_addr; size 4096; flags dynamic,timeout; timeout 6h; }")
			n.W("set ac_6 { type ipv6_addr; size 4096; flags dynamic,timeout; timeout 6h; }")
			for _, i := range fwAccessEntries(c) {
				n.W("set ac%d_4 { type ipv4_addr; size 1024; flags dynamic,timeout; timeout 6h; }", i)
				n.W("set ac%d_6 { type ipv6_addr; size 1024; flags dynamic,timeout; timeout 6h; }", i)
			}
		}
		if len(fwd) > 0 {
			// NAT loopback: trusted LAN clients reaching a forwarded port on a WAN address
			iif, routers := fwReflectMatch(c)
			n.W("chain reflect {\n\t\ttype nat hook prerouting priority dstnat + 1; policy accept;")
			for _, f := range fwd {
				for _, p := range f.Proto {
					n.W("\tiifname %s fib daddr type local ip daddr != %s %s dport %s dnat ip to %s", iif, routers, p, nftPorts(f.Port), fwdTo(c, f))
				}
			}
			n.W("}")
		}
	case "input":
		for _, o := range fw.Open {
			if !on(o.Enabled) {
				continue
			}
			ports, _ := fwPortList(o.Port)
			for _, src := range fwSrcMatches(o.SrcIP) {
				for _, p := range o.Proto {
					n.W("iifname %s %s%s dport %s accept comment %q", fwWANSet(c, o.WAN), src, p, nftSet(ports), o.Name)
				}
			}
		}
	case "forward_early":
		for _, x := range fw.Rules {
			if on(x.Enabled) && x.Dest != "router" {
				for _, l := range fwRuleLines(c, x, fwClockFor(c)) {
					n.W("%s", l)
				}
			}
		}
	case "forward":
		// IPv6 pinholes: WAN → LAN-side host by interface identifier (survives prefix changes)
		lanSide := "{ " + quoteList(c.LANBridges()) + " }"
		for _, a := range fw.IPv6Allow {
			if !on(a.Enabled) {
				continue
			}
			ports, _ := fwPortList(a.Port)
			for _, src := range fwSrcMatches(a.SrcIP) {
				for _, p := range a.Proto {
					n.W("iifname %s oifname %s %sip6 daddr & ::ffff:ffff:ffff:ffff == %s %s dport %s counter accept comment %q",
						fwWANSet(c, a.WAN), lanSide, src, a.iid(), p, nftSet(ports), "v6in:"+a.Name)
				}
			}
		}
	case "dstnat":
		for _, f := range fwd {
			src := ""
			if v4, _, _ := fwAddrs(f.SrcIP); len(v4) > 0 {
				src = "ip saddr " + nftSet(v4) + " "
			}
			for _, p := range f.Proto {
				n.W("iifname %s %s%s dport %s dnat ip to %s comment %q", fwWANSet(c, f.WAN), src, p, nftPorts(f.Port), fwdTo(c, f), f.Name)
			}
		}
	case "srcnat":
		if len(c.WAN) > 0 {
			n.W("oifname { %s } meta nfproto ipv4 masquerade", quoteList(c.WANIfnames()))
		}
		if c.bypassNAT() {
			// mode bypass (all / selected): the main router answers this box, so its replies come back here
			n.W("iifname %q oifname %q meta nfproto ipv4 masquerade comment \"bypass-nat\"", c.LAN.Bridge, c.LAN.Bridge)
		}
		if len(fwd) > 0 {
			// NAT loopback inside one subnet: the target must answer via the router
			for _, ln := range c.LANNets() {
				if _, nn, err := net.ParseCIDR(ln.IPv4); err == nil && ln.Zone == "lan" {
					n.W("iifname %q oifname %q ct status dnat ip saddr %s masquerade comment \"nat-reflection\"", ln.Bridge, ln.Bridge, nn.String())
				}
			}
		}
	}
}

func fwEnabledForwards(c *Config) []Forward {
	var out []Forward
	for _, f := range c.Firewall.Forwards {
		if on(f.Enabled) {
			out = append(out, f)
		}
	}
	return out
}

// fwdTo: the DNAT target (a device name resolves to its ip), with the port when it differs.
func fwdTo(c *Config, f Forward) string {
	to := devHostIP(c, f.To)
	if f.ToPort != "" && f.ToPort != f.Port {
		return fmt.Sprintf("%s:%s", to, nftPorts(f.ToPort))
	}
	return to
}

// fwReflectMatch: input interfaces and router addresses for the NAT loopback chain.
func fwReflectMatch(c *Config) (iif, routers string) {
	var brs, ips []string
	for _, ln := range c.LANNets() {
		ip, _, err := net.ParseCIDR(ln.IPv4)
		if err != nil {
			continue
		}
		ips = append(ips, ip.String())
		if ln.Zone == "lan" {
			brs = append(brs, fmt.Sprintf("%q", ln.Bridge))
		}
	}
	return nftSet(brs), nftSet(ips)
}

// fwWANSet: the WAN interfaces of a subset (all WANs when empty), always as an anonymous set.
func fwWANSet(c *Config, subset []string) string {
	if len(subset) == 0 {
		return "{ " + quoteList(c.WANIfnames()) + " }"
	}
	var ifs []string
	for _, x := range c.WAN {
		for _, s := range subset {
			if x.Name == s {
				ifs = append(ifs, x.Ifname())
			}
		}
	}
	return "{ " + quoteList(ifs) + " }"
}

// fwSrcMatches: one source match per address family ("" = any source), each ending in a space.
func fwSrcMatches(src []string) []string {
	if len(src) == 0 {
		return []string{""}
	}
	v4, v6, _ := fwAddrs(src)
	var out []string
	if len(v4) > 0 {
		out = append(out, "ip saddr "+nftSet(v4)+" ")
	}
	if len(v6) > 0 {
		out = append(out, "ip6 saddr "+nftSet(v6)+" ")
	}
	return out
}

// nftSet renders one element as-is and several as an anonymous set.
func nftSet(xs []string) string {
	if len(xs) == 1 {
		return xs[0]
	}
	return "{ " + strings.Join(xs, ", ") + " }"
}

func lowerAll(xs []string) []string {
	out := make([]string, len(xs))
	for i, x := range xs {
		out[i] = strings.ToLower(x)
	}
	return dedup(out)
}

// fwRuleLines renders one traffic rule (possibly several nft rules: one per address family and
// per time-window group; with log, a rate-limited log rule precedes each verdict rule).
func fwRuleLines(c *Config, x FwRule, clk fwClock) []string {
	var base []string
	if z := x.Src; z == "lan" || z == "guest" || z == "wan" {
		base = append(base, "iifname { "+quoteList(fwZoneIfs(c, z))+" }")
	}
	if z := x.Dest; z == "lan" || z == "guest" || z == "wan" {
		base = append(base, "oifname { "+quoteList(fwZoneIfs(c, z))+" }")
	}
	if len(x.SrcMAC) > 0 {
		base = append(base, "ether saddr "+nftSet(lowerAll(x.SrcMAC)))
	}
	s4, s6, _ := fwAddrs(x.SrcIP)
	d4, d6, _ := fwAddrs(x.DestIP)
	fams := []string{""}
	if len(x.SrcIP) > 0 || len(x.DestIP) > 0 {
		fams = fwFamilies(s4, s6, d4, d6, len(x.SrcIP) > 0, len(x.DestIP) > 0)
	}
	hasProto := map[string]bool{}
	for _, p := range x.Proto {
		hasProto[p] = true
	}
	verdict := x.Action
	if x.Action == "reject" {
		verdict = "reject with icmpx admin-prohibited"
		if len(x.Proto) == 1 && hasProto["tcp"] {
			verdict = "reject with tcp reset"
		}
	}
	if x.Counter {
		verdict = "counter " + verdict
	}
	var out []string
	for _, fam := range fams {
		parts := append([]string{}, base...)
		src, dst := s4, d4
		if fam == "ip6" {
			src, dst = s6, d6
		}
		if fam != "" && len(src) > 0 {
			parts = append(parts, fam+" saddr "+nftSet(src))
		}
		if fam != "" && len(dst) > 0 {
			parts = append(parts, fam+" daddr "+nftSet(dst))
		}
		switch {
		case len(x.Proto) == 0:
		case x.DestPort != "":
			ports, _ := fwPortList(x.DestPort)
			if len(x.Proto) == 1 {
				parts = append(parts, x.Proto[0]+" dport "+nftSet(ports))
			} else {
				parts = append(parts, "meta l4proto { tcp, udp } th dport "+nftSet(ports))
			}
		default:
			var l4 []string
			for _, p := range []string{"tcp", "udp"} {
				if hasProto[p] {
					l4 = append(l4, p)
				}
			}
			if hasProto["icmp"] {
				if fam != "ip6" {
					l4 = append(l4, "icmp")
				}
				if fam != "ip" {
					l4 = append(l4, "ipv6-icmp")
				}
			}
			parts = append(parts, "meta l4proto "+nftSet(l4))
		}
		for _, tm := range fwTimeMatches(x.Schedule, clk) {
			m := strings.Join(append(append([]string{}, parts...), tm), " ")
			m = strings.TrimSpace(m)
			if m != "" {
				m += " "
			}
			if x.Log {
				out = append(out, fmt.Sprintf("%slimit rate 10/minute burst 5 packets log prefix %q level info", m, "mr-rule "+x.Name+": "))
			}
			out = append(out, fmt.Sprintf("%s%s comment %q", m, verdict, "rule:"+x.Name))
		}
	}
	return out
}

// ---- device access control ----

// fwAccessMACs: an entry's MACs and those of its devices / groups, lowercase, each once.
func fwAccessMACs(c *Config, a FwAccess) []string {
	return dedup(append(lowerAll(a.MACs), devMACs(c, a.Devices)...))
}

// fwAccessEntries returns the indices of enabled access entries.
func fwAccessEntries(c *Config) []int {
	var out []int
	for i, a := range c.Firewall.Access {
		if on(a.Enabled) && len(fwAccessMACs(c, a)) > 0 {
			out = append(out, i)
		}
	}
	return out
}

// fwAccessForward: rules at the top of the forward chain (before flow offload). Every packet a
// controlled device sends records its address in @ac_4/@ac_6 (all devices) and @acN_4/@acN_6
// (entry N); the offload rule skips those addresses, so the device's connections always stay on
// the CPU path and a time window also cuts connections that were opened before it started.
// During a window both directions are dropped: out by MAC, back in by the learned address.
func fwAccessForward(c *Config, clk fwClock) []string {
	var out []string
	lanSide := "{ " + quoteList(c.LANBridges()) + " }"
	wanSet := "{ " + quoteList(c.WANIfnames()) + " }"
	for _, i := range fwAccessEntries(c) {
		a := c.Firewall.Access[i]
		macs := nftSet(fwAccessMACs(c, a))
		cm := fmt.Sprintf("%q", "access:"+a.Name)
		out = append(out,
			fmt.Sprintf("iifname %s ether saddr %s update @ac_4 { ip saddr } update @ac%d_4 { ip saddr }", lanSide, macs, i),
			fmt.Sprintf("iifname %s ether saddr %s update @ac_6 { ip6 saddr } update @ac%d_6 { ip6 saddr }", lanSide, macs, i))
		for _, tm := range fwTimeMatches(a.Schedule, clk) {
			if tm != "" {
				tm += " "
			}
			out = append(out,
				fmt.Sprintf("iifname %s ether saddr %s oifname %s %scounter drop comment %s", lanSide, macs, wanSet, tm, cm),
				fmt.Sprintf("iifname %s ip daddr @ac%d_4 %scounter drop comment %s", wanSet, i, tm, cm),
				fmt.Sprintf("iifname %s ip6 daddr @ac%d_6 %scounter drop comment %s", wanSet, i, tm, cm))
		}
	}
	return out
}

// fwAccessInput: during a window a controlled device cannot use the router as a gateway either
// (e.g. a transparent proxy that intercepts to a local socket): traffic that is not for one of the
// router's own addresses is dropped. DHCP / DNS / broadcast / multicast (ND, MLD) keep working.
// The match is "not local/broadcast/multicast/anycast" rather than "unicast": for IPv6 the fib type
// comes from a route lookup, so without an IPv6 default route a proxied destination is
// "unreachable", not "unicast", and would slip through.
func fwAccessInput(c *Config, clk fwClock) []string {
	var out []string
	lanSide := "{ " + quoteList(c.LANBridges()) + " }"
	for _, i := range fwAccessEntries(c) {
		a := c.Firewall.Access[i]
		for _, tm := range fwTimeMatches(a.Schedule, clk) {
			if tm != "" {
				tm += " "
			}
			out = append(out, fmt.Sprintf("iifname %s ether saddr %s %sfib daddr type != { local, broadcast, multicast, anycast } counter drop comment %q", lanSide, nftSet(fwAccessMACs(c, a)), tm, "access:"+a.Name))
		}
	}
	return out
}

// fwAccessElements: current addresses of controlled devices (neighbour table + static DHCP hosts,
// plus the addresses the previous ruleset had learned, which keep them off the offload path only)
// as `add element` commands, loaded in the same transaction as the ruleset so a reload (which
// empties the learned sets) does not let an established connection of a controlled device slip into
// the offload path.
// Addresses only known from the previous sets keep their remaining lifetime, so a reload never
// extends it (a stale address would otherwise stay off the offload path for as long as reloads
// come more often than the set timeout).
func fwAccessElements(c *Config, neigh []fwNeigh, prev []fwLearnedElem) string {
	idx := map[string][]int{}
	for _, i := range fwAccessEntries(c) {
		for _, m := range fwAccessMACs(c, c.Firewall.Access[i]) {
			idx[m] = append(idx[m], i)
		}
	}
	if len(idx) == 0 {
		return ""
	}
	for _, h := range c.knownHosts() {
		neigh = append(neigh, fwNeigh{Dst: h.IP, LLAddr: h.MAC})
	}
	elems := map[string][]string{}
	left := map[string]int{} // "set addr" → remaining seconds; 0 = full set timeout (address seen now)
	add := func(set, addr string, secs int) {
		k := set + " " + addr
		if old, seen := left[k]; seen {
			if old != 0 && (secs == 0 || secs > old) {
				left[k] = secs
			}
			return
		}
		left[k] = secs
		elems[set] = append(elems[set], addr)
	}
	fam := func(ip net.IP) string {
		if ip.To4() != nil {
			return "4"
		}
		return "6"
	}
	for _, p := range prev {
		if ip := net.ParseIP(p.Val); ip != nil && !ip.IsUnspecified() && p.Expires > 0 {
			add("ac_"+fam(ip), ip.String(), p.Expires)
		}
	}
	for _, nb := range neigh {
		ids := idx[strings.ToLower(nb.LLAddr)]
		ip := net.ParseIP(nb.Dst)
		if len(ids) == 0 || ip == nil || ip.IsLinkLocalUnicast() || ip.IsMulticast() || ip.IsUnspecified() {
			continue
		}
		add("ac_"+fam(ip), ip.String(), 0)
		for _, i := range ids {
			add(fmt.Sprintf("ac%d_%s", i, fam(ip)), ip.String(), 0)
		}
	}
	keys := make([]string, 0, len(elems))
	for k := range elems {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	for _, k := range keys {
		var xs []string
		for _, a := range elems[k] {
			if s := left[k+" "+a]; s > 0 {
				a = fmt.Sprintf("%s timeout %ds", a, s)
			}
			xs = append(xs, a)
		}
		fmt.Fprintf(&b, "add element inet mr %s { %s }\n", k, strings.Join(xs, ", "))
	}
	return b.String()
}

type fwNeigh struct {
	Dst    string `json:"dst"`
	LLAddr string `json:"lladdr"`
}

// fwLearnedElem is an address in a loaded @ac_4/@ac_6 set and its remaining lifetime in seconds.
type fwLearnedElem struct {
	Val     string
	Expires int
}

// fwLearned returns the addresses in the loaded @ac_4/@ac_6 sets (before a reload replaces them).
func fwLearned() []fwLearnedElem {
	var out []fwLearnedElem
	for _, s := range []string{"ac_4", "ac_6"} {
		if o, err := run("nft", "-j", "list", "set", "inet", "mr", s); err == nil {
			out = append(out, fwSetElems([]byte(o))...)
		}
	}
	return out
}

// fwSetElems extracts {"elem": {"val": ..., "expires": ...}} elements from `nft -j list set`
// output. Elements without an expiry (about to time out, or a set without timeouts) are skipped.
func fwSetElems(b []byte) []fwLearnedElem {
	var doc struct {
		Nftables []struct {
			Set *struct {
				Elem []json.RawMessage `json:"elem"`
			} `json:"set"`
		} `json:"nftables"`
	}
	var out []fwLearnedElem
	if json.Unmarshal(b, &doc) != nil {
		return nil
	}
	for _, it := range doc.Nftables {
		if it.Set == nil {
			continue
		}
		for _, e := range it.Set.Elem {
			var wrapped struct {
				Elem struct {
					Val     string `json:"val"`
					Expires int    `json:"expires"`
				} `json:"elem"`
			}
			if json.Unmarshal(e, &wrapped) == nil && wrapped.Elem.Val != "" && wrapped.Elem.Expires > 0 {
				out = append(out, fwLearnedElem{wrapped.Elem.Val, wrapped.Elem.Expires})
			}
		}
	}
	return out
}

// fwAccessScript returns the `add element` commands that refill the learned access-control sets
// after a reload: the previous sets' addresses (prev) plus the neighbour table and static leases.
func fwAccessScript(c *Config, prev []fwLearnedElem) string {
	if len(fwAccessEntries(c)) == 0 {
		return ""
	}
	var neigh []fwNeigh
	if out, err := run("ip", "-j", "neigh", "show"); err == nil {
		json.Unmarshal([]byte(out), &neigh)
	}
	return fwAccessElements(c, neigh, prev)
}

// ---- shared helpers (used by other modules too) ----

func quoteList(xs []string) string {
	q := make([]string, len(xs))
	for i, x := range xs {
		q[i] = fmt.Sprintf("%q", x)
	}
	return strings.Join(q, ", ")
}

func nftPorts(p string) string { return p } // "a-b" is already nft range syntax

func netdevExists(name string) bool {
	_, err := os.Stat("/sys/class/net/" + name)
	return err == nil
}

// fwLockFile serializes reloads: the runtime state a reload carries over (learned sets, pauses) is
// read under it, so two reloads at once (a PPPoE hook during `mr pause`) cannot load a stale copy last.
var fwLockFile = RunDir + "/fw.lock"

// fwLoad renders against live devices and loads atomically; keeps the last good ruleset on failure.
func fwLoad(c *Config) error {
	if lk := flock(fwLockFile, true); lk != nil {
		defer lk.Close()
	}
	rules := renderNft(c, netdevExists)
	path := GenDir + "/nftables.nft"
	tmp := path + ".new"
	if err := os.WriteFile(tmp, []byte(rules), 0644); err != nil {
		return err
	}
	if out, err := run("nft", "-c", "-f", tmp); err != nil {
		os.Remove(tmp)
		return fmt.Errorf("nft check failed: %v\n%s", err, out)
	}
	// The learned access-control sets are refilled in the same transaction that replaces the
	// ruleset. Refilled afterwards, a reply packet of a controlled device's running download that
	// arrives in between (sets still empty) puts the connection into the flowtable (hardware
	// offload), where a later time window can no longer cut it.
	var elems string
	if len(fwAccessEntries(c)) > 0 {
		elems = fwAccessScript(c, fwLearned())
	}
	// the addresses dnsmasq learned for policy_routes domains (net module): dnsmasq only adds them when
	// it asks upstream, so a reload that emptied the sets would send cached names to the wrong WAN
	elems += policyDomainCarry(c)
	// active pauses (dev module): their sets and rules, in the same transaction. Replacing the table
	// also replaces the flowtable, so a paused device's offloaded flows come back to the CPU path,
	// where these rules drop them in both directions.
	elems += pauseScript(c)
	loaded := false
	if elems != "" {
		if out, err := runStdin(rules+elems, "nft", "-f", "-"); err == nil {
			loaded = true
		} else {
			logf("fw: loading with the learned set addresses failed, loading without: %v %s", err, strings.TrimSpace(out))
		}
	}
	if !loaded {
		if out, err := run("nft", "-f", tmp); err != nil {
			os.Remove(tmp)
			return fmt.Errorf("nft load failed: %v\n%s", err, out)
		}
		if elems != "" {
			if out, err := runStdin(elems, "nft", "-f", "-"); err != nil {
				logf("fw: learned set addresses: %v %s", err, strings.TrimSpace(out)) // best effort: the sets also learn from traffic
			}
		}
	}
	if err := os.Rename(tmp, path); err != nil {
		return err
	}
	return refreshLan6()
}

// refreshLan6 keeps @lan6 = link-local + multicast + the global prefixes currently on the LAN bridge.
func refreshLan6() error {
	c, err := loadConfig(ConfigPath, SecretsPath)
	if err != nil {
		return err
	}
	out, err := run("ip", "-6", "-o", "addr", "show", "dev", c.LAN.Bridge, "scope", "global")
	if err != nil {
		return nil // bridge not up yet
	}
	elems := []string{"fe80::/10", "ff00::/8"}
	for _, l := range strings.Split(out, "\n") {
		f := strings.Fields(l)
		for i := 0; i+1 < len(f); i++ {
			if f[i] == "inet6" {
				if _, n, err := net.ParseCIDR(f[i+1]); err == nil {
					elems = append(elems, n.String())
				}
			}
		}
	}
	script := fmt.Sprintf("flush set inet mr lan6\nadd element inet mr lan6 { %s }\n", strings.Join(dedup(elems), ", "))
	script += pd6Script(c)
	_, err = runStdin(script, "nft", "-f", "-")
	return err
}

func dedup(xs []string) []string {
	seen := map[string]bool{}
	var o []string
	for _, x := range xs {
		if !seen[x] {
			seen[x] = true
			o = append(o, x)
		}
	}
	return o
}
