package main

// net module: generated files (pppd peers, per-WAN service instances, dhcpcd, igmpproxy, health
// checker config), network.sh fragments and nftables rules. Pure functions of the config, except
// that the balance map leaves out WANs the health checker currently reports down.

import (
	"fmt"
	"net"
	"slices"
	"sort"
	"strings"
)

// perfScript spreads packet work over the 4 cores: CPU0 keeps timers/console, each ethernet
// IRQ (rx/tx rings) gets its own core, mt76 gets CPU3, and RPS fans software-path flows over CPUs 1-3.
// Flows bound to the PPE / WED never reach the CPU at all.
const perfScript = `# spread IRQs and RPS over CPUs 1-3
i=1; for q in $(awk '/ethernet$/{sub(":","",$1); print $1}' /proc/interrupts); do echo $((1 << i)) > /proc/irq/$q/smp_affinity 2>/dev/null; i=$((i % 2 + 1)); done
for q in $(awk '/mt7915e$/{sub(":","",$1); print $1}' /proc/interrupts); do echo 8 > /proc/irq/$q/smp_affinity 2>/dev/null; done
for f in /sys/class/net/*/queues/rx-*/rps_cpus; do case $f in */lo/*) ;; *) echo e > $f 2>/dev/null;; esac; done
for f in /sys/class/net/*/queues/rx-*/rps_flow_cnt; do case $f in */lo/*) ;; *) echo 4096 > $f 2>/dev/null;; esac; done
`

// Rule preferences (tailscale 5210-5270 < from-WAN-address 5290 < main-without-default 5299 < fwmark 5300).
const (
	prefFromLocal = RulePref - 10 // replies the router sends from a WAN address leave via that WAN
	prefSuppress  = RulePref - 1  // main table minus default routes: LAN-side / connected / static routes win over marks
)

// wanmonConf is sourced by the health checker (rootfs/usr/libexec/mr/net-wanmon).
const wanmonConf = GenDir + "/wanmon.conf"

func netRender(c *Config, out *Out) error {
	// policy_routes domains_file: an unreadable file or a bad line stops the render (the nft and
	// dnsmasq renderers skip what they cannot read)
	if _, err := policyDomains(c, true); err != nil {
		return err
	}
	for _, w := range c.WAN {
		switch w.Proto {
		case "pppoe":
			pw, err := c.Secret(w.Password)
			if err != nil {
				return err
			}
			out.Add("/etc/ppp/peers/"+w.Name, 0600, renderPeer(w, pw, len(dialEarlier(c.MultiWAN, w.Name)) == 0))
			out.Add("/etc/init.d/mr-pppoe."+w.Name, 0755, renderInstance("mr-pppoe", w, ""))
		case "dhcp":
			out.Add("/etc/init.d/mr-udhcpc."+w.Name, 0755, renderInstance("mr-udhcpc", w, w.Ifname()))
		}
	}
	out.Add("/etc/dhcpcd.conf", 0644, renderDhcpcd(c))
	if c.Mcast.IGMPProxy {
		out.Add("/etc/igmpproxy.conf", 0644, renderIgmpproxy(c))
	}
	if c.MultiWAN.Enabled() {
		out.Add(wanmonConf, 0644, renderWanmon(c))
	}
	return nil
}

// renderInstance: a per-WAN OpenRC service is a two-line script that sources the shared one
// (rootfs/etc/init.d/<base>); OpenRC names it after the file, so RC_SVCNAME=<base>.<wan>.
// Generating it (instead of relying on symlinks made at image build time) means a WAN added later
// from the web UI or router.yaml gets its service too.
func renderInstance(base string, w WAN, dev string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "#!/sbin/openrc-run\n# generated by mr for WAN %s — service logic in /etc/init.d/%s\n", w.Name, base)
	if dev != "" {
		fmt.Fprintf(&b, "MR_WAN_DEV=%s\n", dev)
	}
	fmt.Fprintf(&b, ". /etc/init.d/%s\n", base)
	return b.String()
}

func renderIgmpproxy(c *Config) string {
	var b strings.Builder
	b.WriteString("# generated by mr — edit router.yaml instead\nquickleave\n")
	for _, w := range c.WAN {
		role := "disabled"
		if w.Name == c.Mcast.Upstream {
			role = "upstream"
		}
		fmt.Fprintf(&b, "phyint %s %s ratelimit 0 threshold 1\n", w.Ifname(), role)
		if role == "upstream" {
			b.WriteString("  altnet 0.0.0.0/0\n")
		}
	}
	fmt.Fprintf(&b, "phyint %s downstream ratelimit 0 threshold 1\n", c.LAN.Bridge)
	return b.String()
}

func pppQuote(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}

// renderPeer: pppd options of a PPPoE WAN. persist (redial inside pppd) except for a WAN that dials after
// others (multiwan.dial_order): its pppd exits when the link drops and supervise-daemon starts
// pppoe-dial again (respawn_delay 5 s), which waits for the earlier WANs first (mod_net_dial.go).
func renderPeer(w WAN, password string, persist bool) string {
	var b strings.Builder
	b.WriteString("# generated by mr — edit router.yaml instead\n")
	fmt.Fprintf(&b, "plugin pppoe.so\nnic-%s\nifname %s\nipparam %s\n", w.LinkDev(), w.Ifname(), w.Name)
	fmt.Fprintf(&b, "user %s\npassword %s\n", pppQuote(w.Username), pppQuote(password))
	// above 1492: RFC 4638 (PPP-Max-Payload, see wanLinkMTUs); pppd falls back to 1492 by itself
	fmt.Fprintf(&b, "mtu %d\nmru %d\n", w.MTU, w.MTU)
	b.WriteString("noauth\nhide-password\nnoipdefault\nnodefaultroute\nnodetach\n")
	if persist {
		b.WriteString("persist\nmaxfail 0\nholdoff 5\n")
	}
	b.WriteString("lcp-echo-interval 5\nlcp-echo-failure 5\nlcp-echo-adaptive\n")
	if w.IPv6 {
		b.WriteString("+ipv6\n")
	} else {
		b.WriteString("noipv6\n")
	}
	if w.PeerDNS {
		b.WriteString("usepeerdns\n")
	}
	return b.String()
}

func renderDhcpcd(c *Config) string {
	var b strings.Builder
	b.WriteString("# generated by mr — edit router.yaml instead\n")
	b.WriteString("duid\npersistent\noption rapid_commit\nnoipv4ll\nnohook resolv.conf\n")
	var allow []string
	for _, w := range c.WAN {
		if w.IPv6 {
			allow = append(allow, w.Ifname())
		}
	}
	if len(allow) == 0 {
		b.WriteString("denyinterfaces *\n")
		return b.String()
	}
	fmt.Fprintf(&b, "allowinterfaces %s\n", strings.Join(allow, " "))
	for i, w := range c.WAN {
		if !w.IPv6 {
			continue
		}
		// ipv6only: IPv4 comes from pppd / udhcpc / the static address, never from dhcpcd
		fmt.Fprintf(&b, "\ninterface %s\n  ipv6only\n  ipv6rs\n  metric %d\n", w.Ifname(), 1024+w.Metric)
		// not a dhcpcd option: recorded so that toggling it restarts dhcpcd, whose events then add or
		// remove the IPv6 source route (hookDhcpcd)
		fmt.Fprintf(&b, "  # mr: ipv6_srcroute=%t\n", w.SrcRoute)
		if w.IPv6PD {
			fmt.Fprintf(&b, "  ia_pd %d %s/0/64/1\n", i+1, c.LAN.Bridge)
		}
	}
	return b.String()
}

// renderWanmon: settings for the health-check loop (/usr/libexec/mr/net-wanmon), sourced as sh.
// Every value is validated (numbers, IPv4 targets, WAN names, netdev names).
func renderWanmon(c *Config) string {
	m := c.MultiWAN
	var wans []string
	for _, w := range c.WAN {
		wans = append(wans, w.Name+":"+w.Ifname())
	}
	return fmt.Sprintf("# generated by mr — edit router.yaml (multiwan) instead\nINTERVAL=%d\nTIMEOUT=%d\nFALL=%d\nRISE=%d\nTARGETS=%q\nWANS=%q\n",
		m.Interval, m.Timeout, m.Fall, m.Rise, strings.Join(m.Targets, " "), strings.Join(wans, " "))
}

// wanDNSFromPeers: WANs whose DNS servers (from PPPoE / DHCP / static config) feed dnsmasq.
func wanDNSFromPeers(c *Config) bool {
	for _, w := range c.WAN {
		if (w.Proto == "static" && len(w.DNS) > 0) || (w.Proto != "static" && w.PeerDNS) {
			return true
		}
	}
	return false
}

// The net hooks keep resolvConf = nameservers of every WAN that is up (healthy first); the dns
// module points dnsmasq at it in "isp" upstream mode (dnsUpstreamLines).

// pppoeOverhead: the PPPoE header (6) and the PPP protocol field (2) inside the Ethernet payload.
const pppoeOverhead = 8

// wanLinkMTUs is the MTU network.sh gives each WAN-side ethernet device (0 = not touched):
//   - PPPoE with mtu above 1492: mtu + 8. That is RFC 4638 ("baby jumbo" frames): with mtu/mru
//     above 1492 pppd's pppoe plugin sends the PPP-Max-Payload tag, and when the access concentrator
//     does not echo it pppd limits the session to 1492 by itself. pppd never asks for more than the
//     link MTU - 8, so a link the kernel could not raise also ends at 1492.
//   - DHCP / static: the configured mtu (0 = leave it).
//   - the parent of a VLAN subinterface: at least what the subinterface needs.
//   - otherwise plain Ethernet's 1500: it undoes an earlier 1508 (also after a PPPoE WAN became
//     DHCP / static: the device would keep 1508 as its IP MTU), and keeps a VLAN subinterface of a
//     device raised above 1500 at 1500 (a new VLAN device inherits its parent's MTU).
//
// On a DSA switch port the kernel raises the conduit (e.g. eth0) by the tag overhead by itself.
func wanLinkMTUs(c *Config) map[string]int {
	need := map[string]int{}
	up := func(w WAN, m int) {
		for _, dev := range []string{w.LinkDev(), w.Device} {
			if m > need[dev] {
				need[dev] = m
			}
		}
	}
	for _, w := range c.WAN {
		if w.Proto != "pppoe" {
			up(w, w.MTU)
		} else if w.MTU > 1500-pppoeOverhead {
			up(w, w.MTU+pppoeOverhead)
		}
	}
	for _, w := range c.WAN {
		if w.Proto != "pppoe" && w.MTU > 0 {
			continue
		}
		m := 1500
		if p := need[w.Device]; w.VLAN > 0 && p > 0 && p < m {
			m = p // never above the parent
		}
		for _, dev := range []string{w.Device, w.LinkDev()} {
			if need[dev] == 0 {
				need[dev] = m
			}
		}
	}
	return need
}

func netSh(c *Config, phase string, b *strings.Builder) {
	switch phase {
	case "links":
		links := map[string]bool{}
		// the kernel skips an unchanged MTU; a changed one ends every PPPoE session on that device
		// (they redial by themselves)
		need, mtuSet := wanLinkMTUs(c), map[string]bool{}
		setMTU := func(dev string) {
			if m := need[dev]; m > 0 && !mtuSet[dev] {
				mtuSet[dev] = true
				fmt.Fprintf(b, "ip link set dev %s mtu %d\n", dev, m)
			}
		}
		for _, w := range c.WAN {
			if w.MAC != "" {
				fmt.Fprintf(b, "if [ \"$(cat /sys/class/net/%s/address)\" != %s ]; then ip link set %s down; ip link set %s address %s; fi\n",
					w.Device, strings.ToLower(w.MAC), w.Device, w.Device, strings.ToLower(w.MAC))
			}
			if !links[w.Device] {
				fmt.Fprintf(b, "ip link set %s up\n", w.Device)
			}
			setMTU(w.Device) // before a VLAN on it: a subinterface cannot exceed its parent
			if w.VLAN > 0 && !links[w.LinkDev()] {
				vlanLink(b, w.Device, w.VLAN)
				fmt.Fprintf(b, "ip link set %s up\n", w.LinkDev())
			}
			setMTU(w.LinkDev())
			links[w.Device], links[w.LinkDev()] = true, true
			if w.Proto == "static" {
				// add the configured address first, then drop any other IPv4 address (old static / DHCP lease).
				// promote_secondaries: a new address in the old one's subnet is a secondary, and deleting the
				// old primary would otherwise take it along (kernel default 0)
				fmt.Fprintf(b, "echo 1 2>/dev/null > /proc/sys/net/ipv4/conf/%s/promote_secondaries\n", w.LinkDev())
				fmt.Fprintf(b, "ip addr replace %s dev %s\n", w.IPv4, w.LinkDev())
				fmt.Fprintf(b, "for a in $(ip -4 -o addr show dev %s | awk '{print $4}'); do [ \"$a\" = %s ] || ip addr del \"$a\" dev %s; done\n", w.LinkDev(), w.IPv4, w.LinkDev())
			}
		}
		snoop := 0
		if c.Mcast.Snooping {
			snoop = 1
		}
		type brdef struct {
			br, ipv4 string
			ports    []string
		}
		brs := []brdef{{c.LAN.Bridge, c.LAN.IPv4, c.LAN.Ports}}
		for _, n := range c.Networks {
			brs = append(brs, brdef{n.BridgeName(), n.IPv4, n.Ports})
		}
		for _, d := range brs {
			fmt.Fprintf(b, "ip link show %s >/dev/null 2>&1 || ip link add %s type bridge\n", d.br, d.br)
			fmt.Fprintf(b, "echo %d > /sys/class/net/%s/bridge/multicast_snooping 2>/dev/null\n", snoop, d.br)
			for _, p := range d.ports {
				fmt.Fprintf(b, "ip link set %s master %s 2>/dev/null; ip link set %s up\n", p, d.br, p)
			}
			fmt.Fprintf(b, "ip addr replace %s dev %s\nip link set %s up\n", d.ipv4, d.br, d.br)
		}
		// tagged VLANs: <port>.<vid> joins the network's bridge; the port itself keeps its untagged role
		for _, n := range c.Networks {
			for _, p := range n.Trunk {
				sub := fmt.Sprintf("%s.%d", p, n.VLAN)
				fmt.Fprintf(b, "ip link set %s up\n", p)
				vlanLink(b, p, n.VLAN)
				fmt.Fprintf(b, "ip link set %s master %s 2>/dev/null; ip link set %s up\n", sub, n.BridgeName(), sub)
			}
		}
	case "routes":
		for _, fam := range []string{"-4", "-6"} {
			// destinations with a specific route in main (LAN-side networks, connected WAN subnets, static
			// routes) never follow a policy / balance mark; only default-route traffic does
			fmt.Fprintf(b, "while ip %s rule del pref %d 2>/dev/null; do :; done; ip %s rule add lookup main suppress_prefixlength 0 pref %d\n",
				fam, prefSuppress, fam, prefSuppress)
			// per-WAN fwmark rules (connmark keeps each connection on the WAN it arrived on; policy routes
			// and the balancer reuse them). Flushed first so a changed table/mark leaves no stale rule.
			fmt.Fprintf(b, "while ip %s rule del pref %d 2>/dev/null; do :; done\n", fam, RulePref)
			for _, w := range c.WAN {
				t, m := c.WANTable(w.Name)
				fmt.Fprintf(b, "ip %s rule add fwmark %s lookup %d pref %d\n", fam, m, t, RulePref)
			}
		}
		// the default routes themselves are installed by the ppp / udhcpc hooks and `mr routes` when a WAN is up.
		// static routes (routes via a PPPoE device are re-added by `mr routes` when it comes up)
		for _, r := range c.Routes {
			fam := "-4"
			if strings.Contains(r.Target, ":") {
				fam = "-6"
			}
			args := []string{"ip", fam, "route", "replace", r.Target}
			if r.Via != "" {
				args = append(args, "via", r.Via)
			}
			if r.Dev != "" {
				args = append(args, "dev", r.Dev)
			}
			if r.Metric > 0 {
				args = append(args, "metric", fmt.Sprint(r.Metric))
			}
			if r.Table > 0 {
				args = append(args, "table", fmt.Sprint(r.Table))
			}
			fmt.Fprintf(b, "%s 2>/dev/null\n", strings.Join(args, " "))
		}
	case "tail":
		b.WriteString(perfScript)
	}
	modeNetSh(c, phase, b)
}

func vlanLink(b *strings.Builder, dev string, vid int) {
	fmt.Fprintf(b, "ip link show %s.%d >/dev/null 2>&1 || ip link add link %s name %s.%d type vlan id %d\n", dev, vid, dev, dev, vid, vid)
}

// nftIfnames renders one interface name or an anonymous set of them.
func nftIfnames(xs []string) string {
	if len(xs) == 1 {
		return fmt.Sprintf("%q", xs[0])
	}
	return "{ " + quoteList(xs) + " }"
}

// lanNets4 is every LAN-side IPv4 network (nft value: one CIDR or an anonymous set).
func lanNets4(c *Config) string {
	var nets []string
	for _, ln := range c.LANNets() {
		if _, n, err := net.ParseCIDR(ln.IPv4); err == nil {
			nets = append(nets, n.String())
		}
	}
	if len(nets) == 1 {
		return nets[0]
	}
	return "{ " + strings.Join(nets, ", ") + " }"
}

func family(n *net.IPNet) int {
	if isV4(n) {
		return 4
	}
	return 6
}

// cidrStr prints a host route as a bare address.
func cidrStr(n *net.IPNet) string {
	if ones, bits := n.Mask.Size(); ones == bits {
		return n.IP.String()
	}
	return n.String()
}

// policyHead: the LAN-side interfaces and the source MAC(s) every rule of policy p starts with.
func policyHead(c *Config, p Policy) string {
	head := "iifname " + nftIfnames(c.LANBridges())
	if p.MAC != "" {
		head += " ether saddr " + strings.ToLower(p.MAC)
	} else if p.Device != "" {
		head += " ether saddr " + nftSet(devMACs(c, []string{p.Device}))
	}
	return head
}

// policyFallbackRules (hook forward_first): a policy with fallback: drop may only use its own WAN.
// While that WAN has no route (down, or failed the health check: its table lost the default route)
// the mark lookup falls through to the main table and would leave through another WAN; this rule
// drops exactly that, for established connections too (it sits before flow offload and the
// established accept). Destinations routed elsewhere (LAN, tailscale) are not affected.
func policyFallbackRules(c *Config) []string {
	var out []string
	for i, p := range c.Policy {
		w := c.WANByName(p.Via)
		if p.Fallback != "drop" || w == nil {
			continue
		}
		var others []string
		for _, x := range c.WANIfnames() {
			if x != w.Ifname() {
				others = append(others, x)
			}
		}
		if len(others) == 0 {
			continue
		}
		var src, dst *net.IPNet
		if p.Src != "" {
			src, _ = parseIPOrCIDR(p.Src)
		}
		if p.Dst != "" {
			dst, _ = parseIPOrCIDR(p.Dst)
		}
		for _, fam := range policyFams(p) {
			s := policyHead(c, p)
			kw := map[int]string{4: "ip", 6: "ip6"}[fam]
			if src == nil && dst == nil && !p.byDomain() && (fam == 4 || p.NAT6) {
				s += map[int]string{4: " meta nfproto ipv4", 6: " meta nfproto ipv6"}[fam]
			}
			if src != nil {
				s += fmt.Sprintf(" %s saddr %s", kw, cidrStr(src))
			}
			if fam == 6 && !p.NAT6 {
				// only what the policy routes (policyRules): a source from another WAN's prefix is left
				// unmarked on purpose and takes the default route (Cd1s/mini-router#63). With nat6 every
				// source is routed, so all of the device's IPv6 is dropped (#108).
				s += " ip6 saddr @" + pd6Set(c, p.Via)
			}
			if dst != nil {
				s += fmt.Sprintf(" %s daddr %s", kw, cidrStr(dst))
			}
			if p.byDomain() {
				s += fmt.Sprintf(" %s daddr @%s", kw, policySet(i, fam))
			}
			out = append(out, fmt.Sprintf("%s oifname %s counter drop comment %q", s, nftIfnames(others), "fallback:"+p.Name))
		}
	}
	return out
}

// policyRules: nft rules (mark hook) for policy route i; one per address family it covers.
func policyRules(c *Config, i int, p Policy) []string {
	_, mark := c.WANTable(p.Via)
	head := policyHead(c, p)
	var src, dst *net.IPNet
	if p.Src != "" {
		src, _ = parseIPOrCIDR(p.Src)
	}
	if p.Dst != "" {
		dst, _ = parseIPOrCIDR(p.Dst)
	}
	var out []string
	for _, fam := range policyFams(p) { // src / dst decide the family; otherwise both
		s := head
		kw := "ip"
		if fam == 6 {
			kw = "ip6"
		}
		if src != nil {
			s += fmt.Sprintf(" %s saddr %s", kw, cidrStr(src))
		}
		pre, s := s, ""
		switch {
		case dst != nil:
			s += fmt.Sprintf(" %s daddr %s", kw, cidrStr(dst))
		case p.byDomain(): // the destination is a learned address (below)
		case fam == 4:
			s += " ip daddr != " + lanNets4(c)
		default:
			s += " ip6 daddr != @lan6"
		}
		if p.byDomain() {
			// addresses dnsmasq learned for the domains; a new connection restarts the address's timer
			set := policySet(i, fam)
			s += fmt.Sprintf(" %s daddr @%s ct state new update @%s { %s daddr }", kw, set, set, kw)
		} else {
			s += " ct state new"
		}
		// the first policy that matches decides (config order): return ends this chain for the packet
		act := fmt.Sprintf(" ct mark set %s meta mark set %s return comment %q", mark, mark, p.Name)
		if fam == 4 {
			out = append(out, pre+s+act)
			continue
		}
		// only a source inside the prefix this WAN delegated can leave through it as is: an address from
		// another WAN's prefix would be dropped upstream (Cd1s/mini-router#63). Unmarked, it takes the
		// default route. The set is filled from the dhcpcd hook's record (pd6Script).
		set := pd6Set(c, p.Via)
		out = append(out, pre+" ip6 saddr @"+set+s+act)
		if p.NAT6 {
			// nat6 (#108): other sources go to npt6m_<i>, which marks them only while the WAN has a prefix
			// (pd6Script); srcnat then translates them into that prefix (npt6n_<i>)
			out = append(out, fmt.Sprintf("%s ip6 saddr != @%s%s jump npt6m_%d comment %q", pre, set, s, i, p.Name))
		}
	}
	return out
}

// nat6Rules (hook srcnat): a nat6 policy's connections leaving its WAN from a foreign prefix get the
// WAN's prefix (npt6n_<i>, filled by pd6Script).
func nat6Rules(c *Config) []string {
	var out []string
	for _, i := range nat6Policies(c) {
		p := c.Policy[i]
		_, mark := c.WANTable(p.Via)
		out = append(out, fmt.Sprintf("oifname %q meta mark %s ip6 saddr != @%s jump npt6n_%d", c.WANByName(p.Via).Ifname(), mark, pd6Set(c, p.Via), i))
	}
	return out
}

// nat6Policies: indexes of the policies with nat6 that route IPv6 through a known WAN.
func nat6Policies(c *Config) []int {
	var out []int
	for i, p := range c.Policy {
		if p.NAT6 && c.WANByName(p.Via) != nil && slices.Contains(policyFams(p), 6) {
			out = append(out, i)
		}
	}
	return out
}

type lbMember struct {
	name, mark string
	weight     int
}

// balanceMembers: WANs that take new connections right now (weight > 0, netdev present, not down).
func balanceMembers(c *Config, exists func(string) bool) []lbMember {
	if c.MultiWAN.Mode != "balance" {
		return nil
	}
	health := readWanState()
	var out []lbMember
	for _, w := range c.WAN {
		wt := c.MultiWAN.Weight(w.Name)
		if wt <= 0 || !exists(w.Ifname()) || health[w.Name] == "down" {
			continue
		}
		_, m := c.WANTable(w.Name)
		out = append(out, lbMember{w.Name, m, wt})
	}
	return out
}

// balanceRule: weighted per-connection choice of WAN for new IPv4 connections from LAN-side networks.
// Only unmarked connections are balanced (policy routes and connmark-restored flows win), the mark is
// stored in the conntrack entry so every later packet of the connection keeps its WAN.
func balanceRule(c *Config, members []lbMember) string {
	total := 0
	var elems []string
	for _, m := range members {
		lo, hi := total, total+m.weight-1
		if lo == hi {
			elems = append(elems, fmt.Sprintf("%d : %s", lo, m.mark))
		} else {
			elems = append(elems, fmt.Sprintf("%d-%d : %s", lo, hi, m.mark))
		}
		total += m.weight
	}
	return fmt.Sprintf("iifname %s ip daddr != %s ct state new meta mark 0x0 ct mark set numgen random mod %d map { %s } meta mark set ct mark comment \"multiwan-balance\"",
		nftIfnames(c.LANBridges()), lanNets4(c), total, strings.Join(elems, ", "))
}

func netNft(c *Config, hook string, n *Nft) {
	switch hook {
	case "defs":
		policyDomainDefs(c, n)
		for _, name := range pd6WANs(c) {
			n.W("set %s { type ipv6_addr; flags interval; auto-merge; comment \"prefixes delegated by wan %s\"; }", pd6Set(c, name), name)
		}
		for _, i := range nat6Policies(c) {
			// filled by pd6Script (empty = no prefix: unmarked, not translated)
			n.W("chain npt6m_%d {\n\t}", i)
			n.W("chain npt6n_%d {\n\t}", i)
		}
	case "srcnat":
		for _, r := range nat6Rules(c) {
			n.W("%s", r)
		}
	case "forward_first":
		for _, r := range policyFallbackRules(c) {
			n.W("%s", r)
		}
	case "mark":
		// connmark: remember which WAN an inbound connection used; LAN-side packets of that connection
		// (replies, port-forward traffic) get the mark back and leave through the same WAN.
		// Policy routes and the balancer only steer NEW outbound connections.
		if len(c.WAN) < 2 && len(c.Policy) == 0 {
			return
		}
		for _, x := range c.WAN {
			_, m := c.WANTable(x.Name)
			n.W("iifname %q ct state new ct mark set %s", x.Ifname(), m)
		}
		for _, br := range c.LANBridges() {
			n.W("iifname %q ct mark != 0x0 meta mark set ct mark return", br)
		}
		for i, p := range c.Policy {
			for _, r := range policyRules(c, i, p) {
				n.W("%s", r)
			}
		}
		if m := balanceMembers(c, n.Exists); len(m) >= 2 {
			n.W("%s", balanceRule(c, m))
		}
	case "forward":
		if c.Mcast.IGMPProxy {
			if up := c.WANByName(c.Mcast.Upstream); up != nil {
				n.W("iifname %q ip daddr 224.0.0.0/4 accept comment \"igmpproxy\"", up.Ifname())
			}
		}
	}
}

// sortedWANs returns WAN names ordered by preference: healthy first, then metric, then config order.
func sortedWANs(c *Config, health map[string]string) []*WAN {
	var ws []*WAN
	for i := range c.WAN {
		ws = append(ws, &c.WAN[i])
	}
	sort.SliceStable(ws, func(i, j int) bool {
		di, dj := health[ws[i].Name] == "down", health[ws[j].Name] == "down"
		if di != dj {
			return !di
		}
		return ws[i].Metric < ws[j].Metric
	})
	return ws
}
