package main

// sys module: SSH (dropbear) and root's authorized_keys.
//
// services.ssh.authorized_keys is rendered as a marked block inside /root/.ssh/authorized_keys.
// Every line outside the block (keys installed by the image build or by hand) is kept exactly as
// it is, so mr can never remove a key it did not add: removing a key in router.yaml only removes it
// from the block. Key lines are validated strictly (known key type, base64 blob whose embedded type
// matches, printable comment; no "command=..."-style options).

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// authKeysFile is root's authorized_keys (a variable so tests can point it elsewhere).
var authKeysFile = "/root/.ssh/authorized_keys"

const (
	akBegin = "# --- begin mini-router managed keys (router.yaml services.ssh.authorized_keys) ---"
	akEnd   = "# --- end mini-router managed keys ---"
)

var sshKeyTypes = map[string]bool{
	"ssh-ed25519": true, "ssh-rsa": true,
	"ecdsa-sha2-nistp256": true, "ecdsa-sha2-nistp384": true, "ecdsa-sha2-nistp521": true,
	"sk-ssh-ed25519@openssh.com": true, "sk-ecdsa-sha2-nistp256@openssh.com": true,
}

type authKey struct {
	Type    string `json:"type"`
	Comment string `json:"comment"`
	FP      string `json:"fingerprint"` // SHA256:... like ssh-keygen -l
	line    string // normalized "type base64 [comment]"
}

// parseAuthKey validates one public key line ("type base64 [comment]").
func parseAuthKey(line string) (*authKey, error) {
	if !safeText(line) {
		return nil, fmt.Errorf("control characters")
	}
	f := strings.Fields(line)
	if len(f) < 2 {
		return nil, fmt.Errorf("want \"type base64 [comment]\"")
	}
	if !sshKeyTypes[f[0]] {
		return nil, fmt.Errorf("unsupported key type %q (plain keys only, no options like command=)", clip(f[0], 40))
	}
	raw, err := base64.StdEncoding.DecodeString(f[1])
	if err != nil || len(raw) < 4 || len(raw) > 4096 {
		return nil, fmt.Errorf("key data is not valid base64")
	}
	n := binary.BigEndian.Uint32(raw)
	if uint64(n)+4 > uint64(len(raw)) || string(raw[4:4+n]) != f[0] {
		return nil, fmt.Errorf("key data does not match type %s", f[0])
	}
	comment := strings.Join(f[2:], " ")
	if len(comment) > 200 {
		return nil, fmt.Errorf("comment longer than 200 characters")
	}
	sum := sha256.Sum256(raw)
	k := &authKey{Type: f[0], Comment: comment, FP: "SHA256:" + base64.RawStdEncoding.EncodeToString(sum[:])}
	k.line = f[0] + " " + f[1]
	if comment != "" {
		k.line += " " + comment
	}
	return k, nil
}

func clip(s string, n int) string {
	if len(s) > n {
		return s[:n] + "…"
	}
	return s
}

func validateSSH(c *Config, v *Validator) {
	s := c.Services.SSH
	if s.Port < 1 || s.Port > 65535 {
		v.Add("services.ssh.port: 1-65535")
	}
	switch s.Port {
	case 53, 67, 80, 123, 547:
		v.Add("services.ssh.port: %d is used by the router itself", s.Port)
	}
	if c.Services.Tailscale.Enabled && s.Port == c.Services.Tailscale.Port {
		v.Add("services.ssh.port: same as services.tailscale.port")
	}
	if len(s.Keys) > 32 {
		v.Add("services.ssh.authorized_keys: at most 32 keys")
	}
	seen := map[string]bool{}
	for i, l := range s.Keys {
		k, err := parseAuthKey(l)
		if err != nil {
			v.Add("services.ssh.authorized_keys[%d]: %v", i, err)
			continue
		}
		if seen[k.FP] {
			v.Add("services.ssh.authorized_keys[%d]: duplicate key %s", i, k.FP)
		}
		seen[k.FP] = true
	}
}

// sshListenAddrs: the router's IPv4 address on every LAN-zone network (services.ssh.lan_only).
func sshListenAddrs(c *Config) []string {
	var out []string
	for _, ln := range c.LANNets() {
		if ln.Zone != "lan" {
			continue
		}
		if ip, _, ok := strings.Cut(ln.IPv4, "/"); ok && ip != "" {
			out = append(out, ip)
		}
	}
	return dedup(out)
}

func renderDropbear(c *Config) string {
	s := c.Services.SSH
	var opts []string
	if addrs := sshListenAddrs(c); s.LANOnly && len(addrs) > 0 {
		for _, a := range addrs {
			opts = append(opts, "-p", a+":"+strconv.Itoa(s.Port))
		}
	} else {
		opts = append(opts, "-p", strconv.Itoa(s.Port))
	}
	opts = append(opts, "-K", "300")
	if !s.PasswordLogin {
		opts = append(opts, "-s", "-g")
	}
	return fmt.Sprintf("# generated by mr\nDROPBEAR_OPTS=%q\n", strings.Join(opts, " "))
}

// mergeManaged returns cur with the block between begin and end replaced by lines (the block is
// removed when lines is empty). Every line outside the block is kept as it is. A begin marker
// without an end marker extends the block to the end of the file (everything after it was
// written by mr); a stray end marker is dropped. ok=false: nothing to write (no block before and
// none wanted).
func mergeManaged(cur, begin, end string, lines []string) (string, bool) {
	text := strings.TrimSuffix(cur, "\n")
	var keep []string
	at, inside, had := -1, false, false
	if text != "" {
		for _, l := range strings.Split(text, "\n") {
			switch {
			case l == begin:
				had, inside = true, true
				if at < 0 {
					at = len(keep)
				}
			case l == end:
				had, inside = true, false
			case !inside:
				keep = append(keep, l)
			}
		}
	}
	if !had && len(lines) == 0 {
		return cur, false
	}
	var block []string
	if len(lines) > 0 {
		block = append(append([]string{begin}, lines...), end)
	}
	if at < 0 {
		at = len(keep)
	}
	out := append(append(append([]string{}, keep[:at]...), block...), keep[at:]...)
	if len(out) == 0 {
		return "", true
	}
	return strings.Join(out, "\n") + "\n", true
}

// renderAuthKeys: root's authorized_keys with the managed block (ok=false: leave the file alone).
func renderAuthKeys(c *Config) (string, bool) {
	var lines []string
	for _, l := range c.Services.SSH.Keys {
		if k, err := parseAuthKey(l); err == nil {
			lines = append(lines, k.line)
		}
	}
	cur, _ := os.ReadFile(authKeysFile)
	return mergeManaged(string(cur), akBegin, akEnd, lines)
}

// apiSysSSHKeys lists the keys in root's authorized_keys (type, comment, fingerprint), split into
// the managed block and the rest, and whether root has a password (for password logins).
func apiSysSSHKeys(r apiReq) apiResp {
	managed, other := []authKey{}, []authKey{}
	invalid := 0
	b, err := os.ReadFile(authKeysFile)
	inside := false
	for _, l := range strings.Split(string(b), "\n") {
		t := strings.TrimSpace(l)
		switch {
		case t == akBegin:
			inside = true
			continue
		case t == akEnd:
			inside = false
			continue
		case t == "" || strings.HasPrefix(t, "#"):
			continue
		}
		k, perr := parseAuthKey(t)
		if perr != nil {
			// options-prefixed or unknown lines outside the block still count as "other"
			invalid++
			continue
		}
		if inside {
			managed = append(managed, *k)
		} else {
			other = append(other, *k)
		}
	}
	return apiResp{body: map[string]any{
		"file": authKeysFile, "exists": err == nil, "managed": managed, "other": other,
		"other_unparsed": invalid, "root_password": rootPasswordState(),
	}}
}

// rootPasswordState: "set", "locked" (* or !...) or "empty"; "" if /etc/shadow is unreadable.
// Only the state is reported, never the hash.
func rootPasswordState() string {
	b, err := os.ReadFile("/etc/shadow")
	if err != nil {
		return ""
	}
	for _, l := range strings.Split(string(b), "\n") {
		f := strings.SplitN(l, ":", 3)
		if len(f) < 2 || f[0] != "root" {
			continue
		}
		switch {
		case f[1] == "":
			return "empty"
		case f[1] == "*" || strings.HasPrefix(f[1], "!"):
			return "locked"
		}
		return "set"
	}
	return ""
}
