package main

import (
	"strings"
)

// File is one generated artifact.
type File struct {
	Path string
	Mode uint32
	Data string
}

// netShPhases is the order of network.sh fragments (see Module.NetSh).
var netShPhases = []string{"links", "wifi", "routes", "tail"}

// Render produces every generated file. It never touches the running system.
func Render(c *Config) ([]File, error) {
	out := &Out{}
	out.Add(GenDir+"/network.sh", 0755, renderNetwork(c))
	for _, m := range modules {
		if m.Render != nil {
			if err := m.Render(c, out); err != nil {
				return nil, err
			}
		}
	}
	out.Add(GenDir+"/services", 0644, strings.Join(enabledServices(c), "\n")+"\n")
	return out.files, nil
}

// renderNetwork: idempotent link/bridge/address/route setup, run by the mr-network service at boot
// and re-run in place by apply. Assembled from every module's NetSh fragments, phase by phase.
func renderNetwork(c *Config) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n# generated by mr — edit router.yaml instead\nset -u\n")
	b.WriteString("ip link set lo up\nip link set eth0 up 2>/dev/null\n")
	for _, ph := range netShPhases {
		b.WriteString("# --- " + ph + "\n")
		for _, m := range modules {
			if m.NetSh != nil {
				m.NetSh(c, ph, &b)
			}
		}
	}
	return b.String()
}

// enabledServices: every OpenRC service the config wants in the default runlevel.
func enabledServices(c *Config) []string {
	s := []string{"mr-network", "mr-firewall"}
	if c.System.Watchdog == nil || *c.System.Watchdog {
		s = append(s, "watchdog")
	}
	for _, m := range modules {
		if m.Services != nil {
			s = append(s, m.Services(c)...)
		}
	}
	return dedup(s)
}

// dnsmasqExtra collects extra dnsmasq.conf lines from every module.
func dnsmasqExtra(c *Config) []string {
	var out []string
	for _, m := range modules {
		if m.Dnsmasq != nil {
			out = append(out, m.Dnsmasq(c)...)
		}
	}
	return out
}
